import {DEFAULT_GRADING,validateGrading,gradedSizes,gradedPatternSvg,type Grading} from './grading.ts';
import {validateProject,type Project} from './model.ts';
const fields=[['waistStep','Waist increment per size (cm)'],['hemStep','Hem increment per size (cm)'],['slantStep','Slant increment per size (cm)'],['steps','Steps on each side of base']] as const;
export const gradingMarkup=`<section class="grading-panel" aria-labelledby="grading-heading"><h4 id="grading-heading">Grade a relative size set</h4><p class="fine-print">Manual linear increments, 3–7 sizes around the committed base. These are relative sizes, not standardized body sizes or validated fit.</p><div class="construction-fields">${fields.map(([key,label])=>`<label>${label}<input id="grading-${key}" type="text" inputmode="decimal" maxlength="40" value="${DEFAULT_GRADING[key]}"></label>`).join('')}</div><div class="construction-actions"><button id="grading-apply" class="quiet">Apply grading rule</button><button id="grading-discard" class="quiet">Discard grading edits</button><button id="grading-remove" class="quiet">Remove grading rule</button><button id="grading-export" class="quiet">Export graded pattern set SVG</button></div><div id="grading-table" role="region" aria-label="Committed size measurements"></div></section>`;
export function mountGrading(options:{current:()=>Project;commit:(next:Project)=>void;guard:()=>boolean;baseDirty:()=>boolean;notice:(text:string,error?:boolean)=>void;download:(blob:Blob,suffix:string)=>void}){
 const input=(key:keyof Grading)=>document.getElementById(`grading-${key}`) as HTMLInputElement;let signature='';
 function reset(){const r=options.current().grading??DEFAULT_GRADING;for(const [key] of fields)input(key).value=String(r[key]);}
 function dirty(){const r=options.current().grading??DEFAULT_GRADING;return fields.some(([key])=>input(key).value!==String(r[key]));}
 function render(p:Project){const next=JSON.stringify(p.grading??null);if(next!==signature){signature=next;reset();}const host=document.getElementById('grading-table')!;if(!p.grading||!p.construction){host.textContent='Apply a measured base, then a grading rule to create the size set.';return;}host.innerHTML='<table><caption>Committed relative sizes · cm</caption><thead><tr><th>Size</th><th>Waist</th><th>Hem</th><th>Slant</th></tr></thead><tbody>'+gradedSizes(p.construction,p.grading).map(({offset,draft})=>`<tr><th>Base ${offset>=0?'+':''}${offset}</th><td>${draft.waist}</td><td>${draft.hem}</td><td>${draft.slant}</td></tr>`).join('')+'</tbody></table>';}
 for(const action of ['apply','discard','remove','export']){const button=document.getElementById(`grading-${action}`)!;button.addEventListener('pointerdown',event=>event.preventDefault());button.addEventListener('click',()=>{if(action==='discard'){reset();options.notice('Grading drafts discarded.');return;}if(!options.guard())return;try{if(action==='remove'){const next={...options.current()};delete next.grading;options.commit(validateProject(next));reset();options.notice('Grading rule removed; the base and pattern drafts are retained. Undo restores the rule.');return;}if(options.baseDirty())throw new Error('Apply or discard pattern drafts before grading.');const p=options.current();if(!p.construction)throw new Error('Apply a measured base before grading.');if(action==='apply'){const raw=Object.fromEntries(fields.map(([key])=>{const value=input(key).value;if(!value.trim())throw new Error(`${key} is required.`);return [key,Number(value)];}));const r=validateGrading(raw);gradedSizes(p.construction,r);options.commit(validateProject({...p,grading:r}));reset();options.notice('Grading rule applied to the complete concept.');}else{if(dirty())throw new Error('Apply or discard grading drafts before exporting.');if(!p.grading)throw new Error('Apply a grading rule before exporting.');options.download(new Blob([gradedPatternSvg(p.construction,p.grading)],{type:'image/svg+xml;charset=utf-8'}),'-graded-skirt-patterns.svg');options.notice('All relative sizes exported at full scale. Check each 5 cm square; no seam or hem allowance.');}}catch(error){options.notice(error instanceof Error?error.message:'Could not grade the pattern.',true);}});}
 return {render,reset,dirty};
}
