import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { test, expect, propose, claim, accept, snapshot, revision, api, privateLink, credentials, chooseImage, submitImage, retained, verifyPixels } from './https-lan-fixtures.ts';

const AUDIT = ['created', 'opponent_joined', 'terms_edited', 'accepted', 'evidence_image_added', 'evidence_image_added', 'result_proposed', 'result_responded', 'arbiter_nominated', 'arbiter_responded', 'invite_issued', 'arbiter_joined', 'arbiter_decided'];
const RESOLUTION = { method: 'arbiter', by: 'arbiter', outcome: 'opponent', proposalId: null, reason: 'The supplied record supports Mira; this is our agreed decision.' };

test('three HTTPS seats explicitly agree, retain exact reviewed images and arbitrate an immutable record across whole service restart', async ({ lan }, info) => {
  test.setTimeout(90000); const contexts = await Promise.all([lan.browser.newContext(), lan.browser.newContext(), lan.browser.newContext()]); const [owner, opponent, arbiter] = await Promise.all(contexts.map(context => context.newPage()));
  try {
    const invitation = await propose(owner, lan); expect(invitation.includes(lan.setup)).toBe(false); expect(await owner.evaluate(key => JSON.stringify({ local: { ...localStorage }, session: { ...sessionStorage } }).includes(key), lan.setup)).toBe(false); await claim(opponent, invitation); expect((await snapshot(opponent)).status).toBe('proposed'); const id = (await credentials(owner)).id;
    await opponent.route(`**/api/challenges/${id}`, route => route.request().method() === 'GET' ? route.abort('failed') : route.continue());
    await opponent.locator('#decline-form [name=reason]').fill('Unsent original reasoning Ω'); await revision(owner); await owner.locator('#terms-form [name=successCriteria]').fill('Share two completed original studies.'); await owner.getByRole('button', { name: 'Save terms', exact: true }).click(); await expect.poll(async () => (await snapshot(owner)).termsVersion).toBe(2);
    const stale = opponent.waitForResponse(response => response.url().endsWith('/accept')); opponent.once('dialog', dialog => dialog.accept()); await opponent.getByRole('button', { name: 'Accept these terms', exact: true }).click(); expect((await stale).status()).toBe(409); expect((await snapshot(owner)).status).toBe('proposed'); await expect(opponent.locator('#decline-form [name=reason]')).toHaveValue('Unsent original reasoning Ω');
    await opponent.unroute(`**/api/challenges/${id}`); await opponent.getByRole('button', { name: 'Review updated terms', exact: true }).click(); await accept(opponent); expect((await snapshot(opponent)).events.filter(event => event.kind === 'accepted').map(event => event.details)).toEqual([{ termsVersion: 2 }]);
    const preview = await chooseImage(owner), firstDescriptor = verifyPixels(preview, 96, 64), first = await submitImage(owner); expect(first.image).toEqual(firstDescriptor); expect(first.text).toBe('Original supplied panels <literal> Ω'); expect(await retained(opponent, first.id)).toEqual(preview);
    const secondPreview = await chooseImage(opponent, true), secondDescriptor = verifyPixels(secondPreview, 72, 48), second = await submitImage(opponent); expect(second.image).toEqual(secondDescriptor);
    await revision(owner); await owner.locator('#result-form [name=outcome]').selectOption('proposer'); await owner.locator('#result-form [name=reason]').fill('Arden believes the first study met the terms.'); await owner.getByRole('button', { name: 'Propose result', exact: true }).click();
    await revision(opponent); await opponent.locator('#result-response-form [name=reason]').fill('Mira disputes which study met the revised terms.'); await opponent.getByRole('button', { name: 'Dispute result', exact: true }).click(); await expect.poll(async () => (await snapshot(owner)).status).toBe('disputed');
    await revision(owner); await owner.locator('#arbiter-form [name=name]').fill('Rowan'); await owner.locator('#arbiter-form [name=reason]').fill('Rowan can review our supplied studies.'); await owner.getByRole('button', { name: 'Nominate arbiter', exact: true }).click();
    const nomination = (await snapshot(owner)).arbiterNomination!; let current = await snapshot(owner); expect((await api(owner, '/invite', { revision: current.revision, seat: 'arbiter' })).status).toBe(409);
    await revision(opponent); opponent.once('dialog', dialog => dialog.accept()); await opponent.getByRole('button', { name: 'Approve arbiter', exact: true }).click(); await expect.poll(async () => (await snapshot(owner)).arbiterNomination?.status).toBe('approved'); expect((await snapshot(owner)).arbiterNomination?.id).toBe(nomination.id);
    await revision(owner); await owner.getByRole('button', { name: 'Invite arbiter', exact: true }).click();
    // Clicking starts the request; the real invitation is available only after its response.
    // Return a boolean so a failed readiness assertion never prints the private token.
    await expect.poll(async () => {
      const value = await owner.locator('#shared-link').inputValue();
      if (!value) return false;
      const link = new URL(value);
      return link.origin === lan.origin && link.pathname === '/' && link.search === `?challenge=${id}` && /^#arbiter=[a-f0-9]{64}$/.test(link.hash);
    }).toBe(true);
    const arbiterInvitation = await owner.locator('#shared-link').inputValue(); await owner.getByRole('button', { name: 'Close link', exact: true }).click(); await claim(arbiter, arbiterInvitation, true);
    expect(await retained(arbiter, first.id)).toEqual(preview); expect(await retained(arbiter, second.id)).toEqual(secondPreview); current = await snapshot(owner); expect((await api(owner, '/arbiter/decide', { revision: current.revision, outcome: 'proposer', reason: 'Proposer has no arbiter authority.' })).status).toBe(403);
    await revision(arbiter); await arbiter.locator('#decision-form [name=outcome]').selectOption('opponent'); await arbiter.locator('#decision-form [name=reason]').fill(RESOLUTION.reason); arbiter.once('dialog', dialog => dialog.accept()); await arbiter.getByRole('button', { name: 'Record decision', exact: true }).click(); await expect.poll(async () => (await snapshot(owner)).status).toBe('resolved'); const final = await snapshot(arbiter); expect(final.resolution).toMatchObject(RESOLUTION); expect(final.events.map(event => event.kind)).toEqual(AUDIT);
    const privateSeats = await Promise.all([owner, opponent, arbiter].map(credentials)); const links = await Promise.all([owner, opponent, arbiter].map(privateLink)); expect(new Set(privateSeats.map(seat => seat.token)).size).toBe(3); expect(await contexts[0].cookies()).toEqual([]);
    const denied = await owner.evaluate(async ({ id, evidence, setup }) => { const path = `/api/challenges/${id}/evidence/${evidence}/image`; return Promise.all([{}, { Authorization: `Bearer ${'f'.repeat(64)}` }, { 'X-Friendly-Setup-Key': setup }].map(async headers => (await fetch(path, { headers: headers as Record<string, string> })).status)); }, { id, evidence: first.id, setup: lan.setup }); expect(denied).toEqual([401, 401, 401]);
    await contexts[0].addCookies([{ name: 'capability', value: privateSeats[0].token, url: lan.origin, secure: true }]); expect(await owner.evaluate(async ({ id, evidence }) => (await fetch(`/api/challenges/${id}/evidence/${evidence}/image`, { credentials: 'include' })).status, { id, evidence: first.id })).toBe(401); await contexts[0].clearCookies();
    const jsonDownload = arbiter.waitForEvent('download'); await arbiter.getByRole('button', { name: 'Export record', exact: true }).click(); const jsonFile = await jsonDownload, jsonBytes = await readFile((await jsonFile.path())!), record = JSON.parse(jsonBytes.toString()) as { challenge: Record<string, unknown> };
    const htmlDownload = arbiter.waitForEvent('download'); await arbiter.locator('#export-images').click(); const htmlFile = await htmlDownload, htmlBytes = await readFile((await htmlFile.path())!), html = htmlBytes.toString(); expect(html).not.toMatch(/<script\b|\son\w+\s*=/i);
    const parsed = await arbiter.evaluate(text => { const doc = new DOMParser().parseFromString(text, 'text/html'); return { images: [...doc.querySelectorAll('img')].map(image => image.getAttribute('src')!), records: [...doc.querySelectorAll('pre')].flatMap(pre => { try { return [JSON.parse(pre.textContent!) as { challenge?: Record<string, unknown> }]; } catch { return []; } }) }; }, html);
    expect(parsed.images.map(source => Buffer.from(source.split(',')[1], 'base64'))).toEqual([preview, secondPreview]); parsed.images.forEach((source, i) => verifyPixels(Buffer.from(source.split(',')[1], 'base64'), i ? 72 : 96, i ? 48 : 64)); expect(parsed.records.find(item => item.challenge)?.challenge).toEqual(record.challenge); expect(record.challenge.events).toEqual(final.events); expect(record.challenge.resolution).toEqual(final.resolution);
    const secrets = [lan.setup, ...privateSeats.map(seat => seat.token), new URL(invitation).hash.split('=')[1], new URL(arbiterInvitation).hash.split('=')[1]]; expect(secrets.some(secret => html.includes(secret) || jsonBytes.toString().includes(secret) || html.includes(createHash('sha256').update(secret).digest('hex')))).toBe(false);
    await lan.restart(); for (const page of [owner, opponent, arbiter]) { await page.reload(); await expect(page.locator('#challenge-status')).toContainText('resolved'); const current = await snapshot(page); expect(current.events).toEqual(final.events); expect(current.resolution).toEqual(final.resolution); expect(await retained(page, first.id)).toEqual(preview); }
    const fresh = await lan.browser.newContext(), recovery = await fresh.newPage(); try { for (let i = 0; i < links.length; i++) { await recovery.goto(links[i]); if (i > 0) recovery.once('dialog', dialog => dialog.accept()); await recovery.getByRole('button', { name: 'Use this private access link', exact: true }).click(); await expect.poll(async () => (await snapshot(recovery)).myRole).toBe(['proposer', 'opponent', 'arbiter'][i]); } await propose(recovery, lan, 'Separate HTTPS authority108'); const unrelated = await credentials(recovery); const cross = await recovery.evaluate(async ({ id, token, evidence }) => Promise.all([`/api/challenges/${id}`, `/api/challenges/${id}/evidence/${evidence}/image`].map(async path => (await fetch(path, { headers: { Authorization: `Bearer ${token}` }, credentials: 'omit' })).status)), { id, token: unrelated.token, evidence: first.id }); expect(cross).toEqual([401, 401]); await recovery.goto(invitation); await recovery.locator('#claim-form [name=name]').fill('Fourth seat'); recovery.once('dialog', dialog => dialog.accept()); await recovery.getByRole('button', { name: 'Claim opponent seat', exact: true }).click(); await expect(recovery.locator('#message')).toContainText(/used|claimed|invalid|available/i); } finally { await fresh.close(); }
    await jsonFile.saveAs(info.outputPath('public-record.json')); await htmlFile.saveAs(info.outputPath('complete-images.html')); await writeFile(info.outputPath('reviewed-first.jpg'), preview); await writeFile(info.outputPath('reviewed-second.jpg'), secondPreview); await writeFile(info.outputPath('media-audit-verification.json'), JSON.stringify({ firstDescriptor, secondDescriptor, eventKinds: AUDIT, termsVersion: 2, resolution: RESOLUTION, restartExact: true, noPrivateMaterial: true }, null, 2));
    await owner.screenshot({ path: info.outputPath('https-agreement-desktop.png'), fullPage: true }); await owner.setViewportSize({ width: 390, height: 844 }); expect(await owner.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); await owner.screenshot({ path: info.outputPath('https-agreement-390.png'), fullPage: true });
  } finally { await Promise.all(contexts.map(context => context.close())); }
});

test('unknown HTTPS status blocks only creation and explicit retry preserves independent private access', async ({ lan }) => {
  const a = await lan.browser.newContext(), b = await lan.browser.newContext(), owner = await a.newPage(), page = await b.newPage();
  try {
    await propose(owner, lan, 'Recovery without setup108'); const link = await privateLink(owner);
    await page.route('**/api/status', route => route.abort('failed')); await page.goto(lan.origin); await expect(page.getByRole('button', { name: 'Propose challenge', exact: true })).toBeDisabled();
    await page.goto(link); await page.getByRole('button', { name: 'Use this private access link', exact: true }).click(); expect((await snapshot(page)).myRole).toBe('proposer'); await expect(page.locator('#setup-key')).toHaveValue('');
    await page.getByRole('button', { name: 'Back to challenges', exact: true }).click(); await page.unroute('**/api/status'); await page.locator('#retry-transport-status').click(); await expect(page.locator('#transport-status')).toContainText(lan.origin); const card = page.locator('#challenge-list .record-card').filter({ has: page.getByRole('heading', { name: 'Recovery without setup108', exact: true }) }); await expect(card).toBeVisible(); await card.getByRole('button', { name: 'Open challenge', exact: true }).click(); await expect.poll(async () => (await snapshot(page)).terms.title).toBe('Recovery without setup108');
  } finally { await a.close(); await b.close(); }
});

test('a lost real creation response clears setup immediately without storing the key or replaying authority', async ({ lan }) => {
  const context = await lan.browser.newContext(), page = await context.newPage();
  try {
    await page.goto(lan.origin); await expect(page.locator('#setup-key')).toBeVisible(); const form = page.locator('#create-form');
    await form.locator('[name=name]').fill('Arden'); await form.locator('[name=title]').fill('Lost original creation108'); await form.locator('[name=description]').fill('An original proposed challenge.'); await form.locator('[name=successCriteria]').fill('Supply the study.'); await form.locator('[name=evidenceRule]').fill('Supplied and unverified.'); await form.locator('[name=deadline]').fill(new Date(Date.now() + 86400000).toISOString().slice(0, 16)); await page.locator('#setup-key').fill(lan.setup);
    await form.locator('[name=title]').fill(''); await form.getByRole('button', { name: 'Propose challenge', exact: true }).click(); expect(await page.locator('#setup-key').inputValue() === lan.setup).toBe(true); await form.locator('[name=title]').fill('Lost original creation108');
    await page.evaluate(() => { const state = window as unknown as { held108?: boolean; release108?: () => void; creates108?: number }; const native = window.fetch; window.fetch = async (...args) => { if (String(args[0]) !== '/api/challenges' || args[1]?.method !== 'POST') return native(...args); state.creates108 = (state.creates108 ?? 0) + 1; const response = await native(...args); if (response.status !== 201) throw new Error('Actual creation did not succeed.'); state.held108 = true; await new Promise<void>(done => { state.release108 = done; }); throw new TypeError('Controlled loss after actual committed HTTPS creation'); }; });
    await form.getByRole('button', { name: 'Propose challenge', exact: true }).click(); await expect.poll(() => page.evaluate(() => (window as unknown as { held108?: boolean }).held108)).toBe(true); await expect(page.locator('#setup-key')).toHaveValue(''); await page.evaluate(() => (window as unknown as { release108?: () => void }).release108?.()); await expect(page.locator('#message')).toContainText(/unknown|confirm|arriv|network|reach|creat/i);
    expect(await page.evaluate(key => JSON.stringify({ local: { ...localStorage }, session: { ...sessionStorage } }).includes(key), lan.setup)).toBe(false); expect(await page.evaluate(() => (window as unknown as { creates108?: number }).creates108)).toBe(1);
    await page.locator('#setup-key').fill(lan.setup); await page.evaluate(() => dispatchEvent(new PageTransitionEvent('pagehide', { persisted: true }))); await expect(page.locator('#setup-key')).toHaveValue('');
  } finally { await context.close(); }
});

test('successful creation after changed-back input retains the issued seat without activating over newer form intent', async ({ lan }) => {
  const context = await lan.browser.newContext(), page = await context.newPage();
  try {
    await page.goto(lan.origin); await expect(page.locator('#setup-key')).toBeVisible(); const form = page.locator('#create-form'); await form.locator('[name=name]').fill('Arden'); await form.locator('[name=title]').fill('Preserved new intent108'); await form.locator('[name=description]').fill('Original study.'); await form.locator('[name=successCriteria]').fill('Supply study.'); await form.locator('[name=evidenceRule]').fill('Supplied image.'); await form.locator('[name=deadline]').fill(new Date(Date.now() + 86400000).toISOString().slice(0, 16)); await page.locator('#setup-key').fill(lan.setup);
    await page.evaluate(() => { const state = window as unknown as { held108?: boolean; release108?: () => void; completed108?: boolean }; const native = window.fetch; window.fetch = async (...args) => { const response = await native(...args); if (String(args[0]) === '/api/challenges' && args[1]?.method === 'POST') { state.held108 = true; await new Promise<void>(done => { state.release108 = done; }); state.completed108 = true; } return response; }; });
    await form.getByRole('button', { name: 'Propose challenge', exact: true }).click(); await expect.poll(() => page.evaluate(() => (window as unknown as { held108?: boolean }).held108)).toBe(true); const title = form.locator('[name=title]'); await title.fill('Temporary deliberate input'); await title.fill('Preserved new intent108'); await title.focus(); await title.evaluate((node: HTMLInputElement) => node.setSelectionRange(4, 9));
    await page.evaluate(() => (window as unknown as { release108?: () => void }).release108?.()); await expect.poll(() => page.evaluate(() => Object.keys(JSON.parse(localStorage.getItem('friendly-challenges.sessions.v1') || '{}')).length)).toBe(1); await expect(form).toBeVisible(); await expect(title).toHaveValue('Preserved new intent108'); await expect(title).toBeFocused(); expect(await title.evaluate((node: HTMLInputElement) => [node.selectionStart, node.selectionEnd])).toEqual([4, 9]); expect(new URL(page.url()).searchParams.has('challenge')).toBe(false);
  } finally { await context.close(); }
});

test('late actual image append receipt preserves changed-back caption and retained preview without a second append', async ({ lan }) => {
  const a = await lan.browser.newContext(), b = await lan.browser.newContext(), owner = await a.newPage(), opponent = await b.newPage();
  try {
    const invitation = await propose(owner, lan, 'Late reviewed append108'); await claim(opponent, invitation); await accept(opponent); const preview = await chooseImage(owner); const id = (await credentials(owner)).id;
    await owner.evaluate(id => { const state = window as unknown as { entered108?: boolean; release108?: () => void; append108?: number; finished108?: boolean }; const native = window.fetch; window.fetch = async (...args) => { const response = await native(...args); if (String(args[0]) === `/api/challenges/${id}/evidence/image` && args[1]?.method === 'POST') { state.append108 = (state.append108 ?? 0) + 1; state.entered108 = true; await new Promise<void>(done => { state.release108 = done; }); state.finished108 = true; } return response; }; }, id);
    await owner.locator('#add-image-evidence').click(); await expect.poll(() => owner.evaluate(() => (window as unknown as { entered108?: boolean }).entered108)).toBe(true); const caption = owner.locator('#evidence-form [name=text]'); await caption.fill('Temporary newer caption'); await caption.fill('Original supplied panels <literal> Ω'); await caption.focus(); await caption.evaluate((node: HTMLTextAreaElement) => node.setSelectionRange(5, 10));
    await owner.evaluate(() => (window as unknown as { release108?: () => void }).release108?.()); await expect.poll(async () => (await snapshot(owner)).evidence.length).toBe(1); await expect.poll(() => owner.evaluate(() => (window as unknown as { finished108?: boolean }).finished108)).toBe(true); await expect(caption).toHaveValue('Original supplied panels <literal> Ω'); await expect(caption).toBeFocused(); await expect(owner.locator('#evidence-image-preview')).toBeVisible(); expect(await retained(opponent, (await snapshot(owner)).evidence[0].id)).toEqual(preview); expect(await owner.evaluate(() => (window as unknown as { append108?: number }).append108)).toBe(1);
  } finally { await a.close(); await b.close(); }
});

test('a genuine private hash link queued during real creation remains explicitly usable after creation completes', async ({ lan }) => {
  const a = await lan.browser.newContext(), b = await lan.browser.newContext(), original = await a.newPage(), page = await b.newPage();
  try {
    await propose(original, lan, 'Original queued access108'); const prior = await credentials(original);
    // Token-free initial URL supplies the existing challenge id; assigning the
    // private fragment later performs a genuine same-document hash navigation.
    await page.goto(`${lan.origin}/?challenge=${prior.id}`); await expect(page.locator('#setup-key')).toBeVisible(); const form = page.locator('#create-form'); await form.locator('[name=name]').fill('Mira'); await form.locator('[name=title]').fill('Separate newly created108'); await form.locator('[name=description]').fill('Original pending creation.'); await form.locator('[name=successCriteria]').fill('Finish original study.'); await form.locator('[name=evidenceRule]').fill('Supplied record.'); await form.locator('[name=deadline]').fill(new Date(Date.now() + 86400000).toISOString().slice(0, 16)); await page.locator('#setup-key').fill(lan.setup);
    await page.evaluate(() => { const state = window as unknown as { queued108?: boolean; release108?: () => void }; const native = window.fetch; window.fetch = async (...args) => { const response = await native(...args); if (String(args[0]) === '/api/challenges' && args[1]?.method === 'POST') { state.queued108 = true; await new Promise<void>(done => { state.release108 = done; }); } return response; }; });
    await form.getByRole('button', { name: 'Propose challenge', exact: true }).click(); await expect.poll(() => page.evaluate(() => (window as unknown as { queued108?: boolean }).queued108)).toBe(true); await page.evaluate(token => { location.hash = `access=${token}`; }, prior.token); await expect.poll(() => new URL(page.url()).hash).toBe(''); await expect(page.locator('#message')).toContainText(/Private link received/i);
    await page.evaluate(() => (window as unknown as { release108?: () => void }).release108?.()); await expect.poll(() => page.evaluate(() => Object.keys(JSON.parse(localStorage.getItem('friendly-challenges.sessions.v1') || '{}')).length)).toBe(1);
    await expect(page.locator('#link-intent')).toBeVisible(); await expect(page.getByRole('button', { name: 'Use this private access link', exact: true })).toBeVisible(); await page.getByRole('button', { name: 'Use this private access link', exact: true }).click(); await expect.poll(async () => (await snapshot(page)).terms.title).toBe('Original queued access108'); expect((await snapshot(page)).myRole).toBe('proposer');
  } finally { await a.close(); await b.close(); }
});
