import { test as base, expect, type Browser, type Page } from '@playwright/test';
import { spawn, execFile, execFileSync, type ChildProcess } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdtemp, readFile, writeFile, chmod, rm, access } from 'node:fs/promises';
import { createHash, randomBytes, X509Certificate } from 'node:crypto';
import { createServer } from 'node:net';
import { request } from 'node:https';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
const execute = promisify(execFile);
export interface Lan { origin: string; setup: string; browser: Browser; certificateSha256: string; spki: string; restart(): Promise<void>; }
export const test = base.extend<{ lan: Lan }>({
  lan: async ({ playwright }, use, info) => {
    const directory = await mkdtemp(join(tmpdir(), 'friendly108-native-')), cert = join(directory, 'certificate.pem'), key = join(directory, 'key.pem'), setupPath = join(directory, 'setup');
    let child: ChildProcess | null = null, browser: Browser | null = null; const servicePids: number[] = [], browserPids: number[] = [];
    const stop = async () => { const old = child; child = null; if (!old || old.exitCode !== null) return; const ended = new Promise<void>((done, reject) => { const timer = setTimeout(() => { old.kill('SIGKILL'); reject(new Error('Owned HTTPS service did not stop within ten seconds.')); }, 10000); old.once('exit', () => { clearTimeout(timer); done(); }); }); old.kill('SIGTERM'); await ended; };
    try {
      await execute('openssl', ['req', '-x509', '-newkey', 'rsa:2048', '-nodes', '-keyout', key, '-out', cert, '-days', '2', '-subj', '/CN=localhost', '-addext', 'subjectAltName=IP:127.0.0.1,DNS:localhost']); await chmod(key, 0o600);
      const setup = randomBytes(32).toString('hex'); await writeFile(setupPath, setup + '\n', { mode: 0o600 });
      const certificate = await readFile(cert), publicKey = new X509Certificate(certificate).publicKey.export({ type: 'spki', format: 'der' }), spki = createHash('sha256').update(publicKey).digest('base64');
      const port = await new Promise<number>(done => { const server = createServer(); server.listen(0, '127.0.0.1', () => { const address = server.address(); if (!address || typeof address === 'string') throw new Error('No fixture port.'); server.close(() => done(address.port)); }); });
      const origin = `https://127.0.0.1:${port}`;
      const ready = () => new Promise<boolean>(done => { const req = request(origin + '/api/status', { ca: certificate, timeout: 1000 }, response => { response.resume(); done(response.statusCode === 200); }); req.on('error', () => done(false)); req.on('timeout', () => req.destroy()); req.end(); });
      const start = async () => { child = spawn(process.env.FRIENDLY_PYTHON ?? 'python3', ['-m', 'challenges', '--data-dir', join(directory, 'library'), '--port', String(port), '--bind', '127.0.0.1', '--origin', origin, '--tls-cert', cert, '--tls-key', key, '--setup-token-file', setupPath], { cwd: resolve(import.meta.dirname, '../..'), stdio: 'ignore' }); if (child.pid) servicePids.push(child.pid); await expect.poll(ready, { timeout: 15000, message: 'The actual HTTPS service becomes ready with strict certificate validation.' }).toBe(true); };
      await start(); browser = await playwright.chromium.launch({ ...(process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : {}), args: [`--ignore-certificate-errors-spki-list=${spki}`] });
      const cdp = await browser.newBrowserCDPSession(); const processes = await cdp.send('SystemInfo.getProcessInfo'); browserPids.push(...processes.processInfo.filter(item => item.type === 'browser').map(item => item.id)); await cdp.detach();
      await writeFile(info.outputPath('public-certificate-receipt.json'), JSON.stringify({ certificateSha256: createHash('sha256').update(certificate).digest('hex'), spki, browserVersion: browser.version(), trust: 'Strict CA readiness; Chromium exact fixture SPKI only', physicalDevices: false }, null, 2));
      await use({ origin, setup, browser, certificateSha256: createHash('sha256').update(certificate).digest('hex'), spki, restart: async () => { await stop(); await start(); } });
    } finally { await browser?.close(); await stop(); await rm(directory, { recursive: true, force: true }); const pids = [...servicePids, ...browserPids]; const exited = await Promise.all(pids.map(async pid => { try { await access(`/proc/${pid}`); return false; } catch { return true; } })); await writeFile(info.outputPath('owned-process-closure.json'), JSON.stringify({ servicePids, browserPids, allObservedPidsExited: exited.every(Boolean), noSecretMaterial: true }, null, 2)); }
  },
});
export { expect };

export const ORIGINAL_PNG = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAGAAAABACAIAAABqVuVZAAAAuElEQVR4nO3SoRHCUAAFwSSDQqOjUwcaTWkpgkrQVIT+6uSP2K3gzc1bv/uxXMnrvM+eMNhmD7g6gYJAQaAgUBAoCBQECgIFgYJAQaAgUBAoCBQECgIFgYJAQaAgUBAoCBQECgIFgYJAQaAgUBAoCBRu7/0ze8Pg93jOnjDwoCBQECgIFAQKAgWBgkBBoCBQECgIFAQKAgWBgkBBoCBQECgIFAQKAgWBgkBBoCBQECgIFAQKAgWBwh9rTATCokrFlwAAAABJRU5ErkJggg==', 'base64');
export const ORIGINAL_JPEG = Buffer.from('/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAAwAEgDAREAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD5Hr8fP9UAoAKACgD0b4Af8xb/ALYf+1K8POf+Xfz/AEP8zf2iv/NMf9zv/uoejV4Z/maFABQAUAfOdfcH/TIFABQAUAejfAD/AJi3/bD/ANqV4ec/8u/n+h/mb+0V/wCaY/7nf/dQ9Grwz/M0KACgAoA+c6+4P+mQKACgAoA9G+AH/MW/7Yf+1K8POf8Al38/0P8AM39or/zTH/c7/wC6h6NXhn+ZoUAFABQB8d1/uwf1QFABQAUAfeH/AARM/wCamf8AcF/9vq/yh/ae/wDNJf8Ac/8A+6R+5eDH/Mf/ANwv/ch94V/lCfuQUAFABQB+D9f9Xh/DYUAFABQB94f8ETP+amf9wX/2+r/KH9p7/wA0l/3P/wDukfuXgx/zH/8AcL/3IfeFf5Qn7kFABQAUAfg/X/V4fw2FABQAUAfeH/BEz/mpn/cF/wDb6v8AKH9p7/zSX/c//wC6R+5eDH/Mf/3C/wDch94V/lCfuQUAFABQB//Z', 'base64');
export interface Evidence { id: string; author: string; text: string; image?: { mime: string; width: number; height: number; bytes: number; sha256: string } }
export interface Snapshot { id: string; revision: number; termsVersion: number; status: string; myRole: string; terms: { title: string; successCriteria: string; deadline: number }; evidence: Evidence[]; events: { kind: string; details: Record<string, unknown> }[]; resolution: unknown; arbiterNomination: { id: string; status: string } | null; resultProposal: { id: string } | null }
export async function credentials(page: Page) { await expect.poll(() => new URL(page.url()).searchParams.get('challenge')).toMatch(/^[a-f0-9]{32}$/); const id = new URL(page.url()).searchParams.get('challenge')!; const read = () => page.evaluate(id => (JSON.parse(localStorage.getItem('friendly-challenges.sessions.v1') || '{}') as Record<string, string>)[id], id); await expect.poll(async () => typeof await read() === 'string').toBe(true); return { id, token: await read() }; }
export async function api(page: Page, action = '', body?: Record<string, unknown>) {
  const seat = await credentials(page); return page.evaluate(async ({ id, token, action, body }) => { const response = await fetch(`/api/challenges/${id}${action}`, { method: body ? 'POST' : 'GET', credentials: 'omit', redirect: 'error', headers: { Authorization: `Bearer ${token}`, ...(body ? { 'Content-Type': 'application/json' } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) }); return { status: response.status, value: await response.json() as unknown }; }, { ...seat, action, body });
}
export async function snapshot(page: Page): Promise<Snapshot> { const response = await api(page); expect(response.status).toBe(200); return response.value as Snapshot; }
export async function revision(page: Page) { const current = await snapshot(page); await expect(page.locator('#challenge-revision')).toContainText(`Revision ${current.revision} ·`); return current; }
export async function propose(page: Page, lan: Lan, title = 'Original HTTPS color challenge108', navigate = true) {
  if (navigate) await page.goto(lan.origin); await expect(page.locator('#setup-key')).toBeVisible(); const form = page.locator('#create-form');
  await form.locator('[name=name]').fill('Arden'); await form.locator('[name=title]').fill(title); await form.locator('[name=description]').fill('Each participant draws an original four-panel color study.'); await form.locator('[name=successCriteria]').fill('Share one completed original study.'); await form.locator('[name=evidenceRule]').fill('Supply an original image and literal caption; claims remain unverified.'); await form.locator('[name=stake]').selectOption('pick-a-movie'); await form.locator('[name=deadline]').fill(new Date(Date.now() + 86400000).toISOString().slice(0, 16)); await page.locator('#setup-key').fill(lan.setup);
  await form.getByRole('button', { name: 'Propose challenge', exact: true }).click(); await expect(page.locator('#shared-link')).toHaveValue(/#invite=[a-f0-9]{64}$/); await expect(page.locator('#setup-key')).toHaveValue(''); const invitation = await page.locator('#shared-link').inputValue(); await page.getByRole('button', { name: 'Close link', exact: true }).click(); return invitation;
}
export async function claim(page: Page, invitation: string, arbiter = false) { await page.goto(invitation); await expect.poll(() => new URL(page.url()).hash).toBe(''); await page.locator('#claim-form [name=name]').fill(arbiter ? 'Rowan' : 'Mira'); await page.getByRole('button', { name: arbiter ? 'Claim arbiter seat' : 'Claim opponent seat', exact: true }).click(); await expect.poll(async () => (await snapshot(page)).myRole).toBe(arbiter ? 'arbiter' : 'opponent'); }
export async function accept(page: Page) { page.once('dialog', dialog => dialog.accept()); await page.getByRole('button', { name: 'Accept these terms', exact: true }).click(); await expect.poll(async () => (await snapshot(page)).status).toBe('active'); }
export async function privateLink(page: Page) { await page.getByRole('button', { name: 'My private access link', exact: true }).click(); const value = await page.locator('#shared-link').inputValue(); await page.getByRole('button', { name: 'Close link', exact: true }).click(); return value; }
export async function observeBlobs(page: Page) { await page.evaluate(() => { const root = window as unknown as { observed108Blobs?: Map<string, Blob> }; if (root.observed108Blobs) return; const blobs = root.observed108Blobs = new Map<string, Blob>(), create = URL.createObjectURL.bind(URL), revoke = URL.revokeObjectURL.bind(URL); URL.createObjectURL = object => { const url = create(object); if (object instanceof Blob) blobs.set(url, object); return url; }; URL.revokeObjectURL = url => { blobs.delete(url); revoke(url); }; }); }
export async function chooseImage(page: Page, jpeg = false) { await observeBlobs(page); await revision(page); await page.locator('#evidence-form [name=text]').fill(jpeg ? 'Second supplied JPEG study' : 'Original supplied panels <literal> Ω'); await page.locator('#evidence-image').setInputFiles({ name: jpeg ? 'original-panels.jpg' : 'original-panels.png', mimeType: jpeg ? 'image/jpeg' : 'image/png', buffer: jpeg ? ORIGINAL_JPEG : ORIGINAL_PNG }); await expect(page.locator('#add-image-evidence')).toBeEnabled(); return Buffer.from(await page.locator('#evidence-image-preview').evaluate(async (node: HTMLImageElement) => { await node.decode(); const blob = (window as unknown as { observed108Blobs: Map<string, Blob> }).observed108Blobs.get(node.src); if (!blob) throw new Error('Missing actual reviewed Blob.'); return [...new Uint8Array(await blob.arrayBuffer())]; })); }
export function verifyPixels(bytes: Buffer, width: number, height: number) { const decoded = execFileSync('python3', ['-c', "import sys;from PIL import Image;from io import BytesIO;im=Image.open(BytesIO(sys.stdin.buffer.read()));assert im.format=='JPEG';assert im.mode=='RGB';print('%d %d'%im.size);sys.stdout.flush();sys.stdout.buffer.write(im.tobytes())"], { input: bytes, maxBuffer: 4 * 1024 ** 2, timeout: 10000 }); const newline = decoded.indexOf(10); expect(decoded.subarray(0, newline).toString()).toBe(`${width} ${height}`); const rgb = decoded.subarray(newline + 1); const colors = [[200, 30, 40], [20, 180, 50], [30, 60, 210], [230, 200, 20]]; for (let i = 0; i < 4; i++) { const x = Math.floor(width * (i % 2 ? .75 : .25)), y = Math.floor(height * (i > 1 ? .75 : .25)); for (let c = 0; c < 3; c++) expect(Math.abs(rgb[(y * width + x) * 3 + c] - colors[i][c])).toBeLessThanOrEqual(12); } return { width, height, bytes: bytes.length, sha256: createHash('sha256').update(bytes).digest('hex'), mime: 'image/jpeg' }; }
export async function submitImage(page: Page) { const before = await revision(page); await page.locator('#add-image-evidence').click(); await expect.poll(async () => (await snapshot(page)).evidence.length).toBe(before.evidence.length + 1); return (await snapshot(page)).evidence.at(-1)!; }
export async function retained(page: Page, evidenceId: string) { const seat = await credentials(page); const result = await page.evaluate(async ({ id, token, evidenceId }) => { const response = await fetch(`/api/challenges/${id}/evidence/${evidenceId}/image`, { headers: { Authorization: `Bearer ${token}` }, credentials: 'omit', redirect: 'error' }); return { status: response.status, bytes: [...new Uint8Array(await response.arrayBuffer())] }; }, { ...seat, evidenceId }); expect(result.status).toBe(200); return Buffer.from(result.bytes); }
