import test from 'node:test';
import assert from 'node:assert/strict';
import {createProject,decodeMask} from '../src/model.ts';
import {assignRegion} from '../src/regions.ts';
import {History} from '../src/history.ts';
import {photo} from './model-fixture.ts';
const p=()=>{const project=createProject(photo(8,6));project.title='Original retained study';return project;};
test('rectangle labels only source cell centres in either drag direction and preserves full project',()=>{const before=p(),next=assignRegion(before,0,'rectangle',[{x:1,y:1},{x:5,y:4}]);const labels=decodeMask(next.depth);for(let y=0;y<6;y++)for(let x=0;x<8;x++)assert.equal(labels[y*8+x],x>=1&&x<5&&y>=1&&y<4?0:1);assert.deepEqual(next,{...before,depth:next.depth});assert.deepEqual(assignRegion(before,0,'rectangle',[{x:5,y:4},{x:1,y:1}]),next);assert.ok(decodeMask(before.depth).every(v=>v===1));});
test('polygon uses even-odd cell-centre containment for concave and self-crossing boundaries',()=>{const polygons=[[{x:1,y:1},{x:7,y:1},{x:7,y:5},{x:4,y:5},{x:4,y:3},{x:1,y:3}],[{x:0,y:0},{x:8,y:6},{x:0,y:6},{x:8,y:0}]];for(const points of polygons){const before=p(),labels=decodeMask(assignRegion(before,2,'polygon',points).depth);for(let y=0;y<6;y++)for(let x=0;x<8;x++){let inside=false;for(let i=0,j=points.length-1;i<points.length;j=i++){const a=points[i],b=points[j];if((a.y>y+.5)!==(b.y>y+.5)&&(x+.5)<(b.x-a.x)*(y+.5-a.y)/(b.y-a.y)+a.x)inside=!inside;}assert.equal(labels[y*8+x],inside?2:1);}assert.deepEqual(assignRegion(before,2,'polygon',[...points].reverse()),assignRegion(before,2,'polygon',points));}});
test('no-area assignment keeps history redo; complete changed mask is one undo step',()=>{const history=new History(p()),original=history.current,next=assignRegion(original,0,'rectangle',[{x:0,y:0},{x:8,y:6}]);assert.equal(history.commit(next),true);assert.deepEqual(history.undo(),original);assert.equal(history.commit(assignRegion(original,0,'rectangle',[{x:2,y:2},{x:2,y:4}])),false);assert.equal(history.canRedo,true);assert.deepEqual(history.redo(),next);});
test('malformed bounded geometry refuses without invoking getters or changing source',()=>{const before=p();for(const points of [[{x:NaN,y:1},{x:4,y:4}],[{x:-1,y:1},{x:4,y:4}],[{x:9,y:1},{x:4,y:4}]])assert.throws(()=>assignRegion(before,0,'rectangle',points));assert.throws(()=>assignRegion(before,0,'polygon',[{x:0,y:0},{x:1,y:1}]));assert.throws(()=>assignRegion(before,0,'polygon',Array.from({length:2049},()=>({x:0,y:0}))));assert.throws(()=>assignRegion(before,0,'polygon',Array.from({length:2048},(_,i)=>({x:i%2?8:0,y:0}))));let count=0;const point={get x(){count++;return 0},y:0};assert.throws(()=>assignRegion(before,0,'rectangle',[point,{x:4,y:4}]));assert.equal(count,0);assert.ok(decodeMask(before.depth).every(v=>v===1));});

test('maximum original dimensions and 2048-point polygon keep exact complete graph',()=>{const before=createProject(photo(1280,1280));const full=assignRegion(before,0,'rectangle',[{x:0,y:0},{x:1280,y:1280}]);assert.equal(decodeMask(full.depth).length,1638400);assert.ok(decodeMask(full.depth).every(v=>v===0));assert.deepEqual(full,{...before,depth:full.depth});const points=Array.from({length:2048},(_,i)=>({x:640+100*Math.cos(i*Math.PI/1024),y:640+100*Math.sin(i*Math.PI/1024)}));const filled=decodeMask(assignRegion(before,2,'polygon',points).depth);assert.equal(filled[640*1280+640],2);assert.equal(filled[0],1);assert.ok(decodeMask(before.depth).every(v=>v===1));});

test('fractional polygon boundary is invariant when reversed',()=>{const before=createProject(photo(32,24)),points=[{x:16.3,y:22.9},{x:8.2,y:.5},{x:6.7,y:8.1}];assert.deepEqual(assignRegion(before,2,'polygon',points),assignRegion(before,2,'polygon',[...points].reverse()));});
