import {test as base,expect,type Page,type APIRequestContext} from '@playwright/test';
import {createHash} from 'node:crypto';
import {readFile,writeFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';

// Original media/text/observation tolerances frozen before sequential-timing producer reads.
export interface NativeCue{start:number;end:number;text:string}
export interface NativeProject{schemaVersion:1;id:string;revision:number;title:string;duration:number;cues:NativeCue[]}
interface Job{id:string;projectId:string;status:string}
export const INITIAL_CUES:NativeCue[]=[{start:1/3,end:1.125,text:'  First café 🌓\nsecond line  '},{start:2.25,end:3.5,text:'Final <literal> & line'}];
export const CLOCK_TOLERANCE=.025;
export const timingSha=(bytes:Uint8Array)=>createHash('sha256').update(bytes).digest('hex');
export function timingWav(){const frames=6*44100,bytes=Buffer.alloc(44+frames*4);bytes.write('RIFF');bytes.writeUInt32LE(bytes.length-8,4);bytes.write('WAVEfmt ',8);bytes.writeUInt32LE(16,16);bytes.writeUInt16LE(1,20);bytes.writeUInt16LE(2,22);bytes.writeUInt32LE(44100,24);bytes.writeUInt32LE(176400,28);bytes.writeUInt16LE(4,32);bytes.writeUInt16LE(16,34);bytes.write('data',36);bytes.writeUInt32LE(frames*4,40);for(let n=0;n<frames;n++){bytes.writeInt16LE(Math.round(3500*Math.sin(2*Math.PI*277*n/44100)),44+n*4);bytes.writeInt16LE(Math.round(2800*Math.sin(2*Math.PI*415*n/44100)),46+n*4);}return bytes;}
export async function fromServer(request:APIRequestContext,id:string){const response=await request.get(`/api/projects/${id}`);expect(response.status()).toBe(200);return await response.json() as NativeProject;}
export const test=base.extend<{timingClips:{create(cues?:NativeCue[]):Promise<NativeProject>}}>({timingClips:async({request},use)=>{const session=await(await request.get('/api/session')).json() as{token:string};const ids:string[]=[],jobs:string[]=[];
 try{await use({create:async(cues=INITIAL_CUES)=>{const result=await request.post('/api/projects',{headers:{'Content-Type':'application/octet-stream','X-Audio-Name':'original-sequential115.wav','X-Karaoke-Token':session.token},data:timingWav()});expect(result.status()).toBe(202);const job=(await result.json() as{job:Job}).job;ids.push(job.projectId);jobs.push(job.id);await expect.poll(async()=>((await(await request.get(`/api/jobs/${job.id}`)).json())as{job:Job}).job.status,{timeout:10000}).toBe('complete');const current=await fromServer(request,job.projectId),saved=await request.put(`/api/projects/${job.projectId}`,{headers:{'X-Karaoke-Token':session.token},data:{revision:current.revision,title:'Original supplied lyrics115',cues}});expect(saved.status()).toBe(200);return await saved.json() as NativeProject;}});}finally{const current=await(await request.get('/api/session')).json()as{activeJob:Job|null};if(current.activeJob&&ids.includes(current.activeJob.projectId)){jobs.push(current.activeJob.id);await request.post(`/api/jobs/${current.activeJob.id}/cancel`,{headers:{'X-Karaoke-Token':session.token},data:{}});}for(const id of jobs)await expect.poll(async()=>{const response=await request.get(`/api/jobs/${id}`);return response.status()===404||((await response.json())as{job:Job}).job.status!=='running';},{timeout:10000}).toBe(true);for(const id of ids)expect([200,404]).toContain((await request.delete(`/api/projects/${id}`,{headers:{'X-Karaoke-Token':session.token},data:{}})).status());}
}});
export interface ClockObservation{action:string;kind:string;time:number;paused:boolean;ended:boolean;repeat:boolean}
type TimingWindow=Window&{timing115Observations:ClockObservation[]};
export async function observeClock(page:Page){await page.addInitScript(()=>{const target=window as unknown as TimingWindow;target.timing115Observations=[];for(const kind of ['click','keydown'])document.addEventListener(kind,event=>{const node=event.target as HTMLElement,audio=document.querySelector<HTMLAudioElement>('#audio');if(!audio||!['timing-mark','timing-end-final'].includes(node.id))return;const keyboard=event as KeyboardEvent;if(kind==='keydown'&&!['Enter',' '].includes(keyboard.key))return;target.timing115Observations.push({action:node.textContent??'',kind,time:audio.currentTime,paused:audio.paused,ended:audio.ended,repeat:kind==='keydown'&&keyboard.repeat});},true);});}
export async function openTiming(page:Page,project:NativeProject){await page.goto(`/?project=${project.id}`);await expect(page.locator('#title')).toHaveValue(project.title);await expect.poll(()=>page.locator('#audio').evaluate(node=>{const a=node as HTMLAudioElement;return a.readyState>=2&&!a.seeking&&!a.error&&a.duration===6;})).toBe(true);await expect(page.locator('#timing-begin')).toBeEnabled();}
export async function media(page:Page){return page.locator('#audio').evaluate(node=>{const a=node as HTMLAudioElement;return{time:a.currentTime,paused:a.paused,ended:a.ended,rate:a.playbackRate,duration:a.duration};});}
export async function nativeToggle(page:Page,paused:boolean){const audio=page.locator('#audio'),box=await audio.boundingBox();if(!box)throw Error('Visible native player required');await audio.click({position:{x:24,y:box.height/2}});await expect.poll(async()=>(await media(page)).paused).toBe(paused);}
export async function waitPosition(page:Page,time:number){await expect.poll(async()=>(await media(page)).time,{intervals:[20,20,20],timeout:7000}).toBeGreaterThanOrEqual(time);}
export async function mark(page:Page,delay=.35){const before=await media(page);await waitPosition(page,before.time+delay);await expect(page.locator('#timing-mark')).toBeEnabled();await page.locator('#timing-mark').click();}
export async function captureTwo(page:Page){await page.locator('#timing-begin').click();await nativeToggle(page,false);await mark(page,.2);await mark(page,.45);await mark(page,.35);await mark(page,.5);await expect(page.locator('#timing-review')).toBeVisible();await expect(page.locator('#timing-apply')).toBeEnabled();expect((await media(page)).paused).toBe(true);}
export async function observed(page:Page){return page.evaluate(()=>(window as unknown as TimingWindow).timing115Observations);}
export async function editorCues(page:Page):Promise<NativeCue[]>{return page.locator('#cue-list [data-cue]').evaluateAll(rows=>rows.map(row=>({text:row.querySelector<HTMLTextAreaElement>('.cue-text textarea')!.value,start:Number(row.querySelector<HTMLInputElement>('[data-boundary=start]')!.value),end:Number(row.querySelector<HTMLInputElement>('[data-boundary=end]')!.value)})));}
export function validateClock(cues:NativeCue[],observations:ClockObservation[]){const actions=observations.filter(x=>x.kind==='click');expect(actions).toHaveLength(cues.length*2);for(const [i,cue]of cues.entries()){expect(cue.text).toBe(INITIAL_CUES[i].text);expect(Math.abs(cue.start-actions[2*i].time)).toBeLessThanOrEqual(CLOCK_TOLERANCE);expect(Math.abs(cue.end-actions[2*i+1].time)).toBeLessThanOrEqual(CLOCK_TOLERANCE);expect(actions[2*i].paused).toBe(false);expect(actions[2*i+1].paused).toBe(false);}expect(cues[1].start-cues[0].end).toBeGreaterThan(.2);}
export function expectedSrt(cues:NativeCue[]){const stamp=(seconds:number)=>{const ms=Math.round(seconds*1000);return`${String(Math.floor(ms/3600000)).padStart(2,'0')}:${String(Math.floor(ms/60000)%60).padStart(2,'0')}:${String(Math.floor(ms/1000)%60).padStart(2,'0')},${String(ms%1000).padStart(3,'0')}`;};return cues.map((cue,i)=>`${i+1}\n${stamp(cue.start)} --> ${stamp(cue.end)}\n${cue.text.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}\n`).join('\n');}
export async function downloaded(page:Page,name:string,path:string){const pending=page.waitForEvent('download');await page.getByRole('button',{name,exact:true}).click();const download=await pending;await download.saveAs(path);return readFile(path);}
export async function checkTimingVideo(path:string,cues:NativeCue[]){const metadata=JSON.parse(execFileSync('ffprobe',['-v','error','-count_frames','-show_streams','-of','json',path],{encoding:'utf8',timeout:15000}));expect(metadata.streams.find((s:{codec_type:string})=>s.codec_type==='video')).toMatchObject({codec_name:'h264',width:1280,height:720,r_frame_rate:'24/1',nb_read_frames:'144'});expect(metadata.streams.find((s:{codec_type:string})=>s.codec_type==='audio').codec_name).toBe('aac');const frames=[...new Set([0,143,...cues.flatMap(c=>[Math.ceil(c.start*24)-1,Math.ceil(c.start*24),Math.ceil(c.end*24)-1,Math.ceil(c.end*24)])])].filter(n=>n>=0&&n<144).sort((a,b)=>a-b);const selection=frames.map(n=>`eq(n\\,${n})`).join('+'),pixels=execFileSync('ffmpeg',['-v','error','-threads','1','-i',path,'-vf',`select=${selection}`,'-fps_mode','passthrough','-f','rawvideo','-pix_fmt','rgb24','-threads','1','pipe:1'],{timeout:15000,maxBuffer:40*1024**2}),size=1280*720*3;expect(pixels.length).toBe(frames.length*size);const samples=frames.map((frame,index)=>{const cue=cues.find(c=>c.start<=frame/24&&frame/24<c.end);let warm=0;for(let y=180;y<470;y++)for(let x=100;x<1180;x++){const offset=index*size+(y*1280+x)*3,r=pixels[offset],g=pixels[offset+1],b=pixels[offset+2];if(r>160&&g>110&&b<175&&r>g+15&&g>b+20)warm++;}if(cue)expect(warm,`active frame ${frame}`).toBeGreaterThan(40);else expect(warm,`gap frame ${frame}`).toBeLessThan(20);return{frame,time:frame/24,active:!!cue,warmPixels:warm};});return{bytes:(await readFile(path)).length,sha256:timingSha(await readFile(path)),frames:144,samples};}
export async function saveReceipt(path:string,value:unknown){await writeFile(path,JSON.stringify(value,null,2));}
