import {expect} from '@playwright/test';
import {test,INITIAL_CUES,CLOCK_TOLERANCE,timingWav,timingSha,observeClock,openTiming,media,nativeToggle,waitPosition,mark,captureTwo,observed,editorCues,validateClock,fromServer,expectedSrt,downloaded,checkTimingVideo,saveReceipt,type NativeProject} from './sequential-timing-fixtures.ts';

test('actual playback marks gaps and pause-resume, then one Apply Undo Redo manual Save SRT and MP4 retain exact observed boundaries',async({page,request,timingClips},info)=>{
 test.setTimeout(60000);await observeClock(page);const project=await timingClips.create();await openTiming(page,project);const audioBefore=await Promise.all(['original','vocals','backing'].map(async name=>timingSha(await(await request.get(`/api/projects/${project.id}/audio/${name}`)).body())));await page.locator('#timing-begin').click();await expect(page.locator('#timing-mark')).toBeDisabled();await nativeToggle(page,false);await mark(page,.2);
 await nativeToggle(page,true);const paused=await media(page);await expect(page.locator('#timing-mark')).toBeDisabled();await expect(page.locator('#timing-status')).toContainText(/resume|paused/i);expect(await editorCues(page)).toEqual(INITIAL_CUES);await nativeToggle(page,false);await waitPosition(page,paused.time+.45);await page.locator('#timing-mark').click();await mark(page,.35);await mark(page,.5);
 await expect(page.locator('#timing-review')).toBeVisible();await expect(page.locator('#timing-apply')).toBeEnabled();expect((await media(page)).paused).toBe(true);for(const cue of INITIAL_CUES)await expect(page.locator('#timing-review-list')).toContainText(cue.text);await expect(page.locator('#save')).toBeDisabled();await expect(page.getByRole('button',{name:'Export karaoke MP4',exact:true})).toBeDisabled();expect(await editorCues(page)).toEqual(INITIAL_CUES);expect(await fromServer(request,project.id)).toEqual(project);
 const receipts=await observed(page);await page.locator('#timing-apply').click();const captured=await editorCues(page);validateClock(captured,receipts);expect(await fromServer(request,project.id)).toEqual(project);await page.locator('#undo-lyrics').click();expect(await editorCues(page)).toEqual(INITIAL_CUES);await expect(page.locator('#undo-lyrics')).toBeDisabled();await page.locator('#redo-lyrics').click();expect(await editorCues(page)).toEqual(captured);
 await page.locator('#save').click();await expect(page.locator('#save-state')).toHaveText('Saved in your local studio.');const saved=await fromServer(request,project.id);expect(saved.cues).toEqual(captured);expect(saved.revision).toBe(project.revision+1);expect(saved.title).toBe(project.title);const srt=await downloaded(page,'Export timed lyrics',info.outputPath('actual-sequential.srt'));expect(srt.toString()).toBe(expectedSrt(captured));const mp4Path=info.outputPath('actual-sequential.mp4');await downloaded(page,'Export karaoke MP4',mp4Path);const video=await checkTimingVideo(mp4Path,captured);
 await page.reload();await expect(page.locator('#title')).toHaveValue(project.title);expect(await editorCues(page)).toEqual(captured);await expect(page.locator('#undo-lyrics')).toBeDisabled();const audioAfter=await Promise.all(['original','vocals','backing'].map(async name=>timingSha(await(await request.get(`/api/projects/${project.id}/audio/${name}`)).body())));expect(audioAfter).toEqual(audioBefore);await saveReceipt(info.outputPath('actual-sequential-receipt.json'),{fixtureWavSha256:timingSha(timingWav()),clockObservationTolerance:CLOCK_TOLERANCE,observations:receipts,cues:captured,savedRevision:saved.revision,audioBefore,audioAfter,srtSha256:timingSha(srt),video,physicalSynchronizationMeasured:false});
});

test('invalid prior numeric spelling title and unapplied multiline paste survive Apply and exact Undo',async({page,timingClips})=>{
 await observeClock(page);const project=await timingClips.create();await openTiming(page,project);await page.locator('#title').fill('');await page.locator('#lyric-draft').fill('Unapplied pasted words\n  stay untouched');await page.getByLabel('Start line 1',{exact:true}).fill('');await page.getByLabel('End line 1',{exact:true}).fill('1.1250');await captureTwo(page);await page.locator('#timing-apply').click();const captured=await editorCues(page);validateClock(captured,await observed(page));await expect(page.locator('#title')).toHaveValue('');await expect(page.locator('#lyric-draft')).toHaveValue('Unapplied pasted words\n  stay untouched');await expect(page.locator('#save')).toBeDisabled();await page.locator('#undo-lyrics').click();await expect(page.getByLabel('Start line 1',{exact:true})).toHaveValue('');await expect(page.getByLabel('End line 1',{exact:true})).toHaveValue('1.1250');await expect(page.locator('#title')).toHaveValue('');await expect(page.locator('#lyric-draft')).toHaveValue('Unapplied pasted words\n  stay untouched');await page.locator('#redo-lyrics').click();expect(await editorCues(page)).toEqual(captured);
});

test('390px held Enter and Space mark once across phase changes and blur until real key release',async({page,timingClips},info)=>{
 await page.setViewportSize({width:390,height:844});const project=await timingClips.create();await openTiming(page,project);await page.locator('#timing-begin').click();await nativeToggle(page,false);await waitPosition(page,.2);const button=page.locator('#timing-mark');await button.focus();await page.keyboard.down('Enter');await expect(button).toHaveText('Mark line end');await page.keyboard.down('Enter');await page.getByLabel('Lyric line 1',{exact:true}).focus();await button.focus();await page.keyboard.down('Enter');await expect(button).toHaveText('Mark line end');await page.keyboard.up('Enter');await expect(button).toHaveText('Mark line end');await waitPosition(page,(await media(page)).time+.25);await page.keyboard.press('Enter');await expect(button).toHaveText('Mark line start');await waitPosition(page,(await media(page)).time+.25);await page.keyboard.down('Space');await expect(button).toHaveText('Mark line end');await page.keyboard.down('Space');await expect(button).toHaveText('Mark line end');await page.keyboard.up('Space');await expect(button).toHaveText('Mark line end');await waitPosition(page,(await media(page)).time+.3);await page.keyboard.press('Space');await expect(page.locator('#timing-review')).toBeVisible();expect(await editorCues(page)).toEqual(INITIAL_CUES);await page.locator('#timing-review').scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('timing-review-390.png'),fullPage:true});await page.locator('#timing-apply').focus();await page.keyboard.press('Enter');expect((await editorCues(page)).every(c=>c.end>c.start)).toBe(true);
});

test('Cancel and paused mark no-ops preserve raw cue node caret server state and existing redo',async({page,request,timingClips})=>{
 const project=await timingClips.create();await openTiming(page,project);await page.getByLabel('Lyric line 1',{exact:true}).fill('Temporary');await page.locator('#undo-lyrics').click();await expect(page.locator('#redo-lyrics')).toBeEnabled();await page.locator('#timing-begin').click();await expect(page.locator('#timing-mark')).toBeDisabled();await page.locator('#timing-mark').evaluate(node=>(node as HTMLButtonElement).click());const lyric=page.getByLabel('Lyric line 1',{exact:true});await lyric.focus();await lyric.evaluate(node=>{const field=node as HTMLTextAreaElement;field.dataset.timingIdentity='same';field.setSelectionRange(2,7);});await page.locator('#timing-cancel').evaluate(node=>(node as HTMLButtonElement).click());await expect(lyric).toBeFocused();await expect(lyric).toHaveAttribute('data-timing-identity','same');expect(await lyric.evaluate(node=>[(node as HTMLTextAreaElement).selectionStart,(node as HTMLTextAreaElement).selectionEnd])).toEqual([2,7]);expect(await editorCues(page)).toEqual(INITIAL_CUES);await expect(page.locator('#redo-lyrics')).toBeEnabled();expect(await fromServer(request,project.id)).toEqual(project);
});

for(const mutation of ['seek','rate','loop']as const)test(`controlled native ${mutation} before queued event retires timing synchronously without publishing`,async({page,request,timingClips})=>{
 const project=await timingClips.create();await openTiming(page,project);await page.locator('#timing-begin').click();await nativeToggle(page,false);await mark(page,.2);await page.evaluate(kind=>{const audio=document.querySelector<HTMLAudioElement>('#audio')!;if(kind==='seek')audio.currentTime=audio.currentTime+.4;else if(kind==='rate')audio.playbackRate=1.5;else audio.loop=true;(document.querySelector('#timing-mark')as HTMLButtonElement).click();},mutation);await expect(page.locator('#timing-apply')).toBeDisabled();await expect(page.locator('#timing-mark')).toBeDisabled();await expect(page.locator('#timing-status')).toContainText(/cancel|retir|discard|not applied|again|changed/i);expect(await editorCues(page)).toEqual(INITIAL_CUES);expect(await fromServer(request,project.id)).toEqual(project);
});

test('natural ended leaves the final open line pending until explicit exact clip-end action',async({page,request,timingClips})=>{
 const cue={start:1/3,end:1.125,text:'Final exact endpoint\nkeeps supplied multiline Ω'},project=await timingClips.create([cue]);await openTiming(page,project);await page.locator('#timing-begin').click();await nativeToggle(page,false);await mark(page,.2);await expect.poll(async()=>(await media(page)).ended,{intervals:[50,100,100],timeout:8000}).toBe(true);await expect(page.locator('#timing-apply')).toBeDisabled();expect(await editorCues(page)).toEqual([cue]);await expect(page.locator('#timing-end-final')).toBeVisible();await page.locator('#timing-end-final').click();await expect(page.locator('#timing-review')).toBeVisible();await page.locator('#timing-apply').click();const captured=await editorCues(page);expect(captured).toHaveLength(1);expect(captured[0].end).toBe(6);expect(captured[0].text).toBe(cue.text);expect(captured[0].start).toBeGreaterThan(0);expect(await fromServer(request,project.id)).toEqual(project);await page.locator('#undo-lyrics').click();expect(await editorCues(page)).toEqual([cue]);
});

test('natural end with unmarked remaining lines refuses partial review and never infers an endpoint',async({page,request,timingClips})=>{
 const project=await timingClips.create();await openTiming(page,project);await page.locator('#timing-begin').click();await nativeToggle(page,false);await mark(page,.2);await expect.poll(async()=>(await media(page)).ended,{intervals:[50,100,100],timeout:8000}).toBe(true);await expect(page.locator('#timing-end-final')).toBeHidden();await expect(page.locator('#timing-apply')).toBeDisabled();await expect(page.locator('#timing-status')).toContainText(/remain|cancel|incomplete/i);expect(await editorCues(page)).toEqual(INITIAL_CUES);await page.locator('#timing-cancel').click();expect(await fromServer(request,project.id)).toEqual(project);
});

test('changed-back input retires a complete review while preserving the actual focused editor node',async({page,request,timingClips})=>{
 const project=await timingClips.create();await openTiming(page,project);await captureTwo(page);const title=page.locator('#title');await title.fill('New intent');await title.fill(project.title);await title.evaluate(node=>{const field=node as HTMLInputElement;field.dataset.timingIdentity='same';field.setSelectionRange(3,3);});await expect(page.locator('#timing-apply')).toBeDisabled();await expect(title).toBeFocused();await expect(title).toHaveAttribute('data-timing-identity','same');expect(await title.evaluate(node=>(node as HTMLInputElement).selectionStart)).toBe(3);expect(await editorCues(page)).toEqual(INITIAL_CUES);expect(await fromServer(request,project.id)).toEqual(project);
});

test('controlled persisted page departure retires marks and blocked held keys cannot activate a fresh session',async({page,timingClips})=>{
 const project=await timingClips.create();await openTiming(page,project);await page.locator('#timing-begin').click();await nativeToggle(page,false);await waitPosition(page,.2);await expect(page.locator('#timing-mark')).toBeEnabled();await page.locator('#timing-mark').focus();await expect(page.locator('#timing-mark')).toBeFocused();await page.keyboard.down('Enter');await expect(page.locator('#timing-mark')).toHaveText('Mark line end');await page.evaluate(()=>{dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true}));dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true}));});await expect(page.locator('#timing-apply')).toBeDisabled();await page.locator('#timing-begin').click();if((await media(page)).paused)await nativeToggle(page,false);await expect(page.locator('#timing-mark')).toBeEnabled();await page.locator('#timing-mark').focus();await expect(page.locator('#timing-mark')).toBeFocused();await page.keyboard.down('Enter');await expect(page.locator('#timing-mark')).toHaveText('Mark line start');await page.keyboard.up('Enter');await page.keyboard.press('Enter');await expect(page.locator('#timing-mark')).toHaveText('Mark line end');await page.locator('#timing-cancel').click();expect(await editorCues(page)).toEqual(INITIAL_CUES);
});

test('late real Backing audio response cannot revive a retired session after selecting Original',async({page,request,timingClips})=>{
 const project=await timingClips.create();await openTiming(page,project);await page.locator('#timing-begin').click();await nativeToggle(page,false);await mark(page,.2);let pending=false;let release:()=>void=()=>{};const gate=new Promise<void>(resolve=>release=resolve);await page.route(`**/api/projects/${project.id}/audio/backing`,async route=>{const response=await route.fetch();pending=true;await gate;await route.fulfill({response});});try{await page.getByRole('button',{name:'Backing',exact:true}).click();await expect.poll(()=>pending).toBe(true);await expect(page.locator('#timing-apply')).toBeDisabled();await page.getByRole('button',{name:'Original',exact:true}).click();release();await expect.poll(()=>page.locator('#audio').evaluate(node=>(node as HTMLAudioElement).currentSrc.endsWith('/audio/original'))).toBe(true);await expect(page.locator('#timing-mark')).toBeDisabled();expect(await editorCues(page)).toEqual(INITIAL_CUES);expect(await fromServer(request,project.id)).toEqual(project);}finally{release();await page.unrouteAll({behavior:'wait'});}
});

test('a foreign saved revision makes explicit Save refuse without replaying or losing captured cues',async({page,request,timingClips})=>{
 const project=await timingClips.create();await openTiming(page,project);await captureTwo(page);await page.locator('#timing-apply').click();const captured=await editorCues(page),session=await(await request.get('/api/session')).json()as{token:string};const response=await request.put(`/api/projects/${project.id}`,{headers:{'X-Karaoke-Token':session.token},data:{revision:project.revision,title:'Foreign saved winner115',cues:INITIAL_CUES}});expect(response.status()).toBe(200);const winner=await response.json()as NativeProject;let puts=0;page.on('request',r=>{if(r.method()==='PUT'&&r.url().endsWith(`/api/projects/${project.id}`))puts++;});await page.locator('#save').click();await expect(page.locator('#message')).toContainText(/changed|revision|reload|conflict/i);expect(puts).toBe(1);expect(await fromServer(request,project.id)).toEqual(winner);expect(await editorCues(page)).toEqual(captured);await page.locator('#undo-lyrics').click();expect(await editorCues(page)).toEqual(INITIAL_CUES);expect(await fromServer(request,project.id)).toEqual(winner);
});


test('controlled visibility loss retires review without rebuilding focused multiline cue text',async({page,request,timingClips})=>{
 const project=await timingClips.create();await openTiming(page,project);await captureTwo(page);const lyric=page.getByLabel('Lyric line 1',{exact:true});await lyric.focus();await lyric.evaluate(node=>{const field=node as HTMLTextAreaElement;field.dataset.timingIdentity='hidden-same';field.setSelectionRange(2,5);});await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});Object.defineProperty(document,'visibilityState',{configurable:true,value:'hidden'});document.dispatchEvent(new Event('visibilitychange'));Reflect.deleteProperty(document,'hidden');Reflect.deleteProperty(document,'visibilityState');document.dispatchEvent(new Event('visibilitychange'));});await expect(page.locator('#timing-apply')).toBeDisabled();await expect(lyric).toBeFocused();await expect(lyric).toHaveAttribute('data-timing-identity','hidden-same');expect(await lyric.evaluate(node=>[(node as HTMLTextAreaElement).selectionStart,(node as HTMLTextAreaElement).selectionEnd])).toEqual([2,5]);expect(await editorCues(page)).toEqual(INITIAL_CUES);expect(await fromServer(request,project.id)).toEqual(project);
});
