"""Independent native archive fixture: real service, literal audits and decoding."""
import argparse
import hashlib
import json
from pathlib import Path
import signal
import sqlite3
import subprocess
import sys
import zipfile

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from duet.server import create_server  # noqa: E402


def fingerprint(value):
    return hashlib.sha256(json.dumps(value, sort_keys=True, separators=(',', ':')).encode()).hexdigest()


def redact(room):
    result = dict(room)
    result['capabilityFingerprints'] = {
        role: fingerprint(value) for role, value in result.pop('capabilities').items()
    }
    result['inviteFingerprint'] = fingerprint(result.pop('inviteHash'))
    return result


def main():
    parser = argparse.ArgumentParser()
    commands = parser.add_subparsers(dest='command', required=True)
    for name in ('serve', 'records'):
        commands.add_parser(name).add_argument('--data-dir', type=Path, required=True)
    commands.add_parser('archive').add_argument('--archive', type=Path, required=True)
    commands.add_parser('decode').add_argument('--audio', type=Path, required=True)
    args = parser.parse_args()
    if args.command == 'serve':
        server = create_server(args.data_dir, port=0)
        def terminate(_signal, _frame):
            raise KeyboardInterrupt
        previous = signal.signal(signal.SIGTERM, terminate)
        try:
            print(f'Duet archive fixture: http://127.0.0.1:{server.server_port}', flush=True)
            server.serve_forever(poll_interval=.05)
        except KeyboardInterrupt:
            pass
        finally:
            server.server_close()
            signal.signal(signal.SIGTERM, previous)
        return
    if args.command == 'records':
        connection = sqlite3.connect((args.data_dir / 'rooms.sqlite3').resolve().as_uri()
                                     + '?mode=ro&immutable=1', uri=True)
        try:
            rows = connection.execute('SELECT document FROM rooms ORDER BY id').fetchall()
            result = {'rooms': [redact(json.loads(row[0])) for row in rows]}
        finally:
            connection.close()
    elif args.command == 'archive':
        # This independent reader inspects only the small artifact generated by
        # these original fixtures. Hostile-container/resource oracles are separate.
        with zipfile.ZipFile(args.archive) as archive:
            result = {'rooms': [redact(room) for room in json.loads(archive.read('rooms.json'))['rooms']],
                      'manifest': json.loads(archive.read('manifest.json')),
                      'files': archive.namelist()}
    else:
        probe = subprocess.run(['ffprobe', '-v', 'error', '-show_entries',
                                'stream=codec_name,sample_rate,channels', '-of', 'json',
                                str(args.audio)], capture_output=True, timeout=20, check=True)
        decoded = subprocess.run(['ffmpeg', '-nostdin', '-v', 'error', '-xerror',
                                  '-protocol_whitelist', 'file', '-f', 'ogg', '-i', str(args.audio),
                                  '-map', '0:a:0', '-ar', '48000', '-ac', '2', '-c:a', 'pcm_s16le',
                                  '-f', 's16le', 'pipe:1'], capture_output=True, timeout=20, check=True)
        pcm = decoded.stdout
        if len(pcm) > 300 * 48000 * 4 or len(pcm) % 4:
            raise ValueError('Invalid fixture PCM size')
        peak = max((abs(int.from_bytes(pcm[i:i + 2], 'little', signed=True))
                    for i in range(0, len(pcm), 2)), default=0)
        result = {'streams': json.loads(probe.stdout)['streams'], 'frames': len(pcm) // 4,
                  'pcmSha256': hashlib.sha256(pcm).hexdigest(), 'peak': peak}
    print(json.dumps(result, ensure_ascii=False, allow_nan=False))


if __name__ == '__main__':
    try:
        main()
    except Exception:
        print('The independent archive fixture could not complete.', file=sys.stderr)
        raise SystemExit(2) from None
