"""Real media and subprocess tests; synthetic fixtures are generated by this test."""
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import threading
import time
import unittest
from unittest.mock import patch

from duet import media


def fixture(path, duration=2, codec='pcm_s16le', container='wav', rate=16000):
    subprocess.run(['ffmpeg', '-nostdin', '-hide_banner', '-loglevel', 'error',
                    '-f', 'lavfi', '-i', f'sine=frequency=440:sample_rate={rate}:duration={duration}',
                    '-threads', '1', '-c:a', codec, '-f', container, str(path)], check=True,
                   stdin=subprocess.DEVNULL, capture_output=True, timeout=15)


class MediaTests(unittest.TestCase):
    def setUp(self):
        self.directory = tempfile.TemporaryDirectory()
        self.root = Path(self.directory.name)
        self.cancel = threading.Event()
        self.source, self.output = self.root / 'input.audio', self.root / 'audio.ogg'

    def tearDown(self):
        self.directory.cleanup()

    def normalize_audio(self, *args):
        """Only generated fixtures: disclose private diagnostics on test failure."""
        try:
            return media.normalize_audio(*args)
        except media._SubprocessError as error:
            diagnostic = error.stderr.decode('utf-8', errors='replace')
            error.add_note(f'Synthetic fixture subprocess exit {error.returncode}: {diagnostic}')
            raise

    def test_real_wav_normalizes_to_canonical_opus_and_preserves_source(self):
        fixture(self.source, 2.123)
        original = self.source.read_bytes()
        stages = []
        duration = self.normalize_audio(self.source, self.output, self.cancel, stages.append)
        result = subprocess.run(['ffprobe', '-v', 'error', '-show_entries',
                                 'stream=codec_name,sample_rate,channels:format=format_name,duration',
                                 '-of', 'json', str(self.output)], check=True, capture_output=True)
        probe = json.loads(result.stdout)
        self.assertEqual(probe['format']['format_name'], 'ogg')
        self.assertEqual(probe['streams'][0]['codec_name'], 'opus')
        self.assertEqual(probe['streams'][0]['sample_rate'], '48000')
        self.assertEqual(probe['streams'][0]['channels'], 2)
        self.assertAlmostEqual(duration, 2.123, delta=1 / 48000)
        self.assertGreater(float(probe['format']['duration']), duration)
        self.assertEqual(self.source.read_bytes(), original)
        self.assertLess(self.output.stat().st_size, 8 * 1024 * 1024)
        self.assertGreaterEqual(len(stages), 3)
        self.assertEqual(sorted(p.name for p in self.root.iterdir()), ['audio.ogg', 'input.audio'])

    def test_real_mp3_flac_and_ogg_inputs_accept_extensionless_paths(self):
        for codec, container in [('libmp3lame', 'mp3'), ('flac', 'flac'), ('libvorbis', 'ogg')]:
            with self.subTest(container=container):
                self.source.unlink(missing_ok=True)
                fixture(self.source, 1.5, codec, container)
                duration = self.normalize_audio(self.source, self.output, self.cancel, lambda _: None)
                self.assertAlmostEqual(duration, 1.5, delta=0.001)

    def test_source_duration_bounds_and_existing_output_preserved(self):
        self.output.write_bytes(b'previous audio')
        for duration in [0.9, 300.01]:
            self.source.unlink(missing_ok=True)
            fixture(self.source, duration, 'flac', 'flac', 8000)
            with self.assertRaisesRegex(ValueError, '1.*300|duration'):
                self.normalize_audio(self.source, self.output, self.cancel, lambda _: None)
            self.assertEqual(self.output.read_bytes(), b'previous audio')
        self.assertEqual(sorted(p.name for p in self.root.iterdir()), ['audio.ogg', 'input.audio'])

    def test_five_minute_boundary_runs_real_complete_conversion(self):
        fixture(self.source, 300, 'flac', 'flac', 8000)
        started = time.monotonic()
        duration = self.normalize_audio(self.source, self.output, self.cancel, lambda _: None)
        self.assertEqual(duration, 300)
        self.assertLess(self.output.stat().st_size, 8 * 1024 * 1024)
        self.assertLess(time.monotonic() - started, 45)

    def test_invalid_magic_size_video_and_corrupt_audio_fail_without_publication(self):
        self.output.write_bytes(b'previous audio')
        for contents in [b'', b'#EXTM3U\nhttps://example.com/media.mp3', b'RIFF\0\0\0\0WAVEbroken', b'OggSbroken']:
            self.source.write_bytes(contents)
            with self.assertRaises((ValueError, RuntimeError)):
                self.normalize_audio(self.source, self.output, self.cancel, lambda _: None)
            self.assertEqual(self.output.read_bytes(), b'previous audio')
        with self.source.open('wb') as oversized:
            oversized.write(b'RIFF\0\0\0\0WAVE')
            oversized.truncate(25 * 1024 * 1024 + 1)
        with self.assertRaisesRegex(ValueError, '25 MiB'):
            self.normalize_audio(self.source, self.output, self.cancel, lambda _: None)
        self.source.unlink()
        subprocess.run(['ffmpeg', '-nostdin', '-v', 'error', '-f', 'lavfi', '-i', 'color=size=64x64:rate=1:duration=2',
                        '-f', 'lavfi', '-i', 'sine=frequency=440:duration=2', '-threads', '1', '-c:v', 'libtheora', '-c:a', 'libvorbis', '-f', 'ogg', str(self.source)], check=True, capture_output=True)
        with self.assertRaisesRegex(ValueError, 'audio.only|stream'):
            self.normalize_audio(self.source, self.output, self.cancel, lambda _: None)
        self.assertEqual(self.output.read_bytes(), b'previous audio')

    def test_cancel_before_work_and_before_publication_preserves_output(self):
        fixture(self.source)
        self.output.write_bytes(b'previous audio')
        self.cancel.set()
        with self.assertRaisesRegex(RuntimeError, 'cancel'):
            self.normalize_audio(self.source, self.output, self.cancel, lambda _: None)
        self.cancel.clear()
        def stage(message):
            if 'Checking normalized' in message:
                self.cancel.set()
        with self.assertRaisesRegex(RuntimeError, 'cancel'):
            self.normalize_audio(self.source, self.output, self.cancel, stage)
        self.assertEqual(self.output.read_bytes(), b'previous audio')
        self.assertEqual(sorted(p.name for p in self.root.iterdir()), ['audio.ogg', 'input.audio'])

    def test_file_paths_cannot_alias_or_use_symlinks(self):
        fixture(self.source)
        with self.assertRaises(ValueError):
            self.normalize_audio(self.source, self.source, self.cancel, lambda _: None)
        linked = self.root / 'linked.audio'
        linked.symlink_to(self.source)
        with self.assertRaises(ValueError):
            self.normalize_audio(linked, self.output, self.cancel, lambda _: None)

    def test_anchored_directory_remains_source_after_job_parent_replacement(self):
        jobs = self.root / '.jobs'
        job = jobs / 'job'
        job.mkdir(parents=True)
        fixture(job / 'input.audio', 2)
        original = (job / 'input.audio').read_bytes()
        outside = self.root / 'outside'
        other_job = outside / 'job'
        other_job.mkdir(parents=True)
        fixture(other_job / 'input.audio', 3)
        descriptor = os.open(job, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW)
        anchor = Path(f'/proc/{os.getpid()}/fd/{descriptor}')

        def replace_parent(message):
            if message == 'Checking audio format and duration':
                jobs.rename(self.root / 'held-jobs')
                jobs.symlink_to(outside, target_is_directory=True)

        try:
            duration = self.normalize_audio(anchor / 'input.audio', anchor / 'audio.ogg',
                                             self.cancel, replace_parent)
            self.assertEqual(duration, 2)
            self.assertTrue((anchor / 'audio.ogg').is_file())
            self.assertEqual((anchor / 'input.audio').read_bytes(), original)
            self.assertEqual([p.name for p in other_job.iterdir()], ['input.audio'])
        finally:
            os.close(descriptor)

    def test_subprocess_time_log_stdout_file_and_rss_limits_reap(self):
        cases = [
            ("import time; time.sleep(10)", {'timeout': .15}, 'timed out'),
            ("import sys; sys.stderr.write('x'*100000)", {'stderr_limit': 1000}, 'output limit'),
            ("import sys; sys.stdout.buffer.write(b'x'*100000)", {'stdout_limit': 1000}, 'output limit'),
            ("import time; x=bytearray(20*1024*1024); time.sleep(10)", {'rss_limit_kib': 1024}, 'memory limit'),
        ]
        for script, options, message in cases:
            with self.subTest(message=message):
                with self.assertRaisesRegex(RuntimeError, message):
                    media._run([sys.executable, '-c', script], self.cancel, **options)
        script = "from pathlib import Path; import time; Path(__import__('sys').argv[1]).write_bytes(b'x'*2000); time.sleep(10)"
        with self.assertRaisesRegex(RuntimeError, 'file.*limit'):
            media._run([sys.executable, '-c', script, str(self.output)], self.cancel, output=self.output, file_limit=1000)

    def test_child_has_hard_memory_file_and_core_limits_without_thread_unsafe_preexec(self):
        script = "import json,resource; print(json.dumps([resource.getrlimit(resource.RLIMIT_AS),resource.getrlimit(resource.RLIMIT_FSIZE),resource.getrlimit(resource.RLIMIT_CORE)]))"
        output, _ = media._run([sys.executable, '-c', script], self.cancel)
        limits = json.loads(output)
        self.assertEqual(limits[0], [512 * 1024 * 1024] * 2)
        self.assertEqual(limits[1], [8 * 1024 * 1024] * 2)
        self.assertEqual(limits[2], [0, 0])

    def test_child_environment_bounds_library_threads_and_allocator_arenas(self):
        keys = ['OPENBLAS_NUM_THREADS', 'OMP_NUM_THREADS', 'OMP_THREAD_LIMIT',
                'MKL_NUM_THREADS', 'BLIS_NUM_THREADS', 'VECLIB_MAXIMUM_THREADS',
                'NUMEXPR_NUM_THREADS', 'GOTO_NUM_THREADS', 'MALLOC_ARENA_MAX']
        inherited = dict.fromkeys(keys, '64')
        script = 'import json,os,sys; print(json.dumps({key:os.environ.get(key) for key in sys.argv[1:]}))'
        with patch.dict(os.environ, inherited):
            output, _ = media._run([sys.executable, '-c', script, *keys], self.cancel)
            self.assertEqual(json.loads(output), {key: '2' if key == 'MALLOC_ARENA_MAX' else '1' for key in keys})
            self.assertEqual({key: os.environ[key] for key in keys}, inherited)

    def test_child_failure_retains_bounded_private_diagnostics_without_public_details(self):
        script = "import sys; sys.stderr.write('original synthetic diagnostic'); sys.exit(9)"
        with self.assertRaises(RuntimeError) as failure:
            media._run([sys.executable, '-c', script], self.cancel)
        self.assertEqual(getattr(failure.exception, 'returncode', None), 9)
        self.assertEqual(getattr(failure.exception, 'stderr', None), b'original synthetic diagnostic')
        self.assertNotIn('synthetic diagnostic', str(failure.exception))
        self.assertNotIn('synthetic diagnostic', repr(failure.exception))

    def test_running_cancel_kills_process_group_and_waits_for_parent(self):
        marker = self.root / 'pid'
        script = "import os,subprocess,sys,time; from pathlib import Path; p=subprocess.Popen([sys.executable,'-c','import time; time.sleep(30)']); Path(sys.argv[1]).write_text(str(os.getpid())+' '+str(p.pid)); time.sleep(30)"
        timer = threading.Timer(.25, self.cancel.set)
        timer.start()
        try:
            with self.assertRaisesRegex(RuntimeError, 'cancel'):
                media._run([sys.executable, '-c', script, str(marker)], self.cancel)
        finally:
            timer.cancel()
        parent, child = map(int, marker.read_text().split())
        with self.assertRaises(ProcessLookupError):
            os.kill(parent, 0)
        status = Path(f'/proc/{child}/status')
        if status.exists():
            self.assertIn('State:\tZ', status.read_text())

    def test_failed_encoding_removes_temporary_file_and_preserves_output(self):
        fixture(self.source)
        self.output.write_bytes(b'previous audio')
        actual = media._run
        def fail_encode(command, cancel, **kwargs):
            if command[0] == 'ffmpeg' and 'libopus' in command:
                kwargs['output'].write_bytes(b'partial')
                raise RuntimeError('Encoder failed')
            return actual(command, cancel, **kwargs)
        with patch.object(media, '_run', side_effect=fail_encode):
            with self.assertRaisesRegex(RuntimeError, 'Encoder failed'):
                self.normalize_audio(self.source, self.output, self.cancel, lambda _: None)
        self.assertEqual(self.output.read_bytes(), b'previous audio')
        self.assertEqual(sorted(p.name for p in self.root.iterdir()), ['audio.ogg', 'input.audio'])


if __name__ == '__main__':
    unittest.main()
