import {test,expect,type Page,type Download} from '@playwright/test';
import {endpoints,applied,coreAt,type Film} from './tween-fixtures.ts';
import {readFile,writeFile} from 'node:fs/promises';
import {parseGIF,decompressFrames} from 'gifuct-js';
import {nativeCurrent} from '../native-saved-project.ts';
async function open(page:Page,film:Film=endpoints()){
  await page.goto('/');await expect(page.locator('#stage')).toHaveAttribute('aria-disabled','false');
  await page.locator('#project-file').setInputFiles({name:'original-endpoints.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(film))});
  await expect(page.locator('#project-title')).toHaveValue(film.title);await expect(page.locator('#save-status')).toHaveText('Saved in this browser');await page.locator('[data-layer-id=paired]').click();
}
test('original endpoint drawings expose an explicit geometric in-between action',async({page})=>{
  await open(page);await expect(page.getByRole('button',{name:'Make drawing in-betweens',exact:true})).toBeVisible({timeout:2000});
});

async function bytes(download:Download){const path=await download.path();if(!path)throw Error('Native download unavailable');return readFile(path);}
async function download(page:Page,id='#backup'){const waiting=page.waitForEvent('download');await page.locator(id).click();return bytes(await waiting);}
async function backup(page:Page):Promise<Film>{return JSON.parse((await download(page)).toString()) as Film;}
async function stored(page:Page,write?:unknown){return nativeCurrent(page,write===undefined?undefined:{value:write});}
async function range(page:Page,id:string,frame:number){await page.locator(id).evaluate((node,value)=>{(node as HTMLInputElement).value=String(value);node.dispatchEvent(new Event('input',{bubbles:true}));},frame);}
async function scrub(page:Page,frame:number){await range(page,'#frame',frame);await expect(page.locator('#stage')).toHaveAttribute('data-frame',String(frame));}
async function pixels(page:Page,id:string,points:{x:number;y:number}[]){return page.locator(id).evaluate((node,points)=>{const ctx=(node as HTMLCanvasElement).getContext('2d')!;return points.map(p=>[...ctx.getImageData(p.x,p.y,1,1).data]);},points);}
async function configure(page:Page){await page.locator('#make-tween').click();await expect(page.locator('#tween-panel')).toBeVisible();await page.getByRole('combobox',{name:'Ending stroke for starting stroke 1',exact:true}).selectOption('1');await page.getByRole('combobox',{name:'Ending stroke for starting stroke 2',exact:true}).selectOption('0');await page.getByRole('checkbox',{name:'Reverse ending stroke for starting stroke 1',exact:true}).check();await page.locator('#tween-count').fill('3');}
async function review(page:Page){await page.locator('#tween-review').click();await expect(page.locator('#tween-apply')).toBeEnabled();}
async function apply(page:Page){await configure(page);await review(page);await page.locator('#tween-apply').click();await expect(page.locator('#stage')).toHaveAttribute('data-frame','2');await expect(page.locator('#save-status')).toHaveText('Saved in this browser');}
function expectCandidate(actual:Film){const expected=applied();expect(actual.layers[0].keys).toEqual(expected.layers[0].keys);expect(actual.layers[1]).toEqual(expected.layers[1]);expect(actual.layers[0].cels.map(c=>c.frame)).toEqual([0,2,4,6,8]);for(const [i,cel] of actual.layers[0].cels.entries()){const want=expected.layers[0].cels[i];if(cel.frame===0||cel.frame===8){expect(cel).toEqual(want);continue;}expect(cel.strokes).toHaveLength(2);for(const [j,stroke] of cel.strokes.entries()){expect(stroke.color).toBe(want.strokes[j].color);expect(stroke.width).toBe(want.strokes[j].width);expect(stroke.points).toHaveLength(64);stroke.points.forEach((p,k)=>{expect(p.x).toBeCloseTo(want.strokes[j].points[k].x,11);expect(p.y).toBeCloseTo(want.strokes[j].points[k].y,11);});}}}

test('explicit nonidentity pairing and reversal review actual pixels without saving, then Apply is one undoable edit',async({page})=>{
  await open(page);const before=await stored(page);await page.locator('#make-tween').click();
  await expect(page.getByRole('combobox',{name:'Ending stroke for starting stroke 1',exact:true})).toHaveValue('');await expect(page.getByRole('combobox',{name:'Ending stroke for starting stroke 2',exact:true})).toHaveValue('');await expect(page.locator('#tween-apply')).toBeDisabled();
  await page.getByRole('combobox',{name:'Ending stroke for starting stroke 1',exact:true}).selectOption('1');await page.getByRole('combobox',{name:'Ending stroke for starting stroke 2',exact:true}).selectOption('0');await page.getByRole('checkbox',{name:'Reverse ending stroke for starting stroke 1',exact:true}).check();await page.locator('#tween-count').fill('3');await review(page);
  await range(page,'#tween-preview-frame',4);const c=coreAt(4);expect(await pixels(page,'#tween-preview',[c.line,c.dot,c.control])).toEqual([[128,0,128,255],[0,255,0,255],[0,255,0,255]]);await expect(page.locator('#stage')).toHaveAttribute('data-frame','0');expect(await stored(page)).toEqual(before);
  await page.locator('#tween-apply').click();await expect(page.locator('#stage')).toHaveAttribute('data-frame','2');const result=await backup(page);expectCandidate(result);await page.locator('#undo').click();expect(await backup(page)).toEqual(endpoints());await page.locator('#redo').click();expect(await backup(page)).toEqual(result);await expect(page.locator('#save-status')).toHaveText('Saved in this browser');await expect.poll(()=>stored(page)).toEqual(result);await page.reload();await expect(page.locator('#project-title')).toHaveValue(result.title);expect(await backup(page)).toEqual(result);
});

test('actual PNG and all GIF frames show held interior artwork, round dots and independent simultaneous pose',async({page},info)=>{
  await open(page);await apply(page);
  for(const frame of [0,2,3,4,6,8,11]){await scrub(page,frame);const encoded=await download(page,'#png'),c=coreAt(frame);const actual=await page.evaluate(async({data,points})=>{const bytes=Uint8Array.from(atob(data),c=>c.charCodeAt(0)),bitmap=await createImageBitmap(new Blob([bytes],{type:'image/png'}));const canvas=new OffscreenCanvas(bitmap.width,bitmap.height),ctx=canvas.getContext('2d')!;ctx.drawImage(bitmap,0,0);const result={width:bitmap.width,height:bitmap.height,pixels:points.map(p=>[...ctx.getImageData(p.x,p.y,1,1).data])};bitmap.close();return result;},{data:encoded.toString('base64'),points:[c.line,c.dot,c.control]});expect(actual).toEqual({width:640,height:360,pixels:[[...c.line.rgb,255],[...c.dot.rgb,255],[...c.control.rgb,255]]});if(frame===4)await writeFile(info.outputPath('independent-interior.png'),encoded);}
  const encoded=await download(page,'#gif');await writeFile(info.outputPath('actual-geometric-tween.gif'),encoded);const frames=decompressFrames(parseGIF(encoded.buffer.slice(encoded.byteOffset,encoded.byteOffset+encoded.byteLength)),true);expect(frames).toHaveLength(12);expect(frames.map(f=>f.delay)).toEqual(Array.from({length:12},(_,i)=>10*(Math.round((i+1)*100/12)-Math.round(i*100/12))));
  for(const [i,frame] of frames.entries()){expect(frame.dims).toEqual({left:0,top:0,width:640,height:360});for(const point of Object.values(coreAt(i))){const at=(point.y*640+point.x)*4;const palette=[Math.round(Math.floor(point.rgb[0]/32)*255/7),Math.round(Math.floor(point.rgb[1]/32)*255/7),Math.floor(point.rgb[2]/64)*85,255];expect([...frame.patch!.subarray(at,at+4)],`frame ${i} independent point`).toEqual(palette);}}
});

test('generated drawing remains separately editable and original endpoints survive Undo and Redo',async({page})=>{
  await open(page);await apply(page);const before=await backup(page);await scrub(page,4);await page.locator('#ink').fill('#ffff00');await page.locator('#stage').scrollIntoViewIfNeeded();const box=(await page.locator('#stage').boundingBox())!;await page.mouse.click(box.x+500*box.width/640,box.y+300*box.height/360);const edited=await backup(page);expect(edited.layers[0].cels[2].strokes).toHaveLength(3);for(const index of [0,1,3,4])expect(edited.layers[0].cels[index]).toEqual(before.layers[0].cels[index]);await page.locator('#undo').click();expect(await backup(page)).toEqual(before);await page.locator('#redo').click();expect(await backup(page)).toEqual(edited);
});

test('invalid and changed-back count text preserves its node and requires a fresh review',async({page})=>{
  await open(page);await configure(page);await review(page);const count=page.locator('#tween-count');await count.evaluate(node=>node.setAttribute('data-native-identity','original'));await count.fill('-');await page.locator('#tween-review').click();await expect(count).toHaveValue('-');await expect(count).toHaveAttribute('data-native-identity','original');await expect(page.locator('#tween-apply')).toBeDisabled();expect(await stored(page)).toEqual(endpoints());await count.fill('3');await expect(page.locator('#tween-apply')).toBeDisabled();await review(page);await count.fill('4');await count.fill('3');await expect(page.locator('#tween-apply')).toBeDisabled();await expect(count).toBeFocused();await review(page);await page.locator('#tween-discard').click();expect(await backup(page)).toEqual(endpoints());
});

test('raw pose drafts block opening and later raw changed-back intent retires review without losing spelling',async({page})=>{
  await open(page);const x=page.locator('#pose-x');await x.fill('-');await x.evaluate(node=>node.setAttribute('data-native-identity','same'));if(await page.locator('#make-tween').isEnabled())await page.locator('#make-tween').click();await expect(x).toHaveValue('-');await expect(page.locator('#tween-panel')).toBeHidden();await page.locator('#discard-pose-edits').click();await configure(page);await review(page);await x.fill('251');await x.fill('250');await expect(page.locator('#tween-apply')).toBeDisabled();await expect(x).toHaveAttribute('data-native-identity','same');await expect(x).toBeFocused();expect(await stored(page)).toEqual(endpoints());
});

test('preview playback preserves main frame and scratch, while main seeking and canceled layer switching retire no artwork',async({page})=>{
  await open(page);await configure(page);await review(page);await page.locator('#tween-preview-play').click();await expect(page.locator('#tween-preview-frame')).toHaveValue('8',{timeout:3000});await expect(page.locator('#stage')).toHaveAttribute('data-frame','0');expect(await stored(page)).toEqual(endpoints());await scrub(page,1);await expect(page.locator('#tween-apply')).toBeDisabled();await expect(page.locator('#tween-count')).toHaveValue('3');await review(page);page.once('dialog',d=>d.dismiss());await page.locator('[data-layer-id=control]').click();await expect(page.locator('[data-layer-id=paired]')).toHaveAttribute('aria-pressed','true');await expect(page.locator('#tween-count')).toHaveValue('3');expect(await stored(page)).toEqual(endpoints());
});

test('ordinary project and GIF downloads remain committed-only while unaccepted artwork exists',async({page})=>{
  await open(page);await configure(page);await review(page);expect(await backup(page)).toEqual(endpoints());await expect(page.locator('#tween-apply')).toBeDisabled();await review(page);const encoded=await download(page,'#gif');const frames=decompressFrames(parseGIF(encoded.buffer.slice(encoded.byteOffset,encoded.byteOffset+encoded.byteLength)),true);const frame=frames[4],at=(140*640+230)*4;expect([...frame.patch!.subarray(at,at+4)]).toEqual([255,0,0,255]);await expect(page.locator('#tween-apply')).toBeDisabled();expect(await stored(page)).toEqual(endpoints());
});

test('failed import and controlled page lifecycle never revive a reviewed proposal or erase correspondence',async({page})=>{
  await open(page);await configure(page);await review(page);page.once('dialog',d=>d.accept());await page.locator('#project-file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{invalid')});await expect(page.locator('#message')).toContainText(/unchanged/i);await expect(page.locator('#tween-count')).toHaveValue('3');await expect(page.getByRole('combobox',{name:'Ending stroke for starting stroke 1',exact:true})).toHaveValue('1');await expect(page.locator('#tween-apply')).toBeDisabled();await review(page);await page.evaluate(()=>{dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true}));dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true}));});await expect(page.locator('#tween-apply')).toBeDisabled();await expect(page.locator('#tween-count')).toHaveValue('3');expect(await stored(page)).toEqual(endpoints());
});

test('390px keyboard correspondence and dot preview fit without page overflow',async({page},info)=>{
  await page.setViewportSize({width:390,height:844});await open(page);await page.locator('#make-tween').focus();await page.keyboard.press('Enter');await page.locator('#tween-pair-order').focus();await page.keyboard.press('Enter');const first=page.getByRole('combobox',{name:'Ending stroke for starting stroke 1',exact:true}),second=page.getByRole('combobox',{name:'Ending stroke for starting stroke 2',exact:true});await first.focus();await page.keyboard.press('End');await page.keyboard.press('Enter');await second.focus();await page.keyboard.press('Home');await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');await expect(first).toHaveValue('1');await expect(second).toHaveValue('0');await page.getByRole('checkbox',{name:'Reverse ending stroke for starting stroke 1',exact:true}).focus();await page.keyboard.press('Space');await page.locator('#tween-count').fill('3');await page.locator('#tween-review').focus();await page.keyboard.press('Enter');await expect(page.locator('#tween-apply')).toBeEnabled();await page.locator('#tween-preview-frame').focus();await page.keyboard.press('End');await expect(page.locator('#tween-preview-frame')).toHaveValue('8');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('review-390px.png'),fullPage:true});await page.locator('#tween-apply').focus();await page.keyboard.press('Enter');expectCandidate(await backup(page));
});

test('late genuine project read after controlled page return cannot restore an invalidated review or overwrite artwork',async({page})=>{
  await open(page);await configure(page);await review(page);await page.evaluate(()=>{const native=File.prototype.text;const gate={waiting:[] as (()=>void)[]};Object.assign(window,{tweenReadGate:gate});File.prototype.text=async function(){const text=await native.call(this);if(this.name==='held-original.json')await new Promise<void>(resolve=>gate.waiting.push(resolve));return text;};});
  const replacement=endpoints();replacement.title='Delayed other artwork';page.once('dialog',d=>d.accept());await page.locator('#project-file').setInputFiles({name:'held-original.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(replacement))});await expect.poll(()=>page.evaluate(()=>(window as unknown as {tweenReadGate:{waiting:unknown[]}}).tweenReadGate.waiting.length)).toBe(1);
  await page.evaluate(()=>{dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true}));dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true}));});await page.locator('#tween-count').fill('4');await page.locator('#tween-count').fill('3');await page.evaluate(()=>(window as unknown as {tweenReadGate:{waiting:(()=>void)[]}}).tweenReadGate.waiting.splice(0).forEach(resolve=>resolve()));await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));await expect(page.locator('#project-title')).toHaveValue(endpoints().title);await expect(page.locator('#tween-count')).toHaveValue('3');await expect(page.locator('#tween-count')).toBeFocused();await expect(page.locator('#tween-apply')).toBeDisabled();expect(await stored(page)).toEqual(endpoints());
});

test('pointer gesture cancellation retires scratch review without committing the provisional drawing',async({page})=>{
  await open(page);await configure(page);await review(page);await page.locator('#stage').scrollIntoViewIfNeeded();const box=(await page.locator('#stage').boundingBox())!;await page.mouse.move(box.x+box.width*.75,box.y+box.height*.8);await page.mouse.down();await page.mouse.move(box.x+box.width*.8,box.y+box.height*.8);await page.keyboard.press('Escape');await page.mouse.up();await expect(page.locator('#tween-apply')).toBeDisabled();await expect(page.locator('#tween-count')).toHaveValue('3');expect(await stored(page)).toEqual(endpoints());expect(await backup(page)).toEqual(endpoints());
});

test('protected corrupt storage stays exact while reviewed in-betweens are applied in memory',async({page})=>{
  await open(page);const corrupt={schemaVersion:999,original:'Preserve this literal unsupported record'};await stored(page,corrupt);await page.reload();await expect(page.locator('#recovery-panel')).toBeVisible();await expect(page.locator('#stage')).toHaveAttribute('aria-disabled','false');
  await page.locator('#project-file-action').selectOption('replace');page.once('dialog',d=>d.accept());await page.locator('#project-file').setInputFiles({name:'safe-endpoints.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(endpoints()))});await expect(page.locator('#project-title')).toHaveValue(endpoints().title);await page.locator('[data-layer-id=paired]').click();await configure(page);await review(page);await page.locator('#tween-apply').click();await expect(page.locator('#stage')).toHaveAttribute('data-frame','2');expectCandidate(await backup(page));expect(await stored(page)).toEqual(corrupt);expect(JSON.parse((await download(page,'#recovery-download')).toString())).toEqual(corrupt);
  page.once('dialog',d=>d.accept());await page.locator('#replace-saved-project').click();await expect(page.locator('#save-status')).toHaveText('Saved in this browser');expectCandidate(await stored(page) as Film);
});

test('open correspondence updates after both endpoint drawings gain a stroke without erasing raw choices',async({page})=>{
  await open(page);await configure(page);await page.locator('#ink').fill('#ffff00');
  const paint=async()=>{await page.locator('#stage').scrollIntoViewIfNeeded();const box=(await page.locator('#stage').boundingBox())!;await page.mouse.click(box.x+500*box.width/640,box.y+300*box.height/360);};
  await paint();await scrub(page,8);await paint();await expect(page.locator('#tween-pairs [data-tween-stroke]')).toHaveCount(3);
  await expect(page.getByRole('combobox',{name:'Ending stroke for starting stroke 1',exact:true})).toHaveValue('1');await expect(page.getByRole('combobox',{name:'Ending stroke for starting stroke 2',exact:true})).toHaveValue('0');await expect(page.locator('#tween-count')).toHaveValue('3');
  const third=page.getByRole('combobox',{name:'Ending stroke for starting stroke 3',exact:true});await expect(third).toHaveValue('');await third.selectOption('2');await review(page);
  const thumbnails=page.locator('#tween-pairs [data-tween-stroke="2"] canvas');expect(await thumbnails.count()).toBeGreaterThan(0);
  for(const canvas of await thumbnails.all())expect(await canvas.evaluate(node=>{const c=node as HTMLCanvasElement,rgba=c.getContext('2d')!.getImageData(0,0,c.width,c.height).data;for(let i=0;i<rgba.length;i+=4)if(rgba[i]>200&&rgba[i+1]>200&&rgba[i+2]<80&&rgba[i+3]>100)return true;return false;})).toBe(true);
  await expect(page.locator('#tween-apply')).toBeEnabled();await expect(page.locator('#save-status')).toHaveText('Saved in this browser');const committed=await stored(page) as Film;expect(committed.layers[0].cels.map(c=>c.strokes.length)).toEqual([3,3]);
});

test('Undo removing the scratch owner requires explicit consent and dismissal keeps its raw controls',async({page})=>{
  await open(page);await page.locator('#add-layer').click();const owner=await page.locator('#layers [aria-pressed=true]').getAttribute('data-layer-id');expect(owner).not.toBeNull();await page.locator('#make-tween').click();const count=page.locator('#tween-count');await count.fill('2');await count.evaluate(node=>node.setAttribute('data-native-identity','owner-count'));
  page.once('dialog',dialog=>dialog.dismiss());await page.locator('#undo').click();await expect(page.locator('#layers [aria-pressed=true]')).toHaveAttribute('data-layer-id',owner!);await expect(count).toHaveValue('2');await expect(count).toHaveAttribute('data-native-identity','owner-count');
  page.once('dialog',dialog=>dialog.accept());await page.locator('#undo').click();await expect(page.locator(`[data-layer-id="${owner}"]`)).toHaveCount(0);await expect(page.locator('#tween-panel')).toBeHidden();expect(await backup(page)).toEqual(endpoints());
});
