import {test,expect,type Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
async function backup(page:Page){const [file]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Export project backup',exact:true}).click()]);return JSON.parse((await readFile((await file.path())!)).toString());}
async function point(page:Page){return (await page.locator('#construction-shell [data-face="0"]').getAttribute('points'))!.split(' ')[0].split(',').map(Number);}
function expected(waist:number,hem:number,slant:number,yaw:number){const top=waist/(2*Math.PI),h=Math.sqrt(slant**2-((hem-waist)/(2*Math.PI))**2),scale=240/Math.max(hem/Math.PI,h),a=yaw*Math.PI/180,t=20*Math.PI/180;return [240+top*Math.cos(a)*scale,180+(-h/2*Math.cos(t)-top*Math.sin(a)*Math.sin(t))*scale];}
test('2D pattern and actual projected 3D vertices share committed measurements with exact history and reload',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Apply measured pattern',exact:true}).click();const initial=await backup(page),before=await point(page);expect(before[0]).toBeCloseTo(expected(80,140,60,30)[0],3);expect(before[1]).toBeCloseTo(expected(80,140,60,30)[1],3);await expect(page.locator('#construction-shell polygon')).toHaveCount(32);await expect(page.locator('#construction-shell [data-seam]')).toHaveCount(2);await page.getByLabel('Waist circumference (cm)',{exact:true}).fill('100');expect(await point(page)).toEqual(before);await page.getByRole('button',{name:'Apply measured pattern',exact:true}).click();const next=await point(page);expect(next[0]).toBeCloseTo(expected(100,140,60,30)[0],3);expect(next[1]).toBeCloseTo(expected(100,140,60,30)[1],3);await expect(page.locator('#construction-summary')).toContainText('waist arc 50 cm');const saved=await backup(page);expect(saved).toEqual({...initial,construction:{kind:'flared-skirt',waist:100,hem:140,slant:60}});await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await backup(page)).toEqual(initial);expect(await point(page)).toEqual(before);await page.getByRole('button',{name:'Redo',exact:true}).click();expect(await point(page)).toEqual(next);await expect(page.locator('#save-state')).toHaveText('Locally saved');await page.reload();expect(await backup(page)).toEqual(saved);expect(await point(page)).toEqual(next);
});
test('session view rotation keeps complete graph redo and invalid unapplied dimensions',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Apply measured pattern',exact:true}).click();const original=await backup(page),start=await point(page);await page.getByLabel('Waist circumference (cm)',{exact:true}).fill('90');await page.getByRole('button',{name:'Apply measured pattern',exact:true}).click();await page.getByRole('button',{name:'Undo',exact:true}).click();await page.getByLabel('Slant seam length (cm)',{exact:true}).fill('');await page.getByRole('button',{name:'Rotate shell right',exact:true}).click();await expect(page.getByLabel('Slant seam length (cm)',{exact:true})).toHaveValue('');await expect(page.locator('#shell-angle')).toContainText('45°');expect(await point(page)).not.toEqual(start);expect(await backup(page)).toEqual(original);await expect(page.getByRole('button',{name:'Redo',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Reset shell view',exact:true}).click();expect(await point(page)).toEqual(start);await page.getByRole('button',{name:'Apply measured pattern',exact:true}).click();expect(await backup(page)).toEqual(original);await expect(page.getByLabel('Slant seam length (cm)',{exact:true})).toHaveValue('');await page.getByRole('button',{name:'Discard pattern edits',exact:true}).click();await page.getByRole('group',{name:'Rotate measured skirt construction',exact:true}).focus();await page.keyboard.press('ArrowLeft');await expect(page.locator('#shell-angle')).toContainText('15°');expect(await backup(page)).toEqual(original);await expect(page.getByRole('button',{name:'Redo',exact:true})).toBeEnabled();
});
test('390px linked shell is readable and camera buttons preserve a focused raw placement before blur',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/');await page.getByRole('button',{name:'Apply measured pattern',exact:true}).click();const before=await backup(page),original=await point(page),placement=page.getByLabel('Horizontal position (%)',{exact:true});await placement.fill('');await page.getByRole('button',{name:'Rotate shell right',exact:true}).click();await expect(placement).toHaveValue('');await expect(placement).toBeFocused();expect(await point(page)).toEqual(original);expect(await backup(page)).toEqual(before);await placement.fill('50');await placement.press('Tab');await page.getByRole('button',{name:'Rotate shell right',exact:true}).click();await expect(page.locator('#shell-angle')).toContainText('45°');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('.shell-paper').screenshot({path:test.info().outputPath('linked-shell-mobile.png')});
});
test('actual OBJ export keeps committed centimetre geometry independent of rotation and refuses raw drafts',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Apply measured pattern',exact:true}).click();const original=await backup(page);
 async function obj(){const [file]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Export construction OBJ',exact:true}).click()]);expect(file.suggestedFilename()).toMatch(/-skirt-construction\.obj$/);return (await readFile((await file.path())!)).toString();}
 const text=await obj(),vertices=text.split('\n').filter(l=>l.startsWith('v ')).map(l=>l.split(' ').slice(1).map(Number));expect(vertices).toHaveLength(64);expect(text.split('\n').filter(l=>l.startsWith('f '))).toHaveLength(32);expect(Math.hypot(vertices[0][0],vertices[0][2])*2*Math.PI).toBeCloseTo(80,4);expect(Math.hypot(...vertices[0].map((v,i)=>v-vertices[32][i]))).toBeCloseTo(60,4);expect(text).toContain('g Front_Panel');expect(text).toContain('g Back_Panel');expect(text).toContain('l 17 49');await page.getByRole('button',{name:'Rotate shell right',exact:true}).click();expect(await obj()).toBe(text);expect(await backup(page)).toEqual(original);
 await page.getByLabel('Slant seam length (cm)',{exact:true}).fill('');let downloads=0;page.on('download',()=>downloads++);await page.getByRole('button',{name:'Export construction OBJ',exact:true}).click();await expect(page.getByText('Apply or discard pattern drafts before exporting.',{exact:true})).toBeVisible();expect(downloads).toBe(0);await expect(page.getByLabel('Slant seam length (cm)',{exact:true})).toHaveValue('');expect(await backup(page)).toEqual(original);
});
test('accepted whole-project imports reset previous raw measurements even when saved construction is identical',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Apply measured pattern',exact:true}).click();const original=await backup(page),incoming={...original,title:'Another concept with the same measurements'};
 for(const p of [incoming,incoming]){await page.getByLabel('Waist circumference (cm)',{exact:true}).fill('95');await page.getByLabel('Import project backup').setInputFiles({name:'same-pattern.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(p))});await expect(page.getByLabel('Waist circumference (cm)',{exact:true})).toHaveValue('80');expect(await backup(page)).toEqual(incoming);await expect(page.locator('#shell-angle')).toContainText('waist 80 cm');}
 const legacy={...incoming};delete legacy.construction;for(const p of [legacy,legacy]){await page.getByLabel('Import project backup').setInputFiles({name:'legacy-pattern.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(p))});await expect(page.locator('#construction-summary')).toContainText('No measured pattern');await page.getByLabel('Waist circumference (cm)',{exact:true}).fill('95');await page.getByLabel('Import project backup').setInputFiles({name:'legacy-again.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(p))});await expect(page.getByLabel('Waist circumference (cm)',{exact:true})).toHaveValue('80');expect(await backup(page)).toEqual(legacy);}
});
