import {test,expect,type Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {createProject,type Project} from '../src/model.ts';
async function download(page:Page,name:string){const [file]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name,exact:true}).click()]);return {bytes:await readFile((await file.path())!),name:file.suggestedFilename()};}
async function backup(page:Page){return JSON.parse((await download(page,'Export project backup')).bytes.toString()) as Project;}
async function open(page:Page,p:Project){await page.getByLabel('Import project backup').setInputFiles({name:'construction.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(p))});await expect(page.getByLabel('Concept name')).toHaveValue(p.title);}
test('measured pattern preserves complete photo/sketch graph through export history and reload',async({page})=>{
 await page.goto('/');const p=createProject();p.title='Measured & original';p.note='Keep this note';p.strokes=[{id:'retained',color:'#ff0000',width:8,points:[{x:.5,y:.5}]}];p.photo=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=40;c.height=50;c.getContext('2d')!.fillRect(0,0,40,50);return {dataUrl:c.toDataURL('image/jpeg'),width:40,height:50,name:'original.jpg'}});await open(page,p);const before=await backup(page);await page.getByRole('button',{name:'Apply measured pattern',exact:true}).click();const expected={...before,construction:{kind:'flared-skirt',waist:80,hem:140,slant:60}};expect(await backup(page)).toEqual(expected);const svg=await download(page,'Export full-size pattern SVG');expect(svg.name).toBe('Measured  original-skirt-pattern.svg');const parsed=await page.evaluate(markup=>{const d=new DOMParser().parseFromString(markup,'image/svg+xml');const root=document.importNode(d.documentElement,true);document.body.append(root);const path=root.querySelector('#panel-front path') as SVGGeometryElement;const perimeter=path.getTotalLength(),bounds=path.getBBox();root.remove();return {perimeter,netWidth:bounds.width,netLength:bounds.height,error:!!d.querySelector('parsererror'),width:d.documentElement.getAttribute('width'),height:d.documentElement.getAttribute('height'),viewBox:d.documentElement.getAttribute('viewBox'),front:!!d.querySelector('#panel-front'),back:!!d.querySelector('#panel-back'),square:d.querySelector('rect')?.getAttribute('width'),bad:d.querySelectorAll('image,script,foreignObject').length,text:d.documentElement.textContent}},svg.bytes.toString());expect(parsed.error).toBe(false);expect(parsed.perimeter).toBeCloseTo(230,1);expect(parsed.netWidth).toBeCloseTo(280*Math.sin(.25),3);expect(parsed.netLength).toBeCloseTo(140-80*Math.cos(.25),3);expect(parsed.front&&parsed.back).toBe(true);expect(parsed.square).toBe('5');expect(parsed.bad).toBe(0);const dimensions=parsed.viewBox!.split(' ').map(Number);expect(Number(parsed.width!.replace('mm',''))).toBeCloseTo(dimensions[2]*10,5);expect(Number(parsed.height!.replace('mm',''))).toBeCloseTo(dimensions[3]*10,5);expect(parsed.text).toContain('waist arc 40 cm');expect(parsed.text).toContain('hem arc 70 cm');expect(svg.bytes.toString()).not.toContain('Keep this note');await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await backup(page)).toEqual(before);await page.getByRole('button',{name:'Redo',exact:true}).click();expect(await backup(page)).toEqual(expected);await expect(page.locator('#save-state')).toHaveText('Locally saved');await page.reload();expect(await backup(page)).toEqual(expected);await page.getByLabel('Waist circumference (cm)',{exact:true}).fill('90');await page.getByRole('button',{name:'Apply measured pattern',exact:true}).click();expect((await backup(page)).construction?.waist).toBe(90);
});
test('invalid raw and unrelated placement drafts refuse before blur and retain redo',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Apply measured pattern',exact:true}).click();const p=await backup(page);await page.getByLabel('Waist circumference (cm)',{exact:true}).fill('90');await page.getByRole('button',{name:'Apply measured pattern',exact:true}).click();await page.getByRole('button',{name:'Undo',exact:true}).click();for(const raw of ['','NaN','151']){await page.getByLabel('Waist circumference (cm)',{exact:true}).fill(raw);await page.getByRole('button',{name:'Apply measured pattern',exact:true}).click();await expect(page.getByLabel('Waist circumference (cm)',{exact:true})).toHaveValue(raw);expect(await backup(page)).toEqual(p);await expect(page.getByRole('button',{name:'Redo',exact:true})).toBeEnabled();}await page.getByRole('button',{name:'Discard pattern edits',exact:true}).click();await page.getByRole('button',{name:'Apply measured pattern',exact:true}).click();await expect(page.getByRole('button',{name:'Redo',exact:true})).toBeEnabled();const position=page.getByLabel('Horizontal position (%)',{exact:true});await position.fill('');await page.getByRole('button',{name:'Apply measured pattern',exact:true}).click();await expect(position).toBeFocused();await expect(position).toHaveValue('');await page.getByRole('button',{name:'Apply measured pattern',exact:true}).focus();await page.keyboard.press('Enter');expect(await backup(page)).toEqual(p);await expect(page.getByRole('button',{name:'Redo',exact:true})).toBeEnabled();
});
test('construction input retires a held genuine backup read and malformed construction preserves work',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Apply measured pattern',exact:true}).click();const before=await backup(page);await page.evaluate(()=>{const original=File.prototype.text;let release!:()=>void;const gate=new Promise<void>(r=>release=r);Object.assign(window,{releaseConstructionFile:release});File.prototype.text=async function(){const text=await original.call(this);if(this.name==='held-pattern.json')await gate;return text;};});const incoming=createProject();incoming.title='Must not replace pattern intent';await page.getByLabel('Import project backup').setInputFiles({name:'held-pattern.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(incoming))});await page.getByLabel('Waist circumference (cm)',{exact:true}).fill('95');await page.evaluate(()=>{(window as unknown as {releaseConstructionFile:()=>void}).releaseConstructionFile()});await expect(page.locator('#load-state')).toBeHidden();expect(await backup(page)).toEqual(before);await expect(page.getByLabel('Waist circumference (cm)',{exact:true})).toHaveValue('95');await page.getByRole('button',{name:'Discard pattern edits',exact:true}).click();await page.getByLabel('Import project backup').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...before,construction:{...before.construction,hem:40}}))});await expect(page.locator('#message')).toContainText('hem');expect(await backup(page)).toEqual(before);
});
test('390px keyboard pattern editing and committed export stay contained',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/');await page.getByLabel('Waist circumference (cm)',{exact:true}).fill('100');await page.getByRole('button',{name:'Apply measured pattern',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.locator('#construction-summary')).toContainText('waist 100 cm');expect((await backup(page)).construction).toEqual({kind:'flared-skirt',waist:100,hem:140,slant:60});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole('heading',{name:'Draft a two-panel skirt',exact:true}).scrollIntoViewIfNeeded();await page.locator('.construction-panel').screenshot({path:test.info().outputPath('measured-pattern-mobile.png')});
});
