import {test,expect,type Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
async function download(page:Page,name:string){const [file]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name,exact:true}).click()]);return (await readFile((await file.path())!)).toString();}
async function backup(page:Page){return JSON.parse(await download(page,'Export project backup'));}
async function apply(page:Page){await page.getByRole('button',{name:'Apply measured pattern',exact:true}).click();await page.getByRole('button',{name:'Apply grading rule',exact:true}).click();}
test('saved grading retains complete concept and exports actual labelled full-scale size nets',async({page})=>{
 await page.goto('/');const artwork=await backup(page);artwork.note='Retained grading notes';artwork.strokes=[{id:'graded-original-stroke',color:'#abcdef',width:4,points:[{x:.2,y:.3},{x:.7,y:.8}]}];artwork.photo=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=36;canvas.height=44;canvas.getContext('2d')!.fillRect(0,0,36,44);return {dataUrl:canvas.toDataURL('image/jpeg'),width:36,height:44,name:'grading-original.jpg'};});await page.getByLabel('Import project backup').setInputFiles({name:'original-artwork.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(artwork))});await expect(page.getByLabel('Concept note',{exact:true})).toHaveValue(artwork.note);expect(await backup(page)).toEqual(artwork);await page.getByRole('button',{name:'Apply measured pattern',exact:true}).click();const base=await backup(page);await page.getByRole('button',{name:'Apply grading rule',exact:true}).click();const saved=await backup(page);expect(saved).toEqual({...base,grading:{waistStep:4,hemStep:6,slantStep:0,steps:2}});await expect(page.locator('#grading-table tbody tr')).toHaveCount(5);const svg=await download(page,'Export graded pattern set SVG');const actual=await page.evaluate(text=>{const doc=new DOMParser().parseFromString(text,'image/svg+xml'),root=document.importNode(doc.documentElement,true);document.body.append(root);const groups=Array.from(root.querySelectorAll('g[id^="size-"]')).map(g=>{const path=g.querySelector('path') as SVGGeometryElement;return {label:g.querySelector('text')!.textContent,perimeter:path.getTotalLength(),innerWidth:g.querySelector('svg')!.getAttribute('width'),viewBox:g.querySelector('svg')!.getAttribute('viewBox')};});const ids=Array.from(root.querySelectorAll('[id]')).map(x=>x.id),width=root.getAttribute('width'),viewBox=root.getAttribute('viewBox');root.remove();return {groups,ids,width,viewBox,error:!!doc.querySelector('parsererror')};},svg);expect(actual.error).toBe(false);expect(actual.groups).toHaveLength(5);expect(new Set(actual.ids).size).toBe(actual.ids.length);expect(actual.groups[0].label).toContain('waist 72 cm');expect(actual.groups[4].label).toContain('hem 152 cm');for(let i=0;i<5;i++){expect(actual.groups[i].perimeter).toBeCloseTo((72+4*i+128+6*i)/2+120,2);expect(Number(actual.groups[i].innerWidth)).toBeCloseTo(Number(actual.groups[i].viewBox!.split(' ')[2]),4);}expect(Number(actual.width!.replace('mm',''))).toBeCloseTo(Number(actual.viewBox!.split(' ')[2])*10,4);await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await backup(page)).toEqual(base);await page.getByRole('button',{name:'Redo',exact:true}).click();expect(await backup(page)).toEqual(saved);await expect(page.locator('#save-state')).toHaveText('Locally saved');await page.reload();expect(await backup(page)).toEqual(saved);
});
test('grading rejects the whole invalid derived set and protects raw fields plus redo before blur',async({page})=>{
 await page.goto('/');await apply(page);const original=await backup(page);await page.getByLabel('Waist increment per size (cm)',{exact:true}).fill('5');await page.getByRole('button',{name:'Apply grading rule',exact:true}).click();await page.getByRole('button',{name:'Undo',exact:true}).click();await page.getByLabel('Steps on each side of base',{exact:true}).fill('3');await page.getByLabel('Hem increment per size (cm)',{exact:true}).fill('-20');await page.getByRole('button',{name:'Apply grading rule',exact:true}).click();await expect(page.locator('#message')).toContainText('Base');expect(await backup(page)).toEqual(original);await expect(page.getByRole('button',{name:'Redo',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Export graded pattern set SVG',exact:true}).click();await expect(page.locator('#message')).toContainText('grading drafts');await page.getByLabel('Import project backup').setInputFiles({name:'invalid-grading.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...original,grading:{...original.grading,steps:4}}))});await expect(page.locator('#message')).toContainText('grading steps');expect(await backup(page)).toEqual(original);await expect(page.getByLabel('Hem increment per size (cm)',{exact:true})).toHaveValue('-20');await expect(page.getByRole('button',{name:'Redo',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Discard grading edits',exact:true}).click();const raw=page.getByLabel('Horizontal position (%)',{exact:true});await raw.fill('');await page.getByRole('button',{name:'Apply grading rule',exact:true}).click();await expect(raw).toHaveValue('');await expect(raw).toBeFocused();expect(await backup(page)).toEqual(original);
});
test('390px seven-size grading survives identical import and resets abandoned grading drafts',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/');await page.getByRole('button',{name:'Apply measured pattern',exact:true}).click();await page.getByLabel('Steps on each side of base',{exact:true}).fill('3');await page.getByRole('button',{name:'Apply grading rule',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.locator('#grading-table tbody tr')).toHaveCount(7);const saved=await backup(page);await page.getByLabel('Waist increment per size (cm)',{exact:true}).fill('');await page.getByLabel('Import project backup').setInputFiles({name:'graded.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(saved))});await expect(page.getByLabel('Waist increment per size (cm)',{exact:true})).toHaveValue('4');expect(await backup(page)).toEqual(saved);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('.grading-panel').screenshot({path:test.info().outputPath('grading-mobile.png')});
});
test('valid base edits that invalidate a saved graded size refuse without false success or losing raw input and redo',async({page})=>{
 await page.goto('/');await apply(page);const original=await backup(page);await page.getByLabel('Waist increment per size (cm)',{exact:true}).fill('5');await page.getByRole('button',{name:'Apply grading rule',exact:true}).click();await page.getByRole('button',{name:'Undo',exact:true}).click();await page.getByLabel('Waist circumference (cm)',{exact:true}).fill('50');await page.getByRole('button',{name:'Apply measured pattern',exact:true}).click();await expect(page.locator('#message')).toContainText('Base -2');await expect(page.getByLabel('Waist circumference (cm)',{exact:true})).toHaveValue('50');expect(await backup(page)).toEqual(original);await expect(page.getByRole('button',{name:'Redo',exact:true})).toBeEnabled();await expect(page.locator('#shell-angle')).toContainText('waist 80 cm');await page.getByRole('button',{name:'Discard pattern edits',exact:true}).click();await page.getByLabel('Waist circumference (cm)',{exact:true}).fill('90');await page.getByRole('button',{name:'Apply measured pattern',exact:true}).click();expect((await backup(page)).construction.waist).toBe(90);await expect(page.locator('#grading-table')).toContainText('82');
});
test('removing a saved grading rule preserves base drafts and artwork and is fully undoable',async({page})=>{
 await page.goto('/');await apply(page);const original=await backup(page);await page.getByLabel('Waist circumference (cm)',{exact:true}).fill('50');await page.getByRole('button',{name:'Remove grading rule',exact:true}).click({timeout:2000});const without={...original};delete without.grading;expect(await backup(page)).toEqual(without);await expect(page.getByLabel('Waist circumference (cm)',{exact:true})).toHaveValue('50');await page.getByRole('button',{name:'Apply measured pattern',exact:true}).click();expect((await backup(page)).construction.waist).toBe(50);await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await backup(page)).toEqual(without);await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await backup(page)).toEqual(original);await expect(page.locator('#grading-table tbody tr')).toHaveCount(5);
});
