import test from 'node:test';
import assert from 'node:assert/strict';
import {validateGrading,gradedSizes,gradedPatternSvg} from '../src/grading.ts';
import {createProject,validateProject} from '../src/model.ts';
const draft={kind:'flared-skirt' as const,waist:80,hem:140,slant:60},rule={waistStep:4,hemStep:6,slantStep:1,steps:2};
test('grading produces exact relative measurements without changing the base',()=>{const sizes=gradedSizes(draft,rule);assert.equal(sizes.length,5);assert.deepEqual(sizes.map(s=>[s.offset,s.draft.waist,s.draft.hem,s.draft.slant]),[[-2,72,128,58],[-1,76,134,59],[0,80,140,60],[1,84,146,61],[2,88,152,62]]);assert.equal(draft.waist,80);assert.notEqual(sizes[2].draft,draft);});
test('rules reject accessors invalid counts non-finite or unchanging sets and invalid derived garments',()=>{for(const r of [{...rule,steps:0},{...rule,steps:4},{...rule,steps:1.5},{...rule,waistStep:NaN},{...rule,hemStep:21},{...rule,waistStep:0,hemStep:0,slantStep:0},{...rule,extra:true}])assert.throws(()=>validateGrading(r));let calls=0;const accessor={...rule};Object.defineProperty(accessor,'waistStep',{get(){calls++;return 4}});assert.throws(()=>validateGrading(accessor));assert.equal(calls,0);assert.throws(()=>gradedSizes({...draft,waist:50},rule));assert.throws(()=>gradedSizes(draft,{...rule,hemStep:-20,steps:3}));});
test('grading optional complete-project data round-trips detached while legacy absence stays exact',()=>{const p=createProject();assert.deepEqual(validateProject(p),p);assert.equal(Object.hasOwn(validateProject(p),'grading'),false);const next={...p,construction:draft,grading:rule};const copy=validateProject(next);assert.deepEqual(copy,next);copy.grading!.waistStep=8;assert.equal(rule.waistStep,4);assert.throws(()=>validateProject({...p,grading:rule}));});
test('size-set SVG labels every relative size with physical dimensions and calibration',()=>{const svg=gradedPatternSvg(draft,rule);assert.equal((svg.match(/id="size-/g)||[]).length,5);assert.equal((svg.match(/width="5" height="5"/g)||[]).length,5);assert.match(svg,/Base -2/);assert.match(svg,/waist 88 cm/);assert.match(svg,/width="[\d.]+mm" height="[\d.]+mm"/);assert.doesNotMatch(svg,/NaN|Infinity|script|<image|foreignObject/);});
