/* global console, process, window */
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {readFile,writeFile,stat} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {URL} from 'node:url';
import {performance} from 'node:perf_hooks';
import {chromium,expect} from '@playwright/test';

// Completed source/wheel CLI artifacts are compared byte-for-byte, never used
// to compute original expected source/objects; those are frozen in Python fixture.
const arg=name=>{const i=process.argv.indexOf(name);return i<0?null:process.argv[i+1];};
const sha=b=>createHash('sha256').update(b).digest('hex');
const redact=s=>String(s).replace(/#session=[a-f0-9]{64}/g,'#session=[private]').replace(/\b[a-f0-9]{64}\b/g,'[64-hex omitted]');
async function download(page,id,out,name){const pending=page.waitForEvent('download',{timeout:45000});await page.locator(id).click();await(await pending).saveAs(join(out,name));return readFile(join(out,name));}
async function main(){
 const out=resolve(arg('--output')??'');assert(arg('--output')&&arg('--session-file'),'Supply prepared --output and root-owned0600 --session-file. No service ownership.');
 const sessionFile=resolve(arg('--session-file')),meta=await stat(sessionFile);assert(meta.isFile()&&meta.size<=4096&&(meta.mode&0o077)===0,'Private service startup file must be regular bounded and owner-only');
 const session=JSON.parse(await readFile(sessionFile,'utf8')),url=new URL(session.url);assert.equal(url.hostname,'127.0.0.1');assert.equal(url.protocol,'http:');assert.match(url.hash,/^#session=[a-f0-9]{64}$/);
 const oracle=JSON.parse(await readFile(join(out,'fixture-oracle.json'),'utf8')),catalogCli=await readFile(join(out,'maximum-cli.json')),expected=JSON.parse(await readFile(join(out,'expected-catalog.json'),'utf8')),cliProof=JSON.parse(await readFile(join(out,'cli-verification.json'),'utf8'));assert.equal(cliProof.status,'passed');assert.deepEqual(JSON.parse(catalogCli),expected);
 const evidence={schemaVersion:1,issue:123,status:'running',scriptSha256:sha(await readFile(new URL(import.meta.url))),fixtureOracleSha256:sha(await readFile(join(out,'fixture-oracle.json'))),rootOrigin:url.origin,checks:[],artifacts:[],operations:[],pageErrors:[],externalRequestCount:0,scope:'Actual original tree catalog paging, explicit pinned source handoff and exact completed CLI/browser artifacts; no optional parsers or producer oracle imports.'};let browser,context;const began=performance.now(),save=()=>writeFile(join(out,'browser-verification.json'),JSON.stringify(evidence,null,2)+'\n');await save();
 try{
  browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});context=await browser.newContext({acceptDownloads:true,viewport:{width:1280,height:1000}});evidence.browserVersion=browser.version();const cdp=await browser.newBrowserCDPSession();evidence.browserPids=(await cdp.send('SystemInfo.getProcessInfo')).processInfo.filter(p=>p.type==='browser').map(p=>p.id);await cdp.detach();const page=await context.newPage();page.on('dialog',d=>d.accept());page.on('pageerror',e=>evidence.pageErrors.push(redact(e.message)));page.on('request',r=>{if(/^https?:/.test(r.url())&&new URL(r.url()).origin!==url.origin)evidence.externalRequestCount++;if(r.method()==='POST'&&new URL(r.url()).pathname==='/api/jobs')evidence.operations.push(JSON.parse(r.postData()).operation);});
  await page.goto(url.href);await expect(page.locator('#workspace-mode')).toBeVisible();await expect(page.locator('#ref')).toBeEnabled();await expect.poll(()=>page.evaluate(()=>window.location.hash)).toBe('');await page.locator('#workspace-mode').selectOption('comparison');await page.locator('#changes-left-ref').fill('max-left');await page.locator('#changes-right-ref').fill('max-right');await page.locator('#changes-discover').click();await expect(page.locator('#changes-download-json')).toHaveAttribute('href',/^blob:/,{timeout:45000});await expect(page.locator('#stop-button')).toBeDisabled();await expect(page.locator('#changes-summary')).toContainText(/10,?000/);await expect(page.locator('#changes-table tbody tr')).toHaveCount(100);const catalog=await download(page,'#changes-download-json',out,'browser-changed-files.json');assert(catalog.equals(catalogCli));assert.deepEqual(JSON.parse(catalog),expected);evidence.artifacts.push({file:'browser-changed-files.json',bytes:catalog.length,sha256:sha(catalog)});await page.locator('#changes-next').click();await expect(page.locator('#changes-table tbody tr')).toHaveCount(100);const row=page.locator('#changes-table tbody tr').filter({hasText:oracle.selectedPath});await expect(row).toHaveCount(1);await expect(row).toHaveAttribute('data-change-index','101');await row.locator('[data-use-change]').click();assert.deepEqual(evidence.operations,['changed-files']);for(const side of['left','right']){await expect(page.locator(`#${side}-ref`)).toHaveValue(oracle.revisions[side==='left'?'max-left':'max-right']);await expect(page.locator(`#${side}-path`)).toHaveValue(JSON.stringify(oracle.selectedPath));await expect(page.locator(`#${side}-selection-mode`)).toHaveValue('whole');}await expect(page.locator('#compare-button')).toBeDisabled();evidence.checks.push('10000 metadata rows exact to source/installed CLI;100-row DOM pagination and global index101 explicit handoff preserve fullpins and cause no source/report request.');
  for(const side of['left','right']){await page.locator(`#${side}-open-source`).click();await expect(page.locator(`#${side}-source-caption`)).toContainText(/physical|committed/);await expect(page.locator('#stop-button')).toBeDisabled();}await page.locator('#compare-button').click();await expect(page.locator('#comparison-download-json')).toHaveAttribute('href',/^blob:/,{timeout:45000});await expect(page.locator('#stop-button')).toBeDisabled();for(const fmt of['json','html']){const b=await download(page,`#comparison-download-${fmt}`,out,`browser-selected-comparison.${fmt}`),cli=await readFile(join(out,`selected-comparison.${fmt}`));assert(b.equals(cli));evidence.artifacts.push({file:`browser-selected-comparison.${fmt}`,bytes:b.length,sha256:sha(b)});if(fmt==='json'){const report=JSON.parse(b);assert.equal(report.left.source,oracle.selectedLeftSource);assert.equal(report.right.source,oracle.selectedRightSource);assert.equal(report.left.revision,oracle.revisions['max-left']);assert.equal(report.right.revision,oracle.revisions['max-right']);assert.deepEqual([report.unchanged_lines,report.removed_lines,report.added_lines],[1,1,1]);}}
  assert.deepEqual(evidence.operations,['changed-files','source','source','comparison']);evidence.checks.push('Explicit native present-source loads and comparison retain original committed bytes, not dirty worktree; JSON and HTML downloads byte-identical to optional-parser-free installed CLI.');assert.equal(await page.evaluate(()=>window.localStorage.length+window.sessionStorage.length),0);await page.screenshot({path:join(out,'desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>window.document.documentElement.scrollWidth<=window.innerWidth));await page.screenshot({path:join(out,'390px.png'),fullPage:true});assert.deepEqual(evidence.pageErrors,[]);assert.equal(evidence.externalRequestCount,0);evidence.status='passed';console.log(JSON.stringify({status:'passed',entries:10000,catalogBytes:catalog.length,operations:evidence.operations},null,2));
 }catch(e){evidence.status='failed';evidence.failure={name:e.name,message:redact(e.message)};throw Error(`Independent native phase failed (${e.name}); sanitized receipt retained.`);}finally{await context?.close();await browser?.close();evidence.browserClosed=true;evidence.wallMs=performance.now()-began;await save();}
}
main().catch(e=>{console.error(e.message);process.exitCode=1;});
