// Original, independent #124 capacity/A-V probe. No production module imports.
// Root owns fixture generation and the app server; this script owns only its browsers.
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {performance} from 'node:perf_hooks';
import {chromium,expect} from '@playwright/test';
import {saveDownload} from './download-diagnostics.mjs';

const RATE=48000,FRAMES=60*RATE,WIDTH=960,HEIGHT=540;
const WAV_CAP=12*1024**2,META_CAP=324*1024,ARCHIVE_CAP=16*1024**2;
const SHA=b=>createHash('sha256').update(b).digest('hex');
const JSON_BYTES=v=>Buffer.from(JSON.stringify(v));
const COLORS=['#ff8000','#0080ff','#ffff00','#ff00ff'],LIGHTS=[.75,.9,1.05,1.2],SHOTS=[2,7,11,16];
const CUE_TIMES=[...Array.from({length:30},(_,i)=>i*2),59,60];
const SOURCE_GATES=[[10,18],[20,28],[30,38],[40,50]],OUTPUT_GATES=[[5,13],[15,23],[25,33],[35,45]];
const TARGETS=Array.from({length:20},(_,i)=>[i*3+.75,i*3+2.25]).flat();
const FOCAL=270/Math.tan(25*Math.PI/180),SHADE=.28+.72*.6/Math.sqrt(.16+1+.36);
const RMS=(13107/32768)*.5/Math.sqrt(2);
const GATES=Object.freeze({markerSeconds:.1,transitionGuardSeconds:.15,binSeconds:.01,markerRms:.05,rmsRelative:.05,pitchHz:2,quietRms:.001,wrongToneAmplitude:.01,pixelError:24,pixelMatches:23,pixelCount:27,videoPtsSeconds:.2,minVideoFrames:600,minSpanSeconds:59,maxSpanSeconds:62});
const args=process.argv.slice(2),option=name=>{const at=args.indexOf(name);return at<0?null:args[at+1];};
const output=option('--output'),fixtures=option('--fixtures');
const phase=args.includes('--prepare')?'prepare':args.includes('--capture')?'capture':args.includes('--inspect')?'inspect':null;
function originalFilm(index){return {schemaVersion:3,title:`Original soundtrack scene ${index+1}`,light:LIGHTS[index],actors:[
  {name:`Moving performer ${index+1}`,color:COLORS[index],performanceMode:'blocking',cues:CUE_TIMES.map((time,i)=>({time,x:-1.2+time/80,z:0,action:['idle','wave','walk'][i%3],visible:true}))},
  {name:`Fixed control ${index+1}`,color:'#00ff00',performanceMode:'blocking',cues:CUE_TIMES.map(time=>({time,x:1.2,z:0,action:'idle',visible:true}))}],
  shots:Array.from({length:20},(_,i)=>{const x=(i%4-1.5)*.3;return {name:`Scene ${index+1} shot ${i+1}`,duration:3,eye:[x,1,8],target:[x,1,0],fov:50,cameraMode:'linear',endEye:[x+.6,1,8],endTarget:[x+.6,1,0]};})};}
function originalSequence(){return {schemaVersion:3,kind:'shot-studio-sequence',title:'Twenty original cuts with a gated stereo soundtrack',sources:Array.from({length:4},(_,i)=>({id:`source-${i}`,label:`Complete original scene ${i+1}`,film:originalFilm(i)})),clips:Array.from({length:20},(_,i)=>({id:`clip-${i}`,sourceId:`source-${i%4}`,shotIndex:SHOTS[i%4],label:`Original cut ${i+1}`,inTime:0,outTime:3}))};}
function ordinaryFilm(){return {schemaVersion:3,title:'Independent silent scene remains unchanged',light:.9,actors:[{name:'Amber still',x:-1,z:0,color:'#ff8000',action:'idle',performanceMode:'loop'},{name:'Blue still',x:1,z:0,color:'#0080ff',action:'idle',performanceMode:'loop'}],shots:[{name:'Silent original shot',duration:1,eye:[0,1,8],target:[0,1,0],fov:50,cameraMode:'static'}]};}
function wave(padded=false){
  const extra=padded?WAV_CAP-(44+FRAMES*4):0;assert(!extra||extra>=8&&extra%2===0);
  const bytes=Buffer.alloc(44+FRAMES*4+extra);bytes.write('RIFF');bytes.writeUInt32LE(bytes.length-8,4);bytes.write('WAVEfmt ',8);bytes.writeUInt32LE(16,16);bytes.writeUInt16LE(1,20);bytes.writeUInt16LE(2,22);bytes.writeUInt32LE(RATE,24);bytes.writeUInt32LE(RATE*4,28);bytes.writeUInt16LE(4,32);bytes.writeUInt16LE(16,34);
  let dataHeader=36;if(extra){bytes.write('JUNK',36);bytes.writeUInt32LE(extra-8,40);bytes.fill(0x51,44,36+extra);dataHeader+=extra;}
  bytes.write('data',dataHeader);bytes.writeUInt32LE(FRAMES*4,dataHeader+4);const offset=dataHeader+8;
  for(let frame=0;frame<FRAMES;frame++){const active=SOURCE_GATES.some(([a,b])=>frame>=a*RATE&&frame<b*RATE);if(active){bytes.writeInt16LE(Math.round(13107*Math.sin(2*Math.PI*440*frame/RATE)),offset+frame*4);bytes.writeInt16LE(Math.round(13107*Math.sin(2*Math.PI*880*frame/RATE)),offset+frame*4+2);}}
  return {bytes,offset};
}
function documentFor(wavBytes,{label='Original 440 / 880 Hz gated stereo',trim=true}={}){return {schemaVersion:1,kind:'shot-studio-sequence-document',sequence:originalSequence(),soundtrack:{label,asset:{sha256:SHA(wavBytes),bytes:wavBytes.length,sampleRate:RATE,channels:2,frameCount:FRAMES},inFrame:trim?10*RATE:0,outFrame:trim?50*RATE:FRAMES,startTime:trim?5:0,gain:trim?.5:1}};}
function frameArchive(document,wavBytes,metadataBytes=JSON_BYTES(document)){const h=Buffer.alloc(16);h.write('SHOTSEQ1');h.writeUInt32LE(metadataBytes.length,8);h.writeUInt32LE(wavBytes.length,12);return Buffer.concat([h,metadataBytes,wavBytes]);}
function parseArchive(bytes){assert.equal(bytes.subarray(0,8).toString(),'SHOTSEQ1');const m=bytes.readUInt32LE(8),w=bytes.readUInt32LE(12);assert(m>0&&m<=META_CAP);assert(w>0&&w<=WAV_CAP);assert.equal(bytes.length,16+m+w);assert(bytes.length<=ARCHIVE_CAP);const document=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes.subarray(16,16+m))),wav=bytes.subarray(16+m);assert.equal(document.soundtrack.asset.bytes,w);assert.equal(document.soundtrack.asset.sha256,SHA(wav));return {document,wav};}
function parseTake(bytes){assert.equal(bytes.subarray(0,8).toString(),'SHOTTAK1');const m=bytes.readUInt32LE(8),v=bytes.readUInt32LE(12);assert.equal(bytes.length,16+m+v);const manifest=JSON.parse(bytes.subarray(16,16+m));assert.equal(manifest.video.bytes,v);const video=bytes.subarray(16+m);assert.equal(manifest.video.sha256,SHA(video));return {manifest,video};}
function position(time){const clip=time>=60?19:Math.floor(time/3),local=time-clip*3,source=clip%4,sourceGlobal=SHOTS[source]*3+local,cameraX=(SHOTS[source]%4-1.5)*.3+.2*local;return {clip,local,source,sourceGlobal,cameraX,light:LIGHTS[source],movingX:-1.2+sourceGlobal/80};}
function patches(at,x,color){const rgb=[1,3,5].map(i=>Math.round(parseInt(color.slice(i,i+2),16)*SHADE*at.light)),points=[];for(const offset of[-.17,0,.17])for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++)points.push({x:Math.floor(480+FOCAL*(x+offset-at.cameraX)/7.84)+dx,y:Math.floor(270-FOCAL*.15/7.84)+dy});return {rgb,points};}
async function writeArtifact(dir,name,bytes){await writeFile(join(dir,name),bytes);return {name,bytes:bytes.length,sha256:SHA(bytes)};}
async function prepare(dir){
  await mkdir(dir,{recursive:false});const canonical=wave(),padded=wave(true),sequence=originalSequence();assert.equal(canonical.bytes.length,11520044);assert.equal(padded.bytes.length,WAV_CAP);assert(canonical.bytes.subarray(canonical.offset).equals(padded.bytes.subarray(padded.offset)));
  const document=documentFor(canonical.bytes),raw=JSON_BYTES(document);assert(raw.length<META_CAP);const exactMetadata=Buffer.concat([raw,Buffer.alloc(META_CAP-raw.length,32)]),files=[['maximum-sequence.json',JSON_BYTES(sequence)],['ordinary-scene.json',JSON_BYTES(ordinaryFilm())],['original-60s-stereo.wav',canonical.bytes],['exact-12MiB.wav',padded.bytes],['over-12MiB.wav',Buffer.concat([padded.bytes,Buffer.from([0])])],['exact-324KiB-metadata.shot-sequence',frameArchive(document,canonical.bytes,exactMetadata)],['over-324KiB-metadata.shot-sequence',frameArchive(document,canonical.bytes,Buffer.concat([exactMetadata,Buffer.from(' ')]))],['over-16MiB.shot-sequence',Buffer.alloc(ARCHIVE_CAP+1)]];
  const records=[];for(const [name,bytes]of files)records.push(await writeArtifact(dir,name,bytes));
  const oracle={schemaVersion:1,issue:124,status:'fixtures-only',source:'Independent literal fixtures, no producer imports',files:records,sequence,ordinaryScene:ordinaryFilm(),expectedTrimmedDocument:document,expectedCanonicalAudioDescriptor:document.soundtrack.asset,expectedPaddedAudioDescriptor:documentFor(padded.bytes).soundtrack.asset,audio:{rate:RATE,channels:2,frames:FRAMES,pcmDataBytes:FRAMES*4,canonicalWavBytes:canonical.bytes.length,canonicalDataOffset:canonical.offset,exactWavBytes:padded.bytes.length,paddedDataOffset:padded.offset,sourceGates:SOURCE_GATES,outputGates:OUTPUT_GATES,frequencies:[440,880],integerAmplitude:13107,trimFrames:[480000,2400000],sequenceStart:5,gain:.5,plateauRms:RMS,tolerances:GATES},video:{width:WIDTH,height:HEIGHT,targets:TARGETS,tolerances:GATES,focalPixels:FOCAL,frontShade:SHADE,expected:TARGETS.map(time=>{const at=position(time);return {time,...at,moving:patches(at,at.movingX,COLORS[at.source]),control:patches(at,1.2,'#00ff00')};})},bounds:{sources:4,shotsPerSource:20,actorsPerSource:2,cuesPerActor:32,clips:20,seconds:60,sourceBytes:sequence.sources.map(s=>JSON_BYTES(s.film).length),metadataBytes:raw.length,metadataBoundary:META_CAP,maxComponentSum:16+META_CAP+WAV_CAP,archiveCap:ARCHIVE_CAP},limitations:['Exact12MiB WAV has legal JUNK padding, not a larger PCM payload or worst-case decoding/RAM.','Metadata exact324KiB uses trailing JSON whitespace. No claim that canonical topology reaches that metadata cap.','16MiB+1 is an early whole-file refusal; valid component maxima total12,914,704B and cannot produce a valid exact16MiB artifact.','All256 performer cues are blocking; this graph does not claim simultaneous loop-mode or heterogeneous camera-axis maxima.','Forty landmark frames are independently pixel-checked; full video timestamps and all decoded PCM frames are inspected, not all video pixels.','The original constant-frequency PCM is synthetic test audio, not a microphone/physical-device claim.']};
  await writeFile(join(dir,'fixture-oracle.json'),JSON.stringify(oracle,null,2)+'\n');console.log(JSON.stringify({status:oracle.status,output:dir,files:records,bounds:oracle.bounds},null,2));
}
async function frozen(dir){const o=JSON.parse(await readFile(join(dir,'fixture-oracle.json'),'utf8'));assert.deepEqual(o.sequence,originalSequence());assert.deepEqual(o.audio.sourceGates,SOURCE_GATES);assert.deepEqual(o.audio.outputGates,OUTPUT_GATES);assert.equal(o.audio.plateauRms,RMS);assert.deepEqual(o.audio.tolerances,GATES);for(const f of o.files){const b=await readFile(join(dir,f.name));assert.equal(b.length,f.bytes);assert.equal(SHA(b),f.sha256);}return o;}
async function download(page,selector,path,timeout=15000){const p=page.waitForEvent('download',{timeout});await page.locator(selector).click();const file=await p;await saveDownload(file,page,selector,path);return readFile(path);}
async function processIds(context){const s=await context.browser().newBrowserCDPSession();try{return(await s.send('SystemInfo.getProcessInfo')).processInfo.filter(p=>p.type==='browser').map(p=>p.id);}finally{await s.detach();}}
async function stored(page){return page.evaluate(()=>new Promise((resolve,reject)=>{const r=indexedDB.open('shot-studio-sequence-documents',1);r.onerror=()=>reject(Error('Native read failed'));r.onsuccess=()=>{const db=r.result,tx=db.transaction('state','readonly'),g=tx.objectStore('state').get('sequence');tx.onabort=()=>{db.close();reject(Error('Native read aborted'));};tx.oncomplete=async()=>{db.close();try{const row=g.result;if(!row)return resolve(null);const b=row.archive;const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',b))].map(x=>x.toString(16).padStart(2,'0')).join('');resolve({schemaVersion:row.schemaVersion,revision:row.revision,bytes:b.byteLength,sha256:hash,legacyRaw:row.legacyRaw});}catch(e){reject(e);}};};}));}
async function capture(fixtureDir,dir,base){
  const oracle=await frozen(fixtureDir);await mkdir(dir,{recursive:false});const profile=join(dir,'profile'),errors=[],external=[],receipt={schemaVersion:1,issue:124,status:'running',fixtureOracleSha256:SHA(await readFile(join(fixtureDir,'fixture-oracle.json'))),fixtureFiles:oracle.files,checks:[],artifacts:[],browsers:[],browserEvents:[],limits:oracle.limitations};let context,page,stage='startup';const began=performance.now();
  const event=(index,event,extra={})=>receipt.browserEvents.push({index,event,stage,wallMs:performance.now()-began,...extra});
  const closeContext=async reason=>{if(context){event(receipt.browsers.length-1,'harness-close-request',{reason});await context.close();}};
  const save=()=>writeFile(join(dir,'verification.json'),JSON.stringify(receipt,null,2)+'\n');await save();
  const mount=async()=>{context=await chromium.launchPersistentContext(profile,{headless:true,acceptDownloads:true,viewport:{width:1440,height:1000},executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const startupPages=context.pages();page=await context.newPage();await Promise.all(startupPages.map(p=>p.close()));const mounted=context,index=receipt.browsers.length;mounted.on('close',()=>event(index,'context-close'));mounted.browser().on('disconnected',()=>event(index,'browser-disconnected'));page.on('close',()=>event(index,'page-close'));page.on('crash',()=>event(index,'page-crash'));page.on('dialog',d=>d.accept());page.on('pageerror',e=>{if(errors.length<20)errors.push(e.message);});page.on('request',r=>{if(/^https?:/.test(r.url())&&new URL(r.url()).origin!==new URL(base).origin&&external.length<20)external.push(r.url());});await page.goto(base);await page.bringToFront();await expect(page.locator('#sequence-open')).toBeEnabled();await expect(page.locator('#sequence-save-status')).toHaveText('Sequence saved in this browser');await expect(page.locator('#record-take')).toBeEnabled();receipt.browserVersion=context.browser().version();receipt.browsers.push(await processIds(context));};
  const input=async(selector,name,mimeType)=>{await expect(page.locator(selector)).toBeEnabled();await page.locator(selector).setInputFiles({name,mimeType,buffer:await readFile(join(fixtureDir,name))});};
  const backup=async name=>download(page,'#sequence-save',join(dir,name));
  const durable=async bytes=>{await expect(page.locator('#sequence-save-status')).toContainText(/saved/i);await expect.poll(async()=>{const r=await stored(page);return r&&r.sha256;},{timeout:15000}).toBe(SHA(bytes));const r=await stored(page);assert.equal(r.bytes,bytes.length);return r;};
  try{
    await mount();stage='ordinary scene and silent retained take';await input('#import','ordinary-scene.json','application/json');await expect(page.locator('#title')).toHaveValue(oracle.ordinaryScene.title);const sceneBefore=await download(page,'#save',join(dir,'ordinary-before.json'));assert.deepEqual(JSON.parse(sceneBefore),oracle.ordinaryScene);
    await page.locator('#take-name').fill('Original unrelated silent retained take');await page.locator('#record-take').click();await expect(page.locator('#take-list [data-take-id]')).toHaveCount(1,{timeout:20000});await expect(page.locator('#take-status')).toContainText(/saved/i);await page.locator('#take-list [data-take-id]').first().click();const takeBefore=await download(page,'#download-take',join(dir,'take-before.shot-take'));const take=parseTake(takeBefore);assert.deepEqual(take.manifest.film,oracle.ordinaryScene);await writeFile(join(dir,'ordinary-silent-take.webm'),take.video);
    stage='maximum legacy sequence and canonical PCM admission';await input('#sequence-open','maximum-sequence.json','application/json');await expect(page.locator('#sequence-clips [data-sequence-clip-id]')).toHaveCount(20);await expect(page.locator('#sequence-title')).toHaveValue(oracle.sequence.title);const legacy=await backup('legacy-inner-sequence.json');assert.deepEqual(JSON.parse(legacy),oracle.sequence);
    await input('#sequence-audio-file','original-60s-stereo.wav','audio/wav');await expect(page.locator('#sequence-audio-import')).toBeEnabled();await page.locator('#sequence-audio-import').click();await expect(page.locator('#sequence-audio-summary')).toContainText(oracle.expectedCanonicalAudioDescriptor.sha256);await expect(page.locator('#sequence-audio-apply')).toBeEnabled();
    const full=parseArchive(await backup('full-source-range.shot-sequence'));assert.deepEqual(full.document.sequence,oracle.sequence);assert(full.wav.equals(await readFile(join(fixtureDir,'original-60s-stereo.wav'))));
    await page.locator('#sequence-audio-label').fill(oracle.expectedTrimmedDocument.soundtrack.label);for(const [id,value]of [['in','10'],['out','50'],['start','5'],['gain','0.5']])await page.locator(`#sequence-audio-${id}`).fill(value);await page.locator('#sequence-audio-apply').click();
    const committed=await backup('trimmed-before-restart.shot-sequence'),parsed=parseArchive(committed);assert.deepEqual(parsed.document,oracle.expectedTrimmedDocument);assert(full.wav.equals(parsed.wav));receipt.saved=await durable(committed);
    stage='one adjustment history transaction';await page.locator('#sequence-undo').click();const undo=parseArchive(await backup('adjustment-undo.shot-sequence'));assert.deepEqual(undo.document,full.document);assert(full.wav.equals(undo.wav));await page.locator('#sequence-redo').click();assert(committed.equals(await backup('adjustment-redo.shot-sequence')));await durable(committed);
    stage='independent exact WAV container boundary';await page.locator('#sequence-audio-file').setInputFiles({name:'exact-12MiB.wav',mimeType:'audio/wav',buffer:await readFile(join(fixtureDir,'exact-12MiB.wav'))});await page.locator('#sequence-audio-import').click();await expect(page.locator('#sequence-audio-summary')).toContainText(oracle.expectedPaddedAudioDescriptor.sha256);const padded=parseArchive(await backup('padded-container.shot-sequence'));assert.equal(padded.wav.length,WAV_CAP);assert(padded.wav.equals(await readFile(join(fixtureDir,'exact-12MiB.wav'))));const paddedBackup=await backup('padded-container-complete.shot-sequence');await durable(paddedBackup);
    await page.locator('#sequence-audio-file').setInputFiles({name:'over-12MiB.wav',mimeType:'audio/wav',buffer:await readFile(join(fixtureDir,'over-12MiB.wav'))});if(await page.locator('#sequence-audio-import').isEnabled())await page.locator('#sequence-audio-import').click();await expect(page.locator('#sequence-status')).toContainText(/large|limit|12|invalid|bytes/i);assert(paddedBackup.equals(await backup('after-wav-refusal.shot-sequence')));await page.locator('#sequence-undo').click();assert(committed.equals(await backup('after-padded-undo.shot-sequence')));await durable(committed);
    stage='independent metadata and whole-file boundaries';await input('#sequence-open','exact-324KiB-metadata.shot-sequence','application/octet-stream');await expect.poll(async()=>{const b=await backup('metadata-admission.shot-sequence');return SHA(b);}).toBe(SHA(committed));await durable(committed);
    for(const name of ['over-324KiB-metadata.shot-sequence','over-16MiB.shot-sequence']){await input('#sequence-open',name,'application/octet-stream');await expect(page.locator('#sequence-status')).toContainText(/large|limit|invalid|metadata|archive|bytes|length/i);assert(committed.equals(await backup(`after-${name}`)));}
    receipt.checks.push('Four complete original sources, twenty full-shot clips,256 cues and sixty-second PCM retain exact film/WAV bytes. Trim/offset/gain is one Undo/Redo edit. Separate exact12MiB ancillary WAV and324KiB raw metadata admit; +1 refuses atomically;16MiB+1 whole-file refuses.');
    stage='whole-browser restart';await durable(committed);receipt.beforeRestart={bytes:committed.length,sha256:SHA(committed)};await closeContext('deliberate full-process restart');context=undefined;await mount();assert.notDeepEqual(receipt.browsers[0],receipt.browsers[1]);await expect(page.locator('#sequence-title')).toHaveValue(oracle.sequence.title);stage='restored complete archive download';const restored=await backup('trimmed-after-restart.shot-sequence');assert(committed.equals(restored));receipt.afterRestart=await durable(restored);assert(sceneBefore.equals(await download(page,'#save',join(dir,'ordinary-after-restart.json'))));await expect(page.locator('#take-list [data-take-id]')).toHaveCount(1);await page.locator('#take-list [data-take-id]').first().click();assert(takeBefore.equals(await download(page,'#download-take',join(dir,'take-after-restart.shot-take'))));
    stage='actual sixty-second audiovisual export';const pending=page.waitForEvent('download',{timeout:95000}),exportStart=performance.now();await page.locator('#sequence-export').click();const file=await pending;await file.saveAs(join(dir,'soundtrack-60s.webm'));receipt.recordAndDownloadWallMs=performance.now()-exportStart;const webm=await readFile(join(dir,'soundtrack-60s.webm'));assert(webm.length>0&&webm.length<=32*1024**2);assert(committed.equals(await backup('after-export.shot-sequence')));assert(sceneBefore.equals(await download(page,'#save',join(dir,'ordinary-after-export.json'))));assert(takeBefore.equals(await download(page,'#download-take',join(dir,'take-after-export.shot-take'))));
    stage='layout and final native persistence';await page.locator('#sequence-panel').scrollIntoViewIfNeeded();await page.screenshot({path:join(dir,'desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('#sequence-audio-label').scrollIntoViewIfNeeded();await page.screenshot({path:join(dir,'390px.png')});assert.deepEqual(errors,[]);assert.deepEqual(external,[]);receipt.pageErrors=errors;receipt.externalRequests=external;receipt.status='capture-passed-awaiting-independent-decode';receipt.captureWallMs=performance.now()-began;
    for(const name of ['trimmed-before-restart.shot-sequence','trimmed-after-restart.shot-sequence','soundtrack-60s.webm','ordinary-before.json','take-before.shot-take','ordinary-silent-take.webm','desktop.png','390px.png']){const b=await readFile(join(dir,name));receipt.artifacts.push({name,bytes:b.length,sha256:SHA(b)});}receipt.checks.push('Fresh persistent browser process restores byte-identical complete archive and unrelated original scene/silent retained take. Full authored-timestamp export leaves all three complete backups unchanged.');
  }catch(e){receipt.status='failed';receipt.failure={stage,name:e.name,message:e.message,stack:e.stack,pageClosed:page?.isClosed(),browserConnected:context?.browser()?.isConnected(),eventsBeforeCleanup:[...receipt.browserEvents],cause:e.cause?.message,diagnostics:e.diagnostics};event(receipt.browsers.length-1,'first-failure',{message:e.message});throw e;}finally{await closeContext('final cleanup');receipt.closedOwnedBrowsers=true;receipt.pageErrors=errors;receipt.externalRequests=external;await save();}
  console.log(JSON.stringify({status:receipt.status,output:dir,browsers:receipt.browsers,recordAndDownloadWallMs:receipt.recordAndDownloadWallMs,archive:receipt.beforeRestart},null,2));
}
function probe(path){return JSON.parse(execFileSync(process.env.FFPROBE_PATH||'ffprobe',['-v','error','-show_streams','-show_frames','-show_entries','stream=index,codec_type,codec_name,width,height,sample_rate,channels:frame=media_type,stream_index,best_effort_timestamp_time,nb_samples','-of','json',path],{encoding:'utf8',timeout:60000,maxBuffer:8*1024**2}));}
function decode(path,extra,maxBuffer){return execFileSync(process.env.FFMPEG_PATH||'ffmpeg',['-v','error','-threads','1','-i',path,...extra],{timeout:90000,maxBuffer});}
function rms(pcm,start,end,channel,audioFirst,origin){const a=Math.max(0,Math.ceil((start+origin-audioFirst)*RATE)),b=Math.min(pcm.length/8,Math.floor((end+origin-audioFirst)*RATE));assert(b>a);let sum=0;for(let i=a;i<b;i++){const value=pcm.readFloatLE(i*8+channel*4);assert(Number.isFinite(value));sum+=value*value;}return {rms:Math.sqrt(sum/(b-a)),firstFrame:a,frames:b-a};}
function frequency(pcm,start,end,channel,audioFirst,origin){const a=Math.ceil((start+origin-audioFirst)*RATE),b=Math.floor((end+origin-audioFirst)*RATE);assert(a>=0&&b<=pcm.length/8);let crossings=0,previous=pcm.readFloatLE(a*8+channel*4);for(let i=a+1;i<b;i++){const v=pcm.readFloatLE(i*8+channel*4);if(previous<=0&&v>0)crossings++;previous=v;}return crossings*RATE/(b-a);}
function toneAmplitude(pcm,start,end,channel,hz,audioFirst,origin){const a=Math.ceil((start+origin-audioFirst)*RATE),b=Math.floor((end+origin-audioFirst)*RATE);let re=0,im=0;for(let i=a;i<b;i++){const v=pcm.readFloatLE(i*8+channel*4),phase=2*Math.PI*hz*i/RATE;re+=v*Math.cos(phase);im+=v*Math.sin(phase);}return 2*Math.hypot(re,im)/(b-a);}
async function inspect(dir){
  const receipt=JSON.parse(await readFile(join(dir,'verification.json'),'utf8'));assert(['capture-passed-awaiting-independent-decode','passed','decode-failed'].includes(receipt.status));const path=join(dir,'soundtrack-60s.webm'),webm=await readFile(path);assert.equal(SHA(webm),receipt.artifacts.find(a=>a.name==='soundtrack-60s.webm').sha256);const began=performance.now();
  try{
    const p=probe(path);assert.equal(p.streams.length,2);const video=p.streams.find(s=>s.codec_type==='video'),audio=p.streams.find(s=>s.codec_type==='audio');assert(video&&audio);assert(['vp8','vp9'].includes(video.codec_name));assert.equal(video.width,WIDTH);assert.equal(video.height,HEIGHT);assert.equal(audio.codec_name,'opus');assert.equal(Number(audio.sample_rate),RATE);assert.equal(audio.channels,2);
    const vpts=p.frames.filter(f=>f.media_type==='video').map(f=>Number(f.best_effort_timestamp_time)),apts=p.frames.filter(f=>f.media_type==='audio').map(f=>Number(f.best_effort_timestamp_time));assert(vpts.length>=GATES.minVideoFrames&&apts.length>0);assert(vpts.every((v,i)=>Number.isFinite(v)&&(!i||v>=vpts[i-1])));assert(apts.every((v,i)=>Number.isFinite(v)&&(!i||v>=apts[i-1])));const origin=Math.min(vpts[0],apts[0]),times=vpts.map(t=>t-origin);assert(times.at(-1)>=GATES.minSpanSeconds&&times.at(-1)<=GATES.maxSpanSeconds);
    const pcm=decode(path,['-map',`0:${audio.index}`,'-ar','48000','-ac','2','-f','f32le','pipe:1'],32*1024**2);assert.equal(pcm.length%8,0);for(let i=0;i<pcm.length;i+=4)assert(Number.isFinite(pcm.readFloatLE(i)));assert(pcm.length/8>=59*RATE&&pcm.length/8<=62*RATE);
    const plateaus=[];for(const [a,b]of OUTPUT_GATES){const start=a+1,end=Math.min(a+2,b-1),channels=[];for(let c=0;c<2;c++){const power=rms(pcm,start,end,c,apts[0],origin),hz=frequency(pcm,start,end,c,apts[0],origin),wrong=toneAmplitude(pcm,start,end,c,c===0?880:440,apts[0],origin);assert(Math.abs(power.rms-RMS)<=RMS*GATES.rmsRelative,`RMS channel${c} ${start}: ${power.rms}, expected ${RMS}`);assert(Math.abs(hz-(c===0?440:880))<=GATES.pitchHz,`Frequency channel${c}: ${hz}`);assert(wrong<=GATES.wrongToneAmplitude,`Wrong-channel tone ${wrong}`);channels.push({...power,hz,wrongToneAmplitude:wrong});}plateaus.push({start,end,channels});}
    const quiet=[];for(const [a,b]of [[.2,4.85],[13.15,14.85],[23.15,24.85],[33.15,34.85],[45.15,59]])for(let c=0;c<2;c++){const value=rms(pcm,a,b,c,apts[0],origin);assert(value.rms<=GATES.quietRms,`Silence ${a}..${b} channel${c}: ${value.rms}`);quiet.push({start:a,end:b,channel:c,...value});}
    const markers=[];for(const [a,b]of OUTPUT_GATES)for(const [target,on]of [[a,true],[b,false]])for(let c=0;c<2;c++){
      const bins=[];for(let i=-30;i<=30;i++){const start=target+i*GATES.binSeconds;bins.push({start,rms:rms(pcm,start,start+GATES.binSeconds,c,apts[0],origin).rms});}
      const crossings=[];for(let i=1;i<bins.length;i++){const before=bins[i-1].rms>=GATES.markerRms,after=bins[i].rms>=GATES.markerRms;if(on?!before&&after:before&&!after)crossings.push(bins[i].start);}
      assert(crossings.length>0,`Missing ${on?'on':'off'} marker at${target} channel${c}`);const observed=crossings.reduce((best,t)=>Math.abs(t-target)<Math.abs(best-target)?t:best);assert(Math.abs(observed-target)<=GATES.markerSeconds,`Marker channel${c} target${target}, actual${observed}`);markers.push({target,on,channel:c,observed,deltaSeconds:observed-target});
    }
    const indices=TARGETS.map(target=>times.reduce((best,t,i)=>Math.abs(t-target)<Math.abs(times[best]-target)?i:best,0));assert.equal(new Set(indices).size,TARGETS.length);indices.forEach((i,j)=>assert(Math.abs(times[i]-TARGETS[j])<=GATES.videoPtsSeconds));const filter=`select=${indices.map(i=>`eq(n\\,${i})`).join('+')}`,pixels=decode(path,['-map',`0:${video.index}`,'-vf',filter,'-vsync','0','-threads','1','-f','rawvideo','-pix_fmt','rgb24','pipe:1'],70*1024**2),frameBytes=WIDTH*HEIGHT*3;assert.equal(pixels.length,frameBytes*TARGETS.length);
    const landmarks=indices.map((index,i)=>{const at=position(times[index]),readings={};for(const [name,x,color]of [['moving',at.movingX,COLORS[at.source]],['control',1.2,'#00ff00']]){const expected=patches(at,x,color);let matches=0;for(const point of expected.points){assert(point.x>=0&&point.x<WIDTH&&point.y>=0&&point.y<HEIGHT);const offset=i*frameBytes+(point.y*WIDTH+point.x)*3;const actual=[...pixels.subarray(offset,offset+3)];if(Math.max(...actual.map((v,c)=>Math.abs(v-expected.rgb[c])))<=GATES.pixelError)matches++;}assert(matches>=GATES.pixelMatches,`Torso ${name} clip${at.clip} ${matches}/27 points`);readings[name]={expectedRgb:expected.rgb,matches};}return {target:TARGETS[i],frame:index,pts:vpts[index],sharedTime:times[index],...at,pixels:readings};});
    const silent=probe(join(dir,'ordinary-silent-take.webm'));assert.equal(silent.streams.length,1);assert.equal(silent.streams[0].codec_type,'video');assert(['vp8','vp9'].includes(silent.streams[0].codec_name));
    receipt.inspection={status:'passed',wallMs:performance.now()-began,videoCodec:video.codec_name,audioCodec:audio.codec_name,decodedVideoFrames:vpts.length,decodedAudioFrames:pcm.length/8,decodedPcmBytes:pcm.length,sharedOrigin:origin,firstVideoPts:vpts[0],firstAudioPts:apts[0],lastSharedVideoTime:times.at(-1),plateaus,quiet,markers,landmarks,ordinaryTakeAudioStreams:0,method:'One common first-decoded-stream timestamp origin. Fixed gates/guards; no fitted audio/video offsets. Full finite PCM and frame PTS; forty original torso landmarks.'};receipt.status='passed';
  }catch(e){receipt.status='decode-failed';receipt.inspection={status:'failed',wallMs:performance.now()-began,name:e.name,message:e.message};throw e;}finally{receipt.inspectionAttempts??=[];receipt.inspectionAttempts.push(receipt.inspection);await writeFile(join(dir,'verification.json'),JSON.stringify(receipt,null,2)+'\n');}
  console.log(JSON.stringify({status:receipt.status,output:dir,inspectionWallMs:receipt.inspection.wallMs,videoFrames:receipt.inspection.decodedVideoFrames,audioFrames:receipt.inspection.decodedAudioFrames},null,2));
}
async function main(){if(!phase||!output)throw Error('Use --prepare --output NEW, --capture --fixtures PREPARED --output NEW --origin URL, or --inspect --output CAPTURED.');const dir=resolve(output);if(phase==='prepare')return prepare(dir);if(phase==='inspect')return inspect(dir);if(!fixtures||!option('--origin'))throw Error('Capture requires frozen --fixtures and root-owned --origin.');return capture(resolve(fixtures),dir,option('--origin'));}
main().catch(e=>{console.error(`${e.name}: ${e.message}`);process.exitCode=1;});
