// Original native maximum-film acceptance; no production domain/rendering imports.
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {mkdir,mkdtemp,readFile,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {chromium,expect} from '@playwright/test';

const sha=b=>createHash('sha256').update(b).digest('hex');
const encoded=value=>Buffer.from(JSON.stringify(value));
function maximumFilm(){return{schemaVersion:3,title:'Original minute of twenty cuts',light:1,
  actors:[{name:'Scarlet measured performer',color:'#ff0000',performanceMode:'blocking',cues:Array.from({length:32},(_,i)=>({time:i*1.875,x:-1.5+i/16,z:0,action:'idle',visible:true}))},
    {name:'Green position control',color:'#00ff00',performanceMode:'blocking',cues:Array.from({length:32},(_,i)=>({time:i*1.875,x:1.8,z:0,action:'idle',visible:true}))}],
  shots:Array.from({length:20},(_,i)=>({name:`Original cut ${i+1}`,duration:3,cameraMode:'static',eye:[(i%3-1)*.75,2.2,8],target:[0,1.15,0],fov:50}))};}
function parseArchive(bytes){assert.equal(bytes.subarray(0,8).toString('ascii'),'SHOTTAK1');const m=bytes.readUInt32LE(8),n=bytes.readUInt32LE(12);assert(m>0&&m<=81920);assert(n>0&&n<=33554432);assert.equal(bytes.length,16+m+n);const manifest=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes.subarray(16,16+m))),video=bytes.subarray(16+m);assert.equal(manifest.video.bytes,n);assert.equal(manifest.video.sha256,sha(video));return{manifest,video};}
function frameArchive(manifest,video){const m=encoded(manifest),h=Buffer.alloc(16);h.write('SHOTTAK1');h.writeUInt32LE(m.length,8);h.writeUInt32LE(video.length,12);return Buffer.concat([h,m,video]);}
async function download(page,path){const pending=page.waitForEvent('download');await page.locator('#download-take').click();const file=await pending;await file.saveAs(path);return readFile(path);}
async function processId(context){const session=await context.browser().newBrowserCDPSession();try{return(await session.send('SystemInfo.getProcessInfo')).processInfo.filter(p=>p.type==='browser').map(p=>p.id);}finally{await session.detach();}}
async function storedReceipt(page){return page.evaluate(async()=>{const row=await new Promise((resolve,reject)=>{const r=indexedDB.open('shot-studio-takes',1);r.onerror=()=>reject(Error('open'));r.onsuccess=()=>{const db=r.result,tx=db.transaction('state','readonly'),g=tx.objectStore('state').get('library');tx.oncomplete=()=>{db.close();resolve(g.result);};tx.onabort=()=>{db.close();reject(Error('abort'));};};});const records=[];for(const r of row.records){const b=await r.video.arrayBuffer(),hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',b))].map(x=>x.toString(16).padStart(2,'0')).join('');records.push({metadata:r.metadata,bytes:b.byteLength,sha256:hash});}return{revision:row.revision,records};});}
function project(point,camera){const norm=a=>{const n=Math.hypot(...a);return a.map(v=>v/n);},dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),f=norm(camera.target.map((v,i)=>v-camera.eye[i])),r=norm([-f[2],0,f[0]]),u=[r[1]*f[2]-r[2]*f[1],r[2]*f[0]-r[0]*f[2],r[0]*f[1]-r[1]*f[0]],v=point.map((x,i)=>x-camera.eye[i]),scale=540/(2*Math.tan(50*Math.PI/360)),z=dot(v,f);return{x:480+scale*dot(v,r)/z,y:270-scale*dot(v,u)/z};}
function costume(bytes,channel){let count=0,x=0,y=0;for(let j=0;j<540;j++)for(let i=0;i<960;i++){const at=(j*960+i)*3,v=bytes[at+channel];if(v>80&&[0,1,2].every(c=>c===channel||v>2*bytes[at+c])){count++;x+=i;y+=j;}}assert(count>400);return{count,x:x/count,y:y/count};}
function inspectVideo(path,film){
  const probe=JSON.parse(execFileSync('ffprobe',['-v','error','-show_streams','-show_frames','-show_entries','stream=codec_type,codec_name,width,height:frame=media_type,best_effort_timestamp_time','-of','json',path],{encoding:'utf8',timeout:60000,maxBuffer:3*1024**2}));
  assert.equal(probe.streams.length,1);assert.equal(probe.streams[0].codec_type,'video');assert.equal(probe.streams[0].width,960);assert.equal(probe.streams[0].height,540);assert(['vp8','vp9'].includes(probe.streams[0].codec_name));
  const pts=probe.frames.filter(f=>f.media_type==='video').map(f=>Number(f.best_effort_timestamp_time));assert(pts.length>600);assert(pts.every((v,i)=>Number.isFinite(v)&&(!i||v>=pts[i-1])));const times=pts.map(t=>t-pts[0]);assert(times.at(-1)>59&&times.at(-1)<62);
  const targets=[2,8,14,20,26,32,38,44,50,58],indices=targets.map(t=>times.reduce((best,v,i)=>Math.abs(v-t)<Math.abs(times[best]-t)?i:best,0));assert.equal(new Set(indices).size,10);indices.forEach((i,n)=>assert(Math.abs(times[i]-targets[n])<.2));
  const filter=`select=${indices.map(i=>`eq(n\\,${i})`).join('+')}`,pixels=execFileSync('ffmpeg',['-v','error','-threads','1','-i',path,'-vf',filter,'-vsync','0','-f','rawvideo','-pix_fmt','rgb24','pipe:1'],{timeout:60000,maxBuffer:20*1024**2}),size=960*540*3;assert.equal(pixels.length,size*10);
  const samples=indices.map((frame,i)=>{const t=times[frame],camera=film.shots[Math.floor(t/3)],rgb=pixels.subarray(i*size,(i+1)*size),red=costume(rgb,0),green=costume(rgb,1),expectedRed=project([-1.5+Math.min(t,58.125)/30,1.15,0],camera),expectedGreen=project([1.8,1.15,0],camera);for(const [got,want] of [[red,expectedRed],[green,expectedGreen]])for(const key of ['x','y'])assert(Math.abs(got[key]-want[key])<16,`${t} ${key} projection differs`);return{frame,pts:pts[frame],elapsed:t,red,green,expectedRed,expectedGreen};});
  return{codec:probe.streams[0].codec_name,decodedFrames:pts.length,spanSeconds:times.at(-1),projectionTolerancePixels:16,samples};
}
async function main(){
  const out=process.env.SHOT_TAKES_OUTPUT?resolve(process.env.SHOT_TAKES_OUTPUT):await mkdtemp(join(tmpdir(),'shot-retained-takes-'));if(process.env.SHOT_TAKES_OUTPUT)await mkdir(out,{recursive:false});
  const film=maximumFilm();assert.equal(film.shots.length,20);assert.equal(film.shots.reduce((s,x)=>s+x.duration,0),60);assert(film.actors.every(a=>a.cues.length===32));assert(encoded(film).length<65536);await writeFile(join(out,'maximum-film.json'),encoded(film));
  const evidence={schemaVersion:1,issue:86,status:'started',fixture:{shots:20,seconds:60,performers:2,cuesPerPerformer:32,canonicalBytes:encoded(film).length,sha256:sha(encoded(film))},checks:[],limits:['Original maximum-duration/count fixture; no producer model/math/renderer oracle imports.','Four slots use one actual sixty-second recording and three imported copies; this is not four separately recorded performances.','Actual encoded size is measured; this does not claim a32MiB encoded output or128MiB native library. Exact byte limits have separate domain tests.','Ten decoded landmark samples plus complete decoded frame timestamps; not pixel inspection of every frame.'],artifacts:[]};
  const save=()=>writeFile(join(out,'verification.json'),JSON.stringify(evidence,null,2)+'\n');await save();if(process.argv.includes('--fixtures-only')){console.log(out);return;}
  const base=process.env.SHOT_TAKES_BASE_URL;if(!base)throw Error('Set SHOT_TAKES_BASE_URL to a separately started normal local server.');const origin=new URL(base).origin,profile=join(out,'profile'),errors=[],external=[];let context,page;
  const mount=async()=>{context=await chromium.launchPersistentContext(profile,{headless:true,acceptDownloads:true,viewport:{width:1440,height:1000},...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});page=context.pages()[0];page.on('dialog',d=>d.accept());page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url())&&new URL(r.url()).origin!==origin)external.push(r.url());});await page.goto(base);await expect(page.locator('#take-status')).toContainText(/library read successfully/i,{timeout:15000});};
  try{
    await mount();evidence.browser=context.browser().version();evidence.firstProcess=await processId(context);await page.locator('#import').setInputFiles({name:'maximum-film.json',mimeType:'application/json',buffer:encoded(film)});await expect(page.locator('#title')).toHaveValue(film.title);
    await page.locator('#take-name').fill('Full minute — original maximum');const started=performance.now();await page.locator('#record-take').click();console.log('Recording actual sixty-second maximum film.');await expect(page.locator('#take-list [data-take-id]')).toHaveCount(1,{timeout:90000});evidence.recordAndSaveMs=performance.now()-started;await expect(page.locator('#take-status')).toContainText(/saved/i);
    const first=await download(page,join(out,'maximum-before-restart.shot-take')),parsed=parseArchive(first);assert.deepEqual(parsed.manifest.film,film);assert.equal(parsed.manifest.origin,'recorded-here');await writeFile(join(out,'maximum.webm'),parsed.video);evidence.video={bytes:parsed.video.length,sha256:sha(parsed.video),...inspectVideo(join(out,'maximum.webm'),film)};evidence.archive={bytes:first.length,sha256:sha(first)};await save();
    await page.locator('#play-take').click();await expect.poll(()=>page.locator('#take-video').evaluate(v=>v.currentTime),{timeout:10000}).toBeGreaterThan(.2);await page.locator('#stop-take').click();
    for(let i=2;i<=4;i++){const manifest=structuredClone(parsed.manifest);manifest.name=`Retained imported alternative ${i}`;await page.locator('#import-take').setInputFiles({name:`copy-${i}.shot-take`,mimeType:'application/octet-stream',buffer:frameArchive(manifest,parsed.video)});await expect(page.locator('#take-list [data-take-id]')).toHaveCount(i,{timeout:15000});}
    const before=await storedReceipt(page);assert.equal(before.records.length,4);assert(before.records.every(r=>r.sha256===sha(parsed.video)));for(const r of before.records)assert.deepEqual(r.metadata.film,film);assert.equal(new Set(before.records.map(r=>r.metadata.id)).size,4);evidence.libraryVideoBytes=before.records.reduce((s,r)=>s+r.bytes,0);evidence.checks.push('Four real Blob pairs admitted through native recording/import, each matching the independent film and exact recorded bytes.');
    await page.locator('#take-list [data-take-id]').first().click();await context.close();context=undefined;await mount();evidence.secondProcess=await processId(context);assert.notDeepEqual(evidence.firstProcess,evidence.secondProcess);await expect(page.locator('#take-list [data-take-id]')).toHaveCount(4);await page.locator('#take-list [data-take-id]').first().click();const second=await download(page,join(out,'maximum-after-restart.shot-take'));assert(first.equals(second));assert.deepEqual(await storedReceipt(page),before);evidence.checks.push('All four full-film pairs and revision survive complete persistent Chromium process restart; original backup bytes identical.');
    await page.locator('#take-list').scrollIntoViewIfNeeded();await page.screenshot({path:join(out,'desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:join(out,'390px.png'),fullPage:true});assert.deepEqual(errors,[]);assert.deepEqual(external,[]);evidence.pageErrors=errors;evidence.externalRequests=external;evidence.status='passed';
    for(const name of ['maximum-film.json','maximum-before-restart.shot-take','maximum-after-restart.shot-take','maximum.webm','desktop.png','390px.png']){const b=await readFile(join(out,name));evidence.artifacts.push({name,bytes:b.length,sha256:sha(b)});}await save();console.log(JSON.stringify({status:evidence.status,out,videoBytes:evidence.video.bytes,frames:evidence.video.decodedFrames,restartByteEqual:true}));
  }catch(error){evidence.status='failed';evidence.error=error.message;await save();throw error;}finally{await context?.close();}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
