import {test,expect} from '@playwright/test';
import {writeFile} from 'node:fs/promises';
import {originalProfile,WINNER_PNG,profileHash,exportProfile,savedProfile,durableProfile,projectOf,openOriginal,renameProfile,restoredTab,addWinner,protectProfile,transactionGate,waitGate,releaseGate,abortNextPut,holdStartupDecode,waitDecode,releaseDecode,holdFile,waitFile,releaseFile} from './saved-copy-fixtures.ts';

const protectedStatus=(page:import('@playwright/test').Page)=>expect(page.locator('#save-status')).toContainText(/protected|another tab|changed|conflict/i);

test('two genuine pages preserve the complete winning photos rating and look while stale memory raw forms and Undo stay usable',async({page,context},info)=>{
 await openOriginal(page);const stale=await context.newPage();await restoredTab(stale);const winner=await addWinner(page),winnerRow=await durableProfile(page);const piece=stale.locator('#piece-form [name=name]'),caption=stale.locator('#example-form [name=caption]'),notes=stale.locator('#look-list [data-look-id]').first().locator('[name=notes]');await piece.fill('Unsubmitted piece Ω');await caption.fill('Unsubmitted opinion');await notes.fill('Unsubmitted look notes\nremain exact');await notes.evaluate(node=>{const field=node as HTMLTextAreaElement;field.dataset.savedCopyIdentity='original-node';field.setSelectionRange(4,9);});await stale.locator('#piece-form input[type=file]').setInputFiles({name:'unsubmitted-original116.png',mimeType:'image/png',buffer:WINNER_PNG});await expect(stale.locator('#piece-photo-status')).toContainText('Photo ready');const preview=await stale.locator('#piece-photo-preview img').getAttribute('src');
 await renameProfile(stale,'Stale local profile116');await protectedStatus(stale);await expect(stale.locator('#replace-saved-copy')).toBeVisible();expect(await durableProfile(stale)).toEqual(winnerRow);const memory=await exportProfile(stale,info.outputPath('actual-stale-memory.json'));expect(memory).toEqual({...originalProfile(),title:'Stale local profile116'});expect(await exportProfile(page,info.outputPath('actual-complete-winner.json'))).toEqual(winner);
 await expect(piece).toHaveValue('Unsubmitted piece Ω');await expect(caption).toHaveValue('Unsubmitted opinion');await expect(notes).toHaveValue('Unsubmitted look notes\nremain exact');await expect(notes).toHaveAttribute('data-saved-copy-identity','original-node');expect(await stale.locator('#piece-photo-preview img').getAttribute('src')).toBe(preview);await stale.locator('#undo').click();expect(await exportProfile(stale)).toEqual(originalProfile());expect(await durableProfile(stale)).toEqual(winnerRow);await stale.locator('#redo').click();expect(await exportProfile(stale)).toEqual(memory);expect(await durableProfile(stale)).toEqual(winnerRow);
 await writeFile(info.outputPath('complete-conflict-receipt.json'),JSON.stringify({winnerPhotos:winner.photos.map(p=>({id:p.id,sha256:profileHash(Buffer.from(p.dataUrl.split(',')[1],'base64'))})),memoryPhotos:memory.photos.map(p=>({id:p.id,sha256:profileHash(Buffer.from(p.dataUrl.split(',')[1],'base64'))})),winnerPieces:winner.pieces.length,winnerExamples:winner.examples.length,winnerLooks:winner.looks.length,rawDraftsPreserved:true},null,2));await stale.close();
});

test('explicit Reload alone discards protected memory and raw drafts after consent and restores the complete winner',async({page,context})=>{
 const stale=await context.newPage(),state=await protectProfile(page,stale);await stale.locator('#piece-form [name=name]').fill('Discard only by consent');stale.once('dialog',dialog=>dialog.dismiss());await stale.locator('#retry-load').click();expect(await exportProfile(stale)).toEqual(state.memory);await expect(stale.locator('#piece-form [name=name]')).toHaveValue('Discard only by consent');expect(await durableProfile(stale)).toEqual(state.row);
 stale.once('dialog',dialog=>dialog.accept());await stale.locator('#retry-load').click();await expect(stale.locator('#profile-title')).toHaveValue(state.project.title);expect(await exportProfile(stale)).toEqual(state.project);await expect(stale.locator('#piece-form [name=name]')).toHaveValue('');await expect(stale.locator('#undo')).toBeDisabled();expect(await durableProfile(stale)).toEqual(state.row);await stale.close();
});

test('fresh replacement review names the winner and excludes unsubmitted photo and form drafts without clearing them',async({page,context})=>{
 const stale=await context.newPage(),state=await protectProfile(page,stale);await stale.locator('#piece-form [name=name]').fill('Retained raw piece');await stale.locator('#piece-form input[type=file]').setInputFiles({name:'retained-photo116.png',mimeType:'image/png',buffer:WINNER_PNG});await expect(stale.locator('#piece-photo-status')).toContainText('Photo ready');const photo=await stale.locator('#piece-photo-preview img').getAttribute('src');let event=stale.waitForEvent('dialog'),click=stale.locator('#replace-saved-copy').click(),dialog=await event;expect(dialog.message()).toContain(state.project.title);expect(dialog.message()).toMatch(/unapplied|unsubmitted|committed/i);await dialog.dismiss();await click;expect(await durableProfile(stale)).toEqual(state.row);await protectedStatus(stale);
 event=stale.waitForEvent('dialog');click=stale.locator('#replace-saved-copy').click();dialog=await event;await dialog.accept();await click;await savedProfile(stale);expect(projectOf(await durableProfile(stale))).toEqual(state.memory);expect(await exportProfile(stale)).toEqual(state.memory);await expect(stale.locator('#piece-form [name=name]')).toHaveValue('Retained raw piece');expect(await stale.locator('#piece-photo-preview img').getAttribute('src')).toBe(photo);await stale.close();
});

test('third writer after actual replacement confirmation invalidates review without overwriting either complete memory',async({page,context})=>{
 const stale=await context.newPage(),state=await protectProfile(page,stale),third=await context.newPage();await third.goto('/');await expect(third.locator('#profile-title')).toHaveValue(state.project.title);const event=stale.waitForEvent('dialog'),click=stale.locator('#replace-saved-copy').click(),dialog=await event;expect(dialog.message()).toContain(state.project.title);await renameProfile(third,'Third writer winner116');await savedProfile(third);const actualThird=await durableProfile(third);await dialog.accept();await click;await protectedStatus(stale);expect(await durableProfile(stale)).toEqual(actualThird);expect(await exportProfile(stale)).toEqual(state.memory);expect(projectOf(actualThird).photos).toEqual(state.project.photos);await third.close();await stale.close();
});

test('actual abort after replacement put success retains winner and protected memory until a new reviewed retry',async({page,context})=>{
 const stale=await context.newPage(),state=await protectProfile(page,stale);await abortNextPut(stale);stale.once('dialog',dialog=>dialog.accept());await stale.locator('#replace-saved-copy').click();await expect(stale.locator('#save-status')).toContainText(/failed|protected|memory|could not/i);await expect(stale.locator('#replace-saved-copy')).toBeEnabled();expect(await durableProfile(stale)).toEqual(state.row);expect(await exportProfile(stale)).toEqual(state.memory);stale.once('dialog',dialog=>dialog.accept());await stale.locator('#replace-saved-copy').click();await savedProfile(stale);expect(projectOf(await durableProfile(stale))).toEqual(state.memory);await stale.close();
});

test('changed-back raw input during actual startup JPEG decode cannot accept the saved copy or authorize overwrite',async({page,context})=>{
 await openOriginal(page);const originalRow=await durableProfile(page),late=await context.newPage();await holdStartupDecode(late);await late.goto('/');await waitDecode(late);const title=late.locator('#profile-title'),initial=await title.inputValue();await title.fill('A newer raw intent');await title.fill(initial);await title.evaluate(node=>{const field=node as HTMLInputElement;field.dataset.savedCopyIdentity='startup-raw';field.setSelectionRange(2,2);});await releaseDecode(late);await expect(late.locator('#save-status')).toContainText('Restore cancelled; current work was kept.');await expect(late.locator('#save-status')).toContainText('Your current profile is in memory.');await expect(late.locator('#retry-save')).toBeHidden();await expect(late.locator('#retry-load')).toBeEnabled();await expect(late.locator('#replace-saved-copy')).toBeEnabled();await expect(title).toBeFocused();await expect(title).toHaveValue(initial);await expect(title).toHaveAttribute('data-saved-copy-identity','startup-raw');expect(await title.evaluate(node=>(node as HTMLInputElement).selectionStart)).toBe(2);expect(await durableProfile(page)).toEqual(originalRow);await renameProfile(late,'Unaccepted local memory116');expect(await durableProfile(page)).toEqual(originalRow);await protectedStatus(late);late.once('dialog',dialog=>dialog.accept());await late.locator('#retry-load').click();await expect(title).toHaveValue(originalProfile().title);expect(await exportProfile(late)).toEqual(originalProfile());expect(await durableProfile(late)).toEqual(originalRow);await late.close();
});

test('a held genuine imported profile cannot publish after changed-back raw intent or grant protected save authority',async({page,context})=>{
 const stale=await context.newPage(),state=await protectProfile(page,stale);await holdFile(stale);const incoming=originalProfile();incoming.title='Old delayed imported profile';stale.once('dialog',dialog=>dialog.accept());await stale.locator('#profile-import').setInputFiles({name:'held-original116.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(incoming))});await waitFile(stale);const title=stale.locator('#profile-title');await title.fill('New raw intent');await title.fill(state.memory.title);await title.evaluate(node=>{const field=node as HTMLInputElement;field.dataset.savedCopyIdentity='import-raw';field.setSelectionRange(3,3);});await releaseFile(stale);await expect(stale.locator('#cancel-operation')).toBeHidden();await expect(title).toBeFocused();await expect(title).toHaveValue(state.memory.title);await expect(title).toHaveAttribute('data-saved-copy-identity','import-raw');expect(await exportProfile(stale)).toEqual(state.memory);expect(await durableProfile(stale)).toEqual(state.row);await protectedStatus(stale);await stale.close();
});

test('newer committed memory during a held genuine replacement stays unsaved until explicit Retry saving',async({page,context})=>{
 const stale=await context.newPage(),state=await protectProfile(page,stale);await transactionGate(stale,'readwrite');try{stale.once('dialog',dialog=>dialog.accept());await stale.locator('#replace-saved-copy').click();await waitGate(stale,true);await renameProfile(stale,'Newer memory after consent116');await releaseGate(stale);await expect(stale.locator('#retry-save')).toBeVisible();await expect(stale.locator('#save-status')).not.toHaveText('Saved on this device · export a profile for backup');expect(projectOf(await durableProfile(stale))).toEqual(state.memory);expect((await exportProfile(stale)).title).toBe('Newer memory after consent116');await stale.locator('#retry-save').click();await savedProfile(stale);const latest=await exportProfile(stale);expect(projectOf(await durableProfile(stale))).toEqual(latest);expect(latest.title).toBe('Newer memory after consent116');}finally{await stale.evaluate(()=>{const w=window as unknown as{style116Gate?:{release:boolean}};if(w.style116Gate)w.style116Gate.release=true;});await stale.close();}
});

test('controlled persisted return cannot let an older completed save mark newer raw fields Saved',async({page})=>{
 await openOriginal(page);await transactionGate(page,'readwrite');try{await renameProfile(page,'Captured pending save116');await waitGate(page,true);await page.evaluate(()=>{dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true}));dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true}));});const title=page.locator('#profile-title');await title.fill('Raw draft after return116');await title.evaluate(node=>{const field=node as HTMLInputElement;field.dataset.savedCopyIdentity='returned-raw';field.setSelectionRange(4,4);});await releaseGate(page);await expect(page.locator('#save-status')).not.toHaveText('Saved on this device · export a profile for backup');await expect(page.locator('#retry-load')).toBeVisible();expect(projectOf(await durableProfile(page)).title).toBe('Captured pending save116');await expect(title).toBeFocused();await expect(title).toHaveValue('Raw draft after return116');await expect(title).toHaveAttribute('data-saved-copy-identity','returned-raw');expect(await title.evaluate(node=>(node as HTMLInputElement).selectionStart)).toBe(4);expect((await exportProfile(page)).title).toBe('Captured pending save116');}finally{await page.evaluate(()=>{const w=window as unknown as{style116Gate?:{release:boolean}};if(w.style116Gate)w.style116Gate.release=true;});}
});

test('changed-back keyed look input while replacement review is pending suppresses consent and preserves caret',async({page,context})=>{
 const stale=await context.newPage(),state=await protectProfile(page,stale);let confirmations=0;stale.on('dialog',dialog=>{confirmations++;void dialog.dismiss();});await transactionGate(stale,'readonly');try{await stale.locator('#replace-saved-copy').click();await waitGate(stale);const notes=stale.locator('#look-list [data-look-id]').first().locator('[name=notes]'),original=await notes.inputValue();await notes.fill('Newer raw notes');await notes.fill(original);await notes.evaluate(node=>{const field=node as HTMLTextAreaElement;field.dataset.savedCopyIdentity='review-notes';field.setSelectionRange(3,7);});await releaseGate(stale);await expect(stale.locator('#replace-saved-copy')).toBeEnabled();expect(confirmations).toBe(0);await expect(notes).toBeFocused();await expect(notes).toHaveValue(original);await expect(notes).toHaveAttribute('data-saved-copy-identity','review-notes');expect(await notes.evaluate(node=>[(node as HTMLTextAreaElement).selectionStart,(node as HTMLTextAreaElement).selectionEnd])).toEqual([3,7]);expect(await durableProfile(stale)).toEqual(state.row);expect(await exportProfile(stale)).toEqual(state.memory);}finally{await stale.evaluate(()=>{const w=window as unknown as{style116Gate?:{release:boolean}};if(w.style116Gate)w.style116Gate.release=true;});await stale.close();}
});
