import {test,expect,type Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {PNG} from 'pngjs';
import {originalStrokeProject} from './stroke-edit-fixtures.ts';
import {nativeCurrent} from './native-saved-project.ts';
function fixture(){const p=originalStrokeProject(true);p.layers[0].cels=[{frame:0,strokes:[{color:'#ff0000',width:12,points:[{x:0,y:0}]}]},{frame:6,strokes:[{color:'#0000ff',width:12,points:[{x:80,y:0}]}]},{frame:10,strokes:[]}];return p;}
async function open(page:Page){const p=fixture();await page.goto('/');await expect(page.locator('#project-file')).toBeEnabled();await page.locator('#project-file').setInputFiles({name:'timing.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(p))});await expect.poll(()=>nativeCurrent(page)).toEqual(p);await page.locator('#layers button').filter({hasText:'Paint'}).click();return p;}
async function bytes(page:Page,id='#backup'){const pending=page.waitForEvent('download');await page.locator(id).click();return readFile((await (await pending).path())!);}
async function backup(page:Page){return JSON.parse((await bytes(page)).toString());}
async function enter(page:Page,raw:string|null){page.once('dialog',async dialog=>{expect(dialog.type()).toBe('prompt');expect(dialog.message()).toContain('pose keys');if(raw===null)await dialog.dismiss();else await dialog.accept(raw);});await page.getByRole('button',{name:'Move active drawing start',exact:true}).click();}
test('retime a complete exposure with actual frame entry, independent PNG timing, history and reload',async({page})=>{
 const p=await open(page);await expect(page.locator('#retime-cel')).toBeDisabled();await page.locator('#frame').fill('6');await enter(page,'9');await expect(page.locator('#frame')).toHaveValue('8');const expected=structuredClone(p);expected.layers[0].cels[1].frame=8;expect(await backup(page)).toEqual(expected);await page.locator('#frame').fill('6');const png=PNG.sync.read(await bytes(page,'#png'));const pixel=(x:number,y:number)=>Array.from(png.data.subarray((y*640+x)*4,(y*640+x)*4+4));expect(pixel(320,180)).toEqual([255,0,0,255]);expect(pixel(400,180)).toEqual([255,255,255,255]);expect(pixel(550,40)).toEqual([255,0,255,255]);await page.locator('#undo').click();expect(await backup(page)).toEqual(p);await page.locator('#redo').click();expect(await backup(page)).toEqual(expected);await expect.poll(()=>nativeCurrent(page)).toEqual(expected);await page.reload();expect(await backup(page)).toEqual(expected);
});
test('cancel, unchanged interior start and invalid/occupied entries preserve selection, complete graph and redo',async({page})=>{
 const p=await open(page);await page.locator('#frame').fill('6');await enter(page,'9');const future=await backup(page);await page.locator('#undo').click();await expect(page.locator('#frame')).toHaveValue('8');for(const raw of [null,'7','11','1','2.5','2e0','']){await enter(page,raw);await expect(page.locator('#frame')).toHaveValue('8');await expect(page.locator('#redo')).toBeEnabled();await expect(page.locator('#layer-name')).toHaveValue('Paint');expect(await backup(page)).toEqual(p);}await page.locator('#redo').click();expect(await backup(page)).toEqual(future);
});
test('retiming refuses other raw drafts before a dialog or pointer blur at 390px',async({page})=>{
 await page.setViewportSize({width:390,height:844});const p=await open(page);await page.locator('#frame').fill('6');let dialogs=0;page.on('dialog',dialog=>{dialogs++;void dialog.dismiss();});const pose=page.locator('#pose-x');await pose.fill('321');await page.locator('#retime-cel').click();await expect(pose).toHaveValue('321');await expect(pose).toBeFocused();expect(await nativeCurrent(page)).toEqual(p);expect(dialogs).toBe(0);await page.locator('#discard-pose-edits').click();await page.getByRole('button',{name:'Edit strokes',exact:true}).click();await page.getByRole('button',{name:'Stroke 1',exact:true}).click();await page.locator('#stroke-width').fill('');await page.locator('#retime-cel').focus();await page.locator('#retime-cel').press('Enter');expect(dialogs).toBe(0);await expect(page.locator('#stroke-width')).toHaveValue('');expect(await backup(page)).toEqual(p);await page.locator('#retime-cel').scrollIntoViewIfNeeded();await page.screenshot({path:test.info().outputPath('timing-mobile.png')});
});
test('pending genuine project-file loading locks authoring actions and cannot be retired by a forced retime click',async({page})=>{
 await page.addInitScript(()=>{const original=File.prototype.text;const gate={entered:false,release:()=>{}};Object.assign(window,{timingFileGate:gate});File.prototype.text=async function(){const text=await original.call(this);if(this.name==='held-timing.json'){gate.entered=true;await new Promise<void>(resolve=>{gate.release=resolve;});}return text;};});
 const p=await open(page);await page.locator('#frame').fill('6');const incoming=structuredClone(p);incoming.title='Loaded timing project';await page.locator('#project-file').setInputFiles({name:'held-timing.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(incoming))});await expect.poll(()=>page.evaluate(()=>(window as unknown as {timingFileGate:{entered:boolean}}).timingFileGate.entered)).toBe(true);for(const id of ['retime-cel','duplicate-layer','onion-enabled'])await expect(page.locator('#'+id)).toBeDisabled();let dialogs=0;page.on('dialog',d=>{dialogs++;void d.dismiss();});await page.locator('#retime-cel').dispatchEvent('click');await page.locator('#duplicate-layer').dispatchEvent('click');expect(dialogs).toBe(0);expect(await backup(page)).toEqual(p);await page.evaluate(()=>(window as unknown as {timingFileGate:{release():void}}).timingFileGate.release());await expect(page.locator('#project-title')).toHaveValue(incoming.title);await expect.poll(()=>nativeCurrent(page)).toEqual(incoming);expect(await backup(page)).toEqual(incoming);
});
test('unchanged start preserves a separately reviewed in-between proposal',async({page})=>{
 const p=await open(page);await page.locator('#frame').fill('8');await page.locator('#make-tween').click();await page.locator('#tween-start').selectOption('0');await page.locator('#tween-pair-order').click();await page.locator('#tween-review').click();await expect(page.locator('#tween-apply')).toBeEnabled();const types:string[]=[];page.on('dialog',d=>types.push(d.type()));await enter(page,'7');expect(types).toEqual(['prompt']);await expect(page.locator('#frame')).toHaveValue('8');await expect(page.locator('#tween-apply')).toBeEnabled();await expect(page.locator('#tween-preview-controls')).toBeVisible();expect(await nativeCurrent(page)).toEqual(p);
});
