import test from 'node:test';
import assert from 'node:assert/strict';
import {retimeDrawingCel,displayedDrawingFrame} from '../src/cel-timing.ts';
import {validateProject,MAX_JSON_BYTES,type DrawingLayer} from '../src/model.ts';
import {History} from '../src/history.ts';
import {originalStrokeProject} from './stroke-edit-fixtures.ts';
test('retiming preserves detached complete artwork and keys while crossing and sorting other boundaries',()=>{const p=validateProject(originalStrokeProject());(p.layers[0] as DrawingLayer).cels.push({frame:9,strokes:[]});const before=structuredClone(p),n=retimeDrawingCel(p,'paint',6,11),expected=structuredClone(p);(expected.layers[0] as DrawingLayer).cels[1].frame=11;(expected.layers[0] as DrawingLayer).cels.sort((a,b)=>a.frame-b.frame);assert.deepEqual(n,expected);assert.deepEqual(p,before);(n.layers[0] as DrawingLayer).cels[2].strokes[0].points[0].x=100;assert.deepEqual(p,before);assert.deepEqual((n.layers[0] as DrawingLayer).cels[0],(p.layers[0] as DrawingLayer).cels[0]);});
test('strict frame entry, first/occupied/missing targets and no-op history preserve the admitted source',()=>{const p=validateProject(originalStrokeProject()),before=structuredClone(p);assert.equal(displayedDrawingFrame(' 9 ',12),8);for(const count of [NaN,Infinity,0,12.5])assert.throws(()=>displayedDrawingFrame('3',count),/frame/i);for(const raw of ['','0','1','13','2.0','2e0','+2','02','NaN'])assert.throws(()=>displayedDrawingFrame(raw,12),/frame/i);for(const next of [0,12,2.5,NaN,Infinity])assert.throws(()=>retimeDrawingCel(p,'paint',6,next));for(const [layer,old] of [['missing',6],['image',6],['paint',0],['paint',5]] as const)assert.throws(()=>retimeDrawingCel(p,layer,old,8));const q=structuredClone(p);(q.layers[0] as DrawingLayer).cels.push({frame:8,strokes:[]});assert.throws(()=>retimeDrawingCel(q,'paint',6,8),/already|occupied/i);const h=new History(p);h.commit(retimeDrawingCel(p,'paint',6,8));h.undo();assert.equal(h.commit(retimeDrawingCel(p,'paint',6,6)),false);assert.equal(h.canRedo,true);assert.deepEqual(p,before);});
test('a longer boundary digit refuses at the exact canonical byte cap without changing the source',()=>{const p=validateProject(originalStrokeProject());p.layers.splice(1);const key=structuredClone(p.layers[0].keys[0]);p.layers.push(...Array.from({length:4},(_,i)=>({id:`image-${i}`,name:'Image',kind:'image' as const,keys:[key],image:{dataUrl:'data:image/png;base64,'+'A'.repeat(1552840),width:1,height:1}})));const gap=MAX_JSON_BYTES-new TextEncoder().encode(JSON.stringify(validateProject(p))).length;let remaining=Math.floor(gap/4)*4;for(const layer of p.layers)if(layer.kind==='image'){const add=Math.min(remaining,20000);layer.image.dataUrl+='A'.repeat(add);remaining-=add;}assert.equal(remaining,0);p.title+='x'.repeat(gap%4);const safe=validateProject(p),before=structuredClone(safe);assert.equal(new TextEncoder().encode(JSON.stringify(safe)).length,MAX_JSON_BYTES);assert.throws(()=>retimeDrawingCel(safe,'paint',6,10),/JSON.*limit/i);assert.deepEqual(safe,before);});
