import {test,expect,type Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {PNG} from 'pngjs';
import {originalStrokeProject,type OracleProject} from './stroke-edit-fixtures.ts';
import {nativeCurrent} from './native-saved-project.ts';
async function backup(page:Page){const pending=page.waitForEvent('download');await page.locator('#backup').click();return JSON.parse((await readFile((await (await pending).path())!)).toString()) as OracleProject;}
async function open(page:Page){const p=originalStrokeProject(true);await page.goto('/');await expect(page.locator('#project-file')).toBeEnabled();await page.locator('#project-file').setInputFiles({name:'motion.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(p))});await expect.poll(()=>nativeCurrent(page)).toEqual(p);await page.locator('#layers button').filter({hasText:'Paint'}).click();return p;}
test('duplicate complete animated drawing is independent through edited pose, native PNG, history and reload',async({page})=>{
 const p=await open(page);await page.locator('#frame').fill('6');await page.getByRole('button',{name:'Duplicate drawing layer',exact:true}).click();await expect(page.locator('#layer-name')).toHaveValue('Paint copy');await expect(page.locator('#frame')).toHaveValue('6');const copy=await backup(page),id=copy.layers[1].id;expect(id).not.toBe(p.layers[0].id);const expected=structuredClone(p);const cloned=structuredClone(p.layers[0]);cloned.id=id;cloned.name='Paint copy';expected.layers.splice(1,0,cloned);expect(copy).toEqual(expected);
 await page.locator('#frame').fill('0');await page.locator('#pose-y').fill('240');await page.locator('#set-key').click();expected.layers[1].keys[0].y=240;const edited=await backup(page);expect(edited).toEqual(expected);expect(edited.layers[0]).toEqual(p.layers[0]);
 const pending=page.waitForEvent('download');await page.locator('#png').click();const png=PNG.sync.read(await readFile((await (await pending).path())!));expect(Array.from(png.data.subarray((240*640+320)*4,(240*640+320)*4+4))).toEqual([0,0,255,255]);
 await page.locator('#undo').click();expect(await backup(page)).toEqual(copy);await page.locator('#undo').click();expect(await backup(page)).toEqual(p);await page.locator('#redo').click();await page.locator('#redo').click();expect(await backup(page)).toEqual(edited);await expect.poll(()=>nativeCurrent(page)).toEqual(edited);await page.reload();expect(await backup(page)).toEqual(edited);
});
test('valid preblur pose and raw stroke appearance drafts are protected at 390px',async({page})=>{
 await page.setViewportSize({width:390,height:844});const p=await open(page);const pose=page.locator('#pose-x');await pose.fill('321');await page.locator('#duplicate-layer').click();await expect(pose).toHaveValue('321');await expect(pose).toBeFocused();expect(await nativeCurrent(page)).toEqual(p);await page.locator('#discard-pose-edits').click();await page.getByRole('button',{name:'Edit strokes',exact:true}).click();await page.getByRole('button',{name:'Stroke 1',exact:true}).click();await page.locator('#stroke-width').fill('');await page.locator('#duplicate-layer').click();await expect(page.locator('#stroke-width')).toHaveValue('');expect(await backup(page)).toEqual(p);
 await page.locator('#duplicate-layer').focus();await page.locator('#duplicate-layer').press('Enter');await expect(page.locator('#stroke-width')).toHaveValue('');expect(await backup(page)).toEqual(p);
 await page.locator('#duplicate-layer').scrollIntoViewIfNeeded();await page.screenshot({path:test.info().outputPath('drawing-copy-mobile.png')});
});
test('image selection is explicitly unsupported; full drawing quota refuses without changing selection or redo',async({page})=>{
 const p=await open(page);await page.locator('#layers button').filter({hasText:'Original magenta image'}).click();await expect(page.locator('#duplicate-layer')).toBeDisabled();await page.locator('#layers button').filter({hasText:'Paint'}).click();
 const crowded=structuredClone(p);crowded.layers[0].cels=[{frame:0,strokes:Array.from({length:51},()=>({color:'#010203',width:1,points:[{x:0,y:0}]}))}];await page.locator('#project-file').setInputFiles({name:'crowded.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(crowded))});await expect.poll(()=>nativeCurrent(page)).toEqual(crowded);await page.locator('#layers button').filter({hasText:'Paint'}).click();await page.locator('#layer-name').fill('Renamed');await page.locator('#undo').click();await expect(page.locator('#redo')).toBeEnabled();await page.locator('#duplicate-layer').click();await expect(page.locator('#message')).toContainText('100 strokes');await expect(page.locator('#layer-name')).toHaveValue('Paint');expect(await backup(page)).toEqual(crowded);await expect(page.locator('#redo')).toBeEnabled();await page.locator('#redo').click();crowded.layers[0].name='Renamed';expect(await backup(page)).toEqual(crowded);
});
