import {test,expect,type Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {PNG} from 'pngjs';
import {originalStrokeProject} from './stroke-edit-fixtures.ts';
import {nativeCurrent} from './native-saved-project.ts';
function fixture(){const p=originalStrokeProject(true);p.layers[0].cels=[{frame:0,strokes:[{color:'#ff0000',width:12,points:[{x:-80,y:0}]}]},{frame:4,strokes:[]},{frame:8,strokes:[{color:'#0000ff',width:12,points:[{x:80,y:0}]}]}];return p;}
async function open(page:Page,p=fixture()){await page.goto('/');await expect(page.locator('#project-file')).toBeEnabled();await page.locator('#project-file').setInputFiles({name:'guides.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(p))});await expect.poll(()=>nativeCurrent(page)).toEqual(p);await page.locator('#layers button').filter({hasText:'Paint'}).click();return p;}
async function bytes(page:Page,id:string){const pending=page.waitForEvent('download');await page.locator(id).click();return readFile((await (await pending).path())!);}
async function pixel(page:Page,id:string,x:number,y:number){return page.locator(id).evaluate((node,{x,y})=>Array.from((node as HTMLCanvasElement).getContext('2d')!.getImageData(x,y,1,1).data),{x,y});}
async function clear(page:Page){await expect.poll(()=>page.locator('#onion-overlay').evaluate(node=>!(node as HTMLCanvasElement).getContext('2d')!.getImageData(0,0,640,360).data.some(Boolean))).toBe(true);}
test('actual neighboring guide pixels never enter complete project, committed stage or native PNG and reload resets the session toggle',async({page})=>{
 const p=await open(page);await page.locator('#frame').fill('4');const pngBefore=PNG.sync.read(await bytes(page,'#png'));await expect(page.locator('#onion-enabled')).not.toBeChecked();await page.getByLabel('Show neighboring drawings',{exact:true}).check();await expect(page.locator('#onion-status')).toContainText('Previous: drawing from frame 1');await expect(page.locator('#onion-status')).toContainText('Next: drawing from frame 9');
 for(const [x,expected] of [[240,[8,127,140,64]],[400,[196,61,100,64]]] as const){const actual=await pixel(page,'#onion-overlay',x,180);for(let i=0;i<4;i++)expect(Math.abs(actual[i]-expected[i])).toBeLessThanOrEqual(i===3?0:2);expect(await pixel(page,'#stage',x,180)).toEqual([255,255,255,255]);}
 expect(JSON.parse((await bytes(page,'#backup')).toString())).toEqual(p);const pngAfter=PNG.sync.read(await bytes(page,'#png'));expect(pngAfter.data).toEqual(pngBefore.data);expect(await nativeCurrent(page)).toEqual(p);await expect(page.locator('#undo')).toBeDisabled();await page.reload();await expect(page.locator('#onion-enabled')).not.toBeChecked();await clear(page);expect(JSON.parse((await bytes(page,'#backup')).toString())).toEqual(p);
});
test('blank boundaries, image selection, history and real playback refresh guide ownership without wrapping',async({page})=>{
 const p=await open(page);await page.locator('#onion-enabled').check();await clear(page);await expect(page.locator('#onion-status')).toContainText('Next: blank drawing from frame 5');await page.locator('#frame').fill('4');expect((await pixel(page,'#onion-overlay',240,180))[3]).toBe(64);await page.locator('#frame').fill('8');await clear(page);await expect(page.locator('#onion-status')).toContainText('Previous: blank drawing from frame 5');await page.locator('#layers button').filter({hasText:'Original magenta image'}).click();await expect(page.locator('#onion-enabled')).toBeDisabled();await clear(page);await page.locator('#layers button').filter({hasText:'Paint'}).click();await page.locator('#frame').fill('4');await page.locator('#loop').check();await page.locator('#play').click();await expect(page.locator('#play')).toHaveText('Pause animation');await clear(page);await expect(page.locator('#onion-status')).toContainText('paused during playback');await page.locator('#play').click();await expect(page.locator('#onion-status')).not.toContainText('paused during playback');await page.locator('#frame').fill('4');expect((await pixel(page,'#onion-overlay',400,180))[3]).toBe(64);
 await page.locator('#frame').fill('6');await page.locator('#add-blank-cel').click();expect((await pixel(page,'#onion-overlay',240,180))[3]).toBe(0);expect((await pixel(page,'#onion-overlay',400,180))[3]).toBe(64);await page.locator('#undo').click();await expect.poll(()=>nativeCurrent(page)).toEqual(p);expect((await pixel(page,'#onion-overlay',240,180))[3]).toBe(64);await page.locator('#redo').click();expect((await pixel(page,'#onion-overlay',240,180))[3]).toBe(0);await page.locator('#onion-enabled').uncheck();await clear(page);
});
test('pointer preblur and keyboard toggles protect raw pose and stroke drafts on a narrow screen',async({page})=>{
 await page.setViewportSize({width:390,height:844});const p=await open(page);const pose=page.locator('#pose-x');await pose.fill('321');await page.getByText('Show neighboring drawings',{exact:true}).click();await expect(pose).toHaveValue('321');await expect(pose).toBeFocused();await expect(page.locator('#onion-enabled')).not.toBeChecked();expect(await nativeCurrent(page)).toEqual(p);await page.locator('#discard-pose-edits').click();await page.locator('#onion-enabled').check();await page.getByRole('button',{name:'Edit strokes',exact:true}).click();await page.getByRole('button',{name:'Stroke 1',exact:true}).click();await page.locator('#stroke-width').fill('');await page.locator('#onion-enabled').click();await expect(page.locator('#onion-enabled')).toBeChecked();await page.locator('#onion-enabled').focus();await page.locator('#onion-enabled').press('Space');await expect(page.locator('#onion-enabled')).toBeChecked();await expect(page.locator('#stroke-width')).toHaveValue('');expect(JSON.parse((await bytes(page,'#backup')).toString())).toEqual(p);await page.locator('#onion-enabled').scrollIntoViewIfNeeded();await page.screenshot({path:test.info().outputPath('onion-mobile.png')});
});

test('rotated scaled translucent guides follow the current pose and gestures lock their control',async({page})=>{
 const p=fixture();Object.assign(p.layers[0].keys[0],{rotation:90,scale:.5,opacity:.5});await open(page,p);await page.locator('#frame').fill('4');await page.locator('#onion-enabled').check();expect((await pixel(page,'#onion-overlay',320,140))[3]).toBe(32);expect((await pixel(page,'#onion-overlay',320,220))[3]).toBe(32);expect(await pixel(page,'#onion-overlay',240,180)).toEqual([0,0,0,0]);
 await page.locator('#stage').scrollIntoViewIfNeeded();const box=(await page.locator('#stage').boundingBox())!;await page.mouse.move(box.x+box.width*.5,box.y+box.height*.5);await page.mouse.down();await expect(page.locator('#onion-enabled')).toBeDisabled();await page.keyboard.press('Escape');await page.mouse.up();await expect(page.locator('#onion-enabled')).toBeEnabled();expect(JSON.parse((await bytes(page,'#backup')).toString())).toEqual(p);
});

test('editing a raw pose pauses playback and immediately restores committed guides',async({page})=>{
 const p=fixture();p.frameCount=96;p.layers[0].cels[2].frame=80;await open(page,p);await page.locator('#frame').fill('4');await page.locator('#onion-enabled').check();await page.locator('#play').click();await expect(page.locator('#onion-status')).toContainText('paused during playback');await clear(page);await page.locator('#pose-x').fill('321');await expect(page.locator('#play')).toHaveText('Play animation');await expect(page.locator('#onion-status')).not.toContainText('paused during playback');expect((await pixel(page,'#onion-overlay',240,180))[3]).toBe(64);await expect(page.locator('#pose-x')).toHaveValue('321');await expect(page.locator('#pose-x')).toBeFocused();await expect(page.locator('#undo')).toBeDisabled();expect(await nativeCurrent(page)).toEqual(p);
});
