import test from 'node:test';
import assert from 'node:assert/strict';
import {neighborDrawings} from '../src/onion-skin.ts';
import {originalStrokeProject} from './stroke-edit-fixtures.ts';
function fixture(){const p=originalStrokeProject();p.layers[0].cels=[{frame:0,strokes:[{color:'#ff0000',width:12,points:[{x:-80,y:0}]}]},{frame:4,strokes:[]},{frame:8,strokes:[{color:'#0000ff',width:12,points:[{x:80,y:0}]}]}];p.layers[0].keys=[{frame:0,x:320,y:180,scale:1,rotation:0,opacity:1,easing:'linear'},{frame:8,x:400,y:220,scale:2,rotation:90,opacity:.5,easing:'linear'}];return p;}
test('immediate exposure neighbors preserve blanks and use only current-frame pose',()=>{const p=fixture();const before=structuredClone(p),n=neighborDrawings(p,'paint',6);assert.deepEqual(n.map(x=>[x.side,x.frame]),[['previous',0],['next',8]]);for(const item of n)assert.deepEqual(item.pose,{x:380,y:210,scale:1.75,rotation:67.5,opacity:.625});assert.deepEqual(neighborDrawings(p,'paint',2).map(x=>[x.side,x.frame,x.strokes]),[['next',4,[]]]);assert.deepEqual(neighborDrawings(p,'paint',11).map(x=>[x.side,x.frame,x.strokes]),[['previous',4,[]]]);assert.deepEqual(p,before);});
test('neighbor plans are detached and image/missing/single-exposure selections have no guides',()=>{const p=fixture(),n=neighborDrawings(p,'paint',6);n[0].strokes[0].points[0].x=0;n[0].pose.x=0;assert.equal(p.layers[0].cels[0].strokes[0].points[0].x,-80);assert.equal(p.layers[0].keys[0].x,320);assert.deepEqual(neighborDrawings(p,'image',0),[]);assert.deepEqual(neighborDrawings(p,'missing',0),[]);assert.deepEqual(neighborDrawings(p,'control',0),[]);});
test('out-of-timeline and fractional/nonfinite frames refuse',()=>{const p=fixture();for(const frame of [-1,12,.5,NaN,Infinity])assert.throws(()=>neighborDrawings(p,'paint',frame),/frame/i);});
test('full retained artwork budget is represented without silently dropping adjacent paths',()=>{const p=fixture();p.layers[0].cels[0].strokes=Array.from({length:50},()=>({color:'#010203',width:1,points:Array.from({length:100},(_,x)=>({x,y:0}))}));p.layers[0].cels[2].strokes=structuredClone(p.layers[0].cels[0].strokes);p.layers.splice(1);const n=neighborDrawings(p,'paint',4);assert.equal(n.reduce((total,guide)=>total+guide.strokes.length,0),100);assert.equal(n.reduce((total,guide)=>total+guide.strokes.reduce((sum,stroke)=>sum+stroke.points.length,0),0),10000);});
