import {test,expect,type Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {PNG} from 'pngjs';
import {originalStrokeProject,type OracleProject} from './stroke-edit-fixtures.ts';
import {nativeCurrent} from './native-saved-project.ts';
async function bytes(page:Page,id='#backup'){const pending=page.waitForEvent('download');await page.locator(id).click();return readFile((await (await pending).path())!);}
async function backup(page:Page){return JSON.parse((await bytes(page)).toString()) as OracleProject;}
async function open(page:Page){const p=originalStrokeProject(true);p.layers[0].cels[0].strokes[0].points=[{x:-60,y:-30},{x:-60,y:30},{x:60,y:30}];await page.goto('/');await expect(page.locator('#project-file')).toBeEnabled();await page.locator('#project-file').setInputFiles({name:'artwork.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(p))});await expect.poll(()=>nativeCurrent(page)).toEqual(p);await page.locator('#layers button').filter({hasText:'Paint'}).click();await page.getByRole('button',{name:'Edit strokes',exact:true}).click();await page.getByRole('button',{name:'Stroke 1',exact:true}).click();return p;}
test('detached duplicate and mirrors preserve independent exposure and real PNG through history and reload',async({page})=>{
 const p=await open(page);await page.getByRole('button',{name:'Duplicate selected stroke',exact:true}).click();const copy=await backup(page),expected=structuredClone(p);expected.layers[0].cels[0].strokes.splice(1,0,structuredClone(expected.layers[0].cels[0].strokes[0]));expect(copy).toEqual(expected);await expect(page.getByRole('button',{name:'Stroke 2',exact:true})).toHaveAttribute('aria-pressed','true');
 await page.getByRole('button',{name:'Mirror stroke horizontally',exact:true}).click();await page.getByRole('button',{name:'Mirror stroke vertically',exact:true}).click();expected.layers[0].cels[0].strokes[1].points=[{x:60,y:30},{x:60,y:-30},{x:-60,y:-30}];const after=await backup(page);expect(after).toEqual(expected);
 const png=PNG.sync.read(await bytes(page,'#png'));const pixel=(x:number,y:number)=>Array.from(png.data.subarray((y*640+x)*4,(y*640+x)*4+4));expect(pixel(380,180)).toEqual([255,0,0,255]);expect(pixel(550,40)).toEqual([255,0,255,255]);
 await page.locator('#undo').click();await page.locator('#undo').click();expect(await backup(page)).toEqual(copy);await page.locator('#undo').click();expect(await backup(page)).toEqual(p);for(let i=0;i<3;i++)await page.locator('#redo').click();expect(await backup(page)).toEqual(after);await expect.poll(()=>nativeCurrent(page)).toEqual(after);await page.reload();expect(await backup(page)).toEqual(after);
});
test('appearance and other pose drafts refuse reusable actions without publishing raw work at 390px',async({page})=>{
 await page.setViewportSize({width:390,height:844});const p=await open(page);await page.locator('#stroke-width').fill('7e-');for(const id of ['stroke-duplicate','stroke-mirror-x','stroke-mirror-y']){await expect(page.locator('#'+id)).toBeDisabled();await page.locator('#'+id).dispatchEvent('click');}await expect(page.locator('#stroke-width')).toHaveValue('7e-');expect(await backup(page)).toEqual(p);await page.locator('#stroke-discard').click();const field=page.locator('#pose-x');await field.fill('321');await page.locator('#stroke-duplicate').click();await expect(field).toHaveValue('321');await expect(field).toBeFocused();expect(await nativeCurrent(page)).toEqual(p);await page.locator('#stroke-editor').scrollIntoViewIfNeeded();await page.screenshot({path:test.info().outputPath('stroke-reuse-mobile.png')});
});
test('unchanged single-point mirrors retain the redo branch',async({page})=>{
 const p=await open(page);await page.locator('#stroke-duplicate').click();const future=await backup(page);await page.locator('#undo').click();await page.getByRole('button',{name:'Stroke 3',exact:true}).click();await page.locator('#stroke-mirror-x').click();await page.locator('#stroke-mirror-y').click();expect(await backup(page)).toEqual(p);await expect(page.locator('#redo')).toBeEnabled();await page.locator('#redo').click();expect(await backup(page)).toEqual(future);
});
