import { test, expect, type Page } from '@playwright/test';
import { writeFile } from 'node:fs/promises';
import { originalBacking, open, backup, microphone, probe, awaitElapsed, releasePermission, released, assertBacking, assertMicrophone, stored, exportBytes, assertExports, type CompleteBackup } from './backed-recording-fixtures.ts';

async function begin(page:Page){const requests=(await probe(page)).requests;page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Record with backing',exact:true}).click();await expect.poll(async()=>(await probe(page)).requests).toBe(requests+1);}
async function finish(page:Page,seconds=2.4){await awaitElapsed(page,seconds);await expect(page.getByRole('button',{name:'Finish recording',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Finish recording',exact:true}).click();await released(page);await expect(page.locator('#notice')).toContainText('Detected',{timeout:20000});await expect(page.getByRole('button',{name:'Record with backing',exact:true})).toBeEnabled();}
function retainedOthers(before:CompleteBackup,after:CompleteBackup){expect(after.document.composition.tracks.slice(1)).toEqual(before.document.composition.tracks.slice(1));expect(after.document.composition.title).toBe(before.document.composition.title);expect(after.document.composition.tempo).toBe(240);for(const binding of before.document.references.filter(r=>r.trackId!=='target')){expect(after.document.references.find(r=>r.trackId===binding.trackId)).toEqual(binding);expect(after.assets.find(a=>a.id===binding.assetId)).toEqual(before.assets.find(a=>a.id===binding.assetId));}}

test('selected-track backing uses actual frozen audible mix and one successful recording edit retains all other reference bytes',async({page},info)=>{
 test.setTimeout(45000);await microphone(page);await open(page);const before=await backup(page);await begin(page);await expect(page.locator('#capture-state')).toContainText(/count.?in.*[1-4].*4/i);await finish(page);
 const observed=await probe(page),backing=observed.sources.filter(s=>s.frames===441000);expect(backing).toHaveLength(1);expect(backing[0].sampleRate).toBe(22050);const maxError=assertBacking(backing[0].samples),clicks=observed.sources.filter(s=>s.frames!==441000);expect(clicks).toHaveLength(4);for(let i=0;i<4;i++)expect(Math.abs(clicks[i].when-(clicks[0].when+i*.25))).toBeLessThanOrEqual(1/backing[0].contextRate);expect(Math.abs(backing[0].when-clicks[0].when-1)).toBeLessThanOrEqual(1/backing[0].contextRate);
 const after=await backup(page);retainedOthers(before,after);const binding=after.document.references.find(r=>r.trackId==='target')!,asset=after.assets.find(a=>a.id===binding.assetId)!;expect(binding.assetId).not.toBe(before.document.references.find(r=>r.trackId==='target')!.assetId);const media=assertMicrophone(asset),notes=after.document.composition.tracks[0].notes;expect(notes.length).toBeGreaterThan(0);expect(notes.every(note=>note.pitch===69)).toBe(true);expect(notes[0].start).toBe(0);expect(Math.abs(notes.at(-1)!.start+notes.at(-1)!.duration-asset.frameCount/22050*4)).toBeLessThanOrEqual(.5);
 await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await backup(page)).toEqual(before);await page.getByRole('button',{name:'Redo',exact:true}).click();expect(await backup(page)).toEqual(after);await expect(page.locator('#save-status')).toHaveText('Saved in this browser');const durable=await stored(page);await page.reload();await expect(page.getByLabel('Project title')).toHaveValue(before.document.composition.title);expect(await backup(page)).toEqual(after);expect(await stored(page)).toEqual(durable);
 const midi=await exportBytes(page,'Export MIDI'),wav=await exportBytes(page,'Export WAV');await writeFile(info.outputPath('actual-backed.mid'),midi);await writeFile(info.outputPath('actual-backed.wav'),wav);const exports=assertExports(midi,wav,after);
 await writeFile(info.outputPath('actual-backed-project.melody.json'),JSON.stringify(after));await writeFile(info.outputPath('actual-microphone.pcm'),Buffer.from(asset.pcmBase64,'base64'));await writeFile(info.outputPath('native-audio-receipt.json'),JSON.stringify({backingMaxAbsoluteError:maxError,scheduledClicks:4,countInSeconds:1,selectedTrackExcluded:true,otherReferencesExact:true,oneUndoRedo:true,...media,exports,physicalLatencyMeasured:false},null,2));
});

test('Finish stays disabled through count-in and Cancel preserves complete project, history and durable PCM',async({page})=>{
 await microphone(page);await open(page);const before=await backup(page),durable=await stored(page),undo=await page.getByRole('button',{name:'Undo',exact:true}).isEnabled(),redo=await page.getByRole('button',{name:'Redo',exact:true}).isEnabled();await begin(page);await expect(page.locator('#capture-state')).toContainText(/count.?in/i);await expect(page.getByRole('button',{name:'Finish recording',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Cancel',exact:true}).click();await released(page);expect(await backup(page)).toEqual(before);expect(await stored(page)).toEqual(durable);expect(await page.getByRole('button',{name:'Undo',exact:true}).isEnabled()).toBe(undo);expect(await page.getByRole('button',{name:'Redo',exact:true}).isEnabled()).toBe(redo);
});

test('cancelled pending microphone permission releases the actual late stream without notes or reference changes',async({page})=>{
 await microphone(page,true);await open(page);const before=await backup(page),durable=await stored(page);await begin(page);await expect.poll(async()=>(await probe(page)).requests).toBe(1);await page.getByRole('button',{name:'Cancel',exact:true}).click();await releasePermission(page);await released(page);await expect(page.getByRole('button',{name:'Record with backing',exact:true})).toBeEnabled();expect(await backup(page)).toEqual(before);expect(await stored(page)).toEqual(durable);expect((await probe(page)).sources).toHaveLength(0);
});

test('unapplied raw fields and continuation proposal refuse backed capture before blur without clearing either',async({page})=>{
 await microphone(page);await open(page);const before=await backup(page);await page.locator('#continuation-count').fill('8');await page.getByRole('button',{name:'Suggest continuation',exact:true}).click();await expect(page.locator('#continuation-proposal')).toBeVisible();const proposal=await page.locator('#proposal-notes').textContent();let dialogs=0;page.on('dialog',dialog=>{dialogs++;void dialog.dismiss();});await page.getByRole('button',{name:'Record with backing',exact:true}).click();await expect(page.locator('#notice')).toContainText(/apply|discard|suggestion|unapplied/i);expect(await page.locator('#proposal-notes').textContent()).toBe(proposal);expect((await probe(page)).requests).toBe(0);expect(dialogs).toBe(0);
 const raw=page.getByLabel('Tempo (BPM)');await raw.fill('');await raw.evaluate(node=>node.setAttribute('data-back-reference','same'));await raw.focus();await page.getByRole('button',{name:'Record with backing',exact:true}).click();await expect(raw).toBeFocused();await expect(raw).toHaveValue('');await expect(raw).toHaveAttribute('data-back-reference','same');expect(await page.locator('#proposal-notes').textContent()).toBe(proposal);expect((await probe(page)).requests).toBe(0);expect(await backup(page)).toEqual(before);
});

test('declined replacement leaves selected complete take and microphone authority untouched',async({page})=>{
 await microphone(page);await open(page);const before=await backup(page),durable=await stored(page);page.once('dialog',dialog=>dialog.dismiss());await page.getByRole('button',{name:'Record with backing',exact:true}).click();expect((await probe(page)).requests).toBe(0);expect(await backup(page)).toEqual(before);expect(await stored(page)).toEqual(durable);await expect(page.getByRole('button',{name:'Record with backing',exact:true})).toBeEnabled();
});

test('no eligible unmuted backing refuses with guidance before requesting microphone access',async({page})=>{
 await microphone(page);const original=originalBacking();for(const track of original.document.composition.tracks.slice(1))track.muted=true;await open(page,original);const before=await backup(page);page.on('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Record with backing',exact:true}).click();await expect(page.locator('#notice')).toContainText(/backing|unmute|audible/i);expect((await probe(page)).requests).toBe(0);expect(await backup(page)).toEqual(before);
});

test('Stop playback and controlled pagehide cancel the whole backed session without publishing partial PCM',async({page})=>{
 await microphone(page);await open(page);const before=await backup(page);await begin(page);await awaitElapsed(page,.2);await page.getByRole('button',{name:'Stop playback',exact:true}).click();await released(page);expect(await backup(page)).toEqual(before);await begin(page);await awaitElapsed(page,.2);await page.evaluate(()=>{dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true}));dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true}));});await released(page);await expect(page.getByRole('button',{name:'Record with backing',exact:true})).toBeEnabled();expect(await backup(page)).toEqual(before);
});

test('silent real microphone completion preserves old notes, reference bytes and redo instead of admitting backing audio',async({page})=>{
 await microphone(page,false,true);await open(page);const before=await backup(page);await begin(page);await awaitElapsed(page,1.2);await page.getByRole('button',{name:'Finish recording',exact:true}).click();await released(page);await expect(page.locator('#notice')).toContainText(/no clear notes/i);expect(await backup(page)).toEqual(before);await expect(page.getByRole('button',{name:'Record with backing',exact:true})).toBeEnabled();
});

test('a foreign saved-copy winner during recording retains new complete memory without overwriting durable PCM',async({page,context})=>{
 test.setTimeout(45000);await microphone(page);await open(page);const original=await backup(page);const winner=await context.newPage();await winner.goto('/');await expect(winner.getByLabel('Project title')).toHaveValue(original.document.composition.title);await expect(winner.getByRole('button',{name:'Record melody',exact:true})).toBeEnabled();await begin(page);await awaitElapsed(page,.1);await winner.getByLabel('Project title').fill('Foreign durable winner113');await winner.getByLabel('Project title').press('Tab');await expect(winner.locator('#save-status')).toHaveText('Saved in this browser');const durable=await stored(winner);await finish(page,1.3);await expect(page.locator('#save-status')).toContainText(/another tab|conflict|protected/i);const memory=await backup(page);expect(memory.document.composition.title).toBe(original.document.composition.title);retainedOthers(original,memory);expect(memory.document.references.find(r=>r.trackId==='target')!.assetId).not.toBe(original.document.references.find(r=>r.trackId==='target')!.assetId);expect(await stored(page)).toEqual(durable);await expect(page.locator('#replace-saved-copy')).toBeVisible();await winner.close();
});

test('390px keyboard capture controls preserve count-in cancellation and fit without horizontal page overflow',async({page},info)=>{
 await page.setViewportSize({width:390,height:844});await microphone(page);await open(page);const before=await backup(page);page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Record with backing',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.locator('#capture-state')).toContainText(/count.?in/i);await expect(page.getByRole('button',{name:'Finish recording',exact:true})).toBeDisabled();await page.screenshot({path:info.outputPath('count-in-390.png'),fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole('button',{name:'Cancel',exact:true}).focus();await page.keyboard.press('Enter');await released(page);expect(await backup(page)).toEqual(before);
});
