import { expect, type Page } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { decodeMidi, decodeWav } from './browser/continuation-fixtures.ts';
export interface OriginalNote {id:string;pitch:number;start:number;duration:number;velocity:number}
export interface OriginalTrack {id:string;name:string;instrument:'sine';volume:number;muted:boolean;notes:OriginalNote[]}
export interface OriginalAsset {id:string;kind:string;captureTempo:number;decodedSampleRate:number;decodedChannels:number;decodedFrames:number;analyzedFrames:number;frameCount:number;sha256:string;pcmBase64:string}
export interface CompleteBackup {format:string;version:number;document:{schemaVersion:number;composition:{version:number;title:string;tempo:number;tracks:OriginalTrack[]};references:{trackId:string;assetId:string}[]};assets:OriginalAsset[]}
export const hash=(bytes:Uint8Array)=>createHash('sha256').update(bytes).digest('hex');
export function originalBacking(title='Original backed recording Ω'):CompleteBackup{
 const target:OriginalTrack={id:'target',name:'Destination high notes',instrument:'sine',volume:1,muted:false,notes:[84,85,84,86,84,85,84,86].map((pitch,i)=>({id:`old-${i}`,pitch,start:i*.25,duration:.25,velocity:.8}))};
 const tracks:OriginalTrack[]=[target,{id:'backing',name:'Audible low backing',instrument:'sine',volume:.25,muted:false,notes:[{id:'low-a',pitch:48,start:0,duration:4,velocity:.5},{id:'low-b',pitch:52,start:4,duration:4,velocity:.5}]},{id:'muted',name:'Muted high sentinel',instrument:'sine',volume:1,muted:true,notes:[{id:'muted-note',pitch:96,start:0,duration:8,velocity:1}]},{id:'zero',name:'Zero volume sentinel',instrument:'sine',volume:0,muted:false,notes:[{id:'zero-note',pitch:90,start:0,duration:8,velocity:1}]}];
 const assets=tracks.map((_,i)=>{const pcm=Buffer.alloc(22050);for(let n=0;n<11025;n++)pcm.writeInt16LE(Math.round(5000*Math.sin(2*Math.PI*(330+55*i)*n/22050)),n*2);return{id:`1130000${i}-0000-4000-8000-000000000001`,kind:'audio-file',captureTempo:240,decodedSampleRate:22050,decodedChannels:1,decodedFrames:11025,analyzedFrames:11025,frameCount:11025,sha256:hash(pcm),pcmBase64:pcm.toString('base64')};});
 return{format:'melody-studio-project',version:1,document:{schemaVersion:1,composition:{version:1,title,tempo:240,tracks},references:tracks.map((track,i)=>({trackId:track.id,assetId:assets[i].id}))},assets};
}
export async function backup(page:Page):Promise<CompleteBackup>{const waiting=page.waitForEvent('download');await page.getByRole('button',{name:'Save project file',exact:true}).click();const path=await(await waiting).path();if(!path)throw Error('Native project download unavailable');const value=JSON.parse((await readFile(path)).toString())as CompleteBackup;for(const asset of value.assets){const pcm=Buffer.from(asset.pcmBase64,'base64');expect(hash(pcm)).toBe(asset.sha256);expect(pcm.length).toBe(asset.frameCount*2);}return value;}
export async function open(page:Page,fixture=originalBacking()){await page.goto('/');await expect(page.getByLabel('Open project file',{exact:true})).toBeEnabled();page.once('dialog',d=>d.accept());await page.getByLabel('Open project file',{exact:true}).setInputFiles({name:'original-backed.melody.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(fixture))});await expect(page.getByLabel('Project title')).toHaveValue(fixture.document.composition.title);await expect(page.locator('#save-status')).toHaveText('Saved in this browser');await page.locator('[data-track=target]').click();}
interface ObservedSource {sampleRate:number;frames:number;when:number;contextRate:number;samples:number[]}
interface Probe {requests:number;stopped:number;sources:ObservedSource[];releasePermission:(()=>void)|null;elapsed:()=>number;stream:MediaStream|null;renderRequests:number}
type ProbeWindow=Window&{backed113:Probe};
export async function microphone(page:Page,pending=false,silent=false){await page.addInitScript(({pending,silent})=>{
 const state:Probe={requests:0,stopped:0,sources:[],releasePermission:null,elapsed:()=>-Infinity,stream:null,renderRequests:0};(window as unknown as ProbeWindow).backed113=state;
 const native=AudioContext.prototype.createBufferSource;
 AudioContext.prototype.createBufferSource=function(){const source=native.call(this),start=source.start.bind(source),context=source.context;source.start=(...args:Parameters<AudioBufferSourceNode['start']>)=>{const b=source.buffer;if(b){const when=args[0]??context.currentTime;state.sources.push({sampleRate:b.sampleRate,frames:b.length,when,contextRate:context.sampleRate,samples:b.length===441000?Array.from(b.getChannelData(0).subarray(0,66150)):[]});if(b.length===441000)state.elapsed=()=>context.currentTime-when;}start(...args);};return source;};
 Object.defineProperty(navigator.mediaDevices,'getUserMedia',{configurable:true,value:async()=>{state.requests++;state.elapsed=()=>-Infinity;const context=new AudioContext(),tone=context.createOscillator(),gain=context.createGain(),destination=context.createMediaStreamDestination();tone.frequency.value=440;gain.gain.value=silent?0:.25;tone.connect(gain).connect(destination);tone.start();const stream=destination.stream;state.stream=stream;for(const track of stream.getTracks()){const stop=track.stop.bind(track);track.stop=()=>{if(track.readyState==='ended')return;state.stopped++;stop();tone.stop();void context.close();};}await context.resume();if(pending)await new Promise<void>(done=>state.releasePermission=done);return stream;}});
 },{pending,silent});}
export async function probe(page:Page){return page.evaluate(()=>{const p=(window as unknown as ProbeWindow).backed113;return{requests:p.requests,stopped:p.stopped,sources:p.sources,elapsed:p.elapsed(),released:p.stream?.getTracks().every(t=>t.readyState==='ended')??false};});}
export async function awaitElapsed(page:Page,seconds:number){await expect.poll(()=>page.evaluate(()=>(window as unknown as ProbeWindow).backed113.elapsed())).toBeGreaterThan(seconds);}
export async function releasePermission(page:Page){await page.evaluate(()=>(window as unknown as ProbeWindow).backed113.releasePermission?.());}
export async function released(page:Page){await expect.poll(async()=>{const p=await probe(page);return p.stopped>0&&p.released;}).toBe(true);}
export function assertBacking(samples:number[]){expect(samples).toHaveLength(66150);let largest=0;for(let i=0;i<samples.length;i++){let want=0;for(const [pitch,start]of[[48,0],[52,22050]]){const local=i-start;if(local<0||local>=23814)continue;const envelope=local<220.5?local/220.5:local<=22050?1:Math.max(0,1-(local-22050)/1764);want+=Math.sin(2*Math.PI*(440*2**((pitch-69)/12))*local/22050)*envelope*.25*.5*.4;}largest=Math.max(largest,Math.abs(samples[i]-want));}expect(largest).toBeLessThanOrEqual(5e-8);expect(samples.slice(45864).every(n=>n===0)).toBe(true);return largest;}
export function assertMicrophone(asset:OriginalAsset){const pcm=Buffer.from(asset.pcmBase64,'base64');expect(asset.kind).toBe('microphone');expect(asset.captureTempo).toBe(240);expect(asset.frameCount).toBeGreaterThan(22050);expect(asset.frameCount).toBeLessThanOrEqual(441000);let power=0,crossings=0;const start=2205,end=Math.min(asset.frameCount-1,start+22050);for(let i=start;i<end;i++){const x=pcm.readInt16LE(i*2)/32768;power+=x*x;if(i>start&&pcm.readInt16LE((i-1)*2)<=0&&x>0)crossings++;}const rms=Math.sqrt(power/(end-start)),hz=crossings*22050/(end-start);expect(Math.abs(rms-.1768)).toBeLessThan(.015);expect(Math.abs(hz-440)).toBeLessThanOrEqual(2);return{rms,hz,frames:asset.frameCount,sha256:asset.sha256};}
export async function stored(page:Page){return page.evaluate(()=>new Promise<{row:unknown;assets:{id:string;sha256:string;bytes:number[]}[]}>((resolve,reject)=>{const req=indexedDB.open('melody-studio.projects');req.onerror=()=>reject(req.error);req.onsuccess=()=>{const db=req.result,tx=db.transaction(['projects','assets'],'readonly'),row=tx.objectStore('projects').get('current'),assets=tx.objectStore('assets').getAll();tx.oncomplete=()=>{db.close();void Promise.all((assets.result as{id:string;sha256:string;pcm:Blob}[]).map(async asset=>({id:asset.id,sha256:asset.sha256,bytes:[...new Uint8Array(await asset.pcm.arrayBuffer())]}))).then(values=>resolve({row:row.result,assets:values}),reject);};tx.onabort=()=>{db.close();reject(tx.error);};};}));}

export async function exportBytes(page:Page,name:string){const waiting=page.waitForEvent('download');await page.getByRole('button',{name,exact:true}).click();const path=await(await waiting).path();if(!path)throw Error('Native export unavailable');return readFile(path);}
export function assertExports(midiBytes:Buffer,wavBytes:Buffer,backup:CompleteBackup){const project=backup.document.composition,midi=decodeMidi(midiBytes);expect(midi.ticksPerBeat).toBe(480);expect(midi.microsecondsPerBeat).toBe(250000);project.tracks.forEach((track,index)=>expect(midi.tracks[index+1].notes).toEqual((track.muted?[]:track.notes).map(note=>{const start=Math.round(note.start*480),end=Math.round((note.start+note.duration)*480);return{pitch:note.pitch,start:start/480,duration:(end-start)/480,velocity:Math.max(1,Math.round(note.velocity*127))};}).sort((a,b)=>a.start-b.start||a.pitch-b.pitch)));const wav=decodeWav(wavBytes),rate=22050;expect(wav.sampleRate).toBe(rate);const end=Math.max(...project.tracks.flatMap(track=>track.notes.map(note=>note.start+note.duration)));expect(wav.samples.length).toBe(Math.ceil((end/4+.08)*rate));let maximum=0;for(let index=0;index<wav.samples.length;index+=37){let value=0;for(const track of project.tracks)if(!track.muted)for(const note of track.notes){const i=index-Math.round(note.start/4*rate),duration=note.duration/4*rate;if(i<0||i>=Math.ceil(duration+.08*rate))continue;const envelope=i<.01*rate?i/(.01*rate):i<=duration?1:Math.max(0,1-(i-duration)/(.08*rate));value+=Math.sin(2*Math.PI*(440*2**((note.pitch-69)/12))*i/rate)*envelope*track.volume*note.velocity*.4;}const wanted=Math.round(value*(value<0?32768:32767));maximum=Math.max(maximum,Math.abs(wav.samples[index]-wanted));}expect(maximum).toBeLessThanOrEqual(2);return{ticksPerBeat:480,wavSampleRate:rate,wavFrames:wav.samples.length,maximumSignedPcmError:maximum};}
