import {test,expect} from '@playwright/test';
import {openRoll,readRoll,rollDownload,assertMidi,assertWav,rollBackup} from './roll-edit-fixtures.ts';
import {savedProject} from './browser/continuation-fixtures.ts';

test('quantize selected original starts with independent project/MIDI/WAV, history and reload',async({page})=>{
 await openRoll(page);const before=await readRoll(page);await page.getByLabel('Section start beat',{exact:true}).fill('1');await page.getByLabel('Section end beat (exclusive)',{exact:true}).fill('4.5');await page.getByLabel('Quantize grid',{exact:true}).selectOption('0.25');await page.getByRole('button',{name:'Quantize section note starts',exact:true}).click();await expect(page.locator('#notice')).toContainText('note starts quantized');const expected=structuredClone(before);expected.document.composition.tracks[0].notes[0].start=.25;expected.document.composition.tracks[0].notes[2].start=2.25;expect(await readRoll(page)).toEqual(expected);assertMidi(await rollDownload(page,'Export MIDI'),expected.document.composition);assertWav(await rollDownload(page,'Export WAV'),expected.document.composition);
 await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await readRoll(page)).toEqual(before);await page.getByRole('button',{name:'Redo',exact:true}).click();expect(await readRoll(page)).toEqual(expected);await expect(page.locator('#save-status')).toHaveText('Saved in this browser');await page.reload();expect(await readRoll(page)).toEqual(expected);
});
test('partial strength, zero/aligned no-op and invalid/empty selection retain reference and redo',async({page})=>{
 await openRoll(page);const before=await readRoll(page);await page.getByLabel('Section start beat',{exact:true}).fill('1');await page.getByLabel('Section end beat (exclusive)',{exact:true}).fill('4.5');await page.getByLabel('Quantize strength',{exact:true}).fill('.5');await page.getByRole('button',{name:'Quantize section note starts',exact:true}).click();const expected=structuredClone(before);expected.document.composition.tracks[0].notes[0].start=1/3+(.25-1/3)*.5;expected.document.composition.tracks[0].notes[2].start=2.1875;expect(await readRoll(page)).toEqual(expected);await page.getByRole('button',{name:'Undo',exact:true}).click();
 for(const strength of ['0','','NaN','1.01','-.1']){await page.getByLabel('Quantize strength',{exact:true}).fill(strength);await page.getByRole('button',{name:'Quantize section note starts',exact:true}).click();await expect(page.getByLabel('Quantize strength',{exact:true})).toHaveValue(strength);await expect(page.getByRole('button',{name:'Redo',exact:true})).toBeEnabled();expect(await readRoll(page)).toEqual(before);}
 await page.getByLabel('Quantize strength',{exact:true}).fill('1');await page.getByLabel('Section start beat',{exact:true}).fill('2');await page.getByLabel('Section end beat (exclusive)',{exact:true}).fill('3');await page.getByRole('button',{name:'Quantize section note starts',exact:true}).click();await expect(page.locator('#notice')).toContainText('no note onsets');await expect(page.getByRole('button',{name:'Redo',exact:true})).toBeEnabled();expect(await readRoll(page)).toEqual(before);
 await page.getByRole('button',{name:'Redo',exact:true}).click();expect(await readRoll(page)).toEqual(expected);
});
test('quantize keeps another focused raw draft before blur and keyboard refusal, with narrow controls',async({page})=>{
 await page.setViewportSize({width:390,height:844});await openRoll(page);const before=await readRoll(page);await page.getByLabel('Section start beat',{exact:true}).fill('1');await page.getByLabel('Section end beat (exclusive)',{exact:true}).fill('4.5');const title=page.getByLabel('Project title',{exact:true});await title.fill('Unsent quantize title');await page.getByRole('button',{name:'Quantize section note starts',exact:true}).click();await expect(title).toHaveValue('Unsent quantize title');await expect(title).toBeFocused();await expect(page.locator('#notice')).toContainText('drafts');expect(await savedProject(page)).toEqual(before.document.composition);await title.fill(before.document.composition.title);await title.press('Tab');await page.locator('[data-note="fractional-low"]').press('Enter');await page.getByLabel('Duration (beats)',{exact:true}).fill('');await page.getByRole('button',{name:'Quantize section note starts',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.getByLabel('Duration (beats)',{exact:true})).toHaveValue('');expect(await readRoll(page)).toEqual(before);await page.getByRole('button',{name:'Discard note edits',exact:true}).click();await page.getByRole('button',{name:'Quantize section note starts',exact:true}).focus();await page.keyboard.press('Enter');expect((await readRoll(page)).document.composition.tracks[0].notes[0].start).toBe(.25);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole('button',{name:'Quantize section note starts',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:test.info().outputPath('quantize-mobile.png')});
});
test('native timeline overflow refuses earlier proposed changes and preserves complete echo/reference graph',async({page})=>{
 const fixture=rollBackup();fixture.document.composition.tracks[0].echo={beats:1,decay:.5,repeats:3};fixture.document.composition.tracks[0].notes.push({id:'edge',pitch:60,start:511.7,duration:.3,velocity:.5});await openRoll(page,fixture);const before=await readRoll(page);await page.getByLabel('Section start beat',{exact:true}).fill('1');await page.getByLabel('Section end beat (exclusive)',{exact:true}).fill('513');await page.getByRole('combobox',{name:'Quantize grid',exact:true}).selectOption('1');await page.getByRole('button',{name:'Quantize section note starts',exact:true}).click();await expect(page.locator('#notice')).toContainText('512');expect(await readRoll(page)).toEqual(before);await expect(page.locator('#save-status')).toHaveText('Saved in this browser');expect(await savedProject(page)).toEqual(before.document.composition);
});
