import {test,expect} from '@playwright/test';
import {installAudioProbe,audioProbe,controlProbe} from './browser/continuation-fixtures.ts';
import {writeFile} from 'node:fs/promises';
import {openRoll,rollBackup,readRoll,rollDownload,dragNote,gridPoint,geometry,assertMidi,assertWav,storedRoll} from './roll-edit-fixtures.ts';

test('the piano roll exposes native movement drawing and snap controls',async({page})=>{
  await openRoll(page);await expect(page.getByRole('combobox',{name:'Piano roll tool',exact:true})).toBeVisible({timeout:2000});await expect(page.locator('#roll-tool')).toHaveValue('move');await expect(page.locator('#roll-snap')).toHaveValue('0.25');
});

test('one native move and resize preserve fractional offsets polyphony reference bytes and one-step Undo',async({page})=>{
  await openRoll(page);const original=await readRoll(page);await dragNote(page,'fractional-low',.25,2);const moved=await readRoll(page);const expected=structuredClone(original);Object.assign(expected.document.composition.tracks[0].notes[0],{start:1/3+.25,pitch:62});expect(moved).toEqual(expected);
  await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await readRoll(page)).toEqual(original);await page.getByRole('button',{name:'Redo',exact:true}).click();expect(await readRoll(page)).toEqual(moved);
  await page.locator('#roll-snap').selectOption('0.125');await dragNote(page,'fractional-low',.125,0,true);const resized=await readRoll(page);expected.document.composition.tracks[0].notes[0].duration=2/3+.125;expect(resized).toEqual(expected);await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await readRoll(page)).toEqual(moved);
});

test('draw click and rightward drag use absolute snap and independent editable IDs',async({page})=>{
  await openRoll(page);const original=await readRoll(page);await page.locator('#roll-tool').selectOption('draw');const at=await gridPoint(page,3.31,65);await page.mouse.click(at.x,at.y);let result=await readRoll(page);const added=result.document.composition.tracks[0].notes.find(n=>!original.document.composition.tracks[0].notes.some(o=>o.id===n.id));expect(added).toMatchObject({pitch:65,start:3.25,duration:1,velocity:.8});expect(result.assets).toEqual(original.assets);
  await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await readRoll(page)).toEqual(original);const from=await gridPoint(page,3.31,65),to=await gridPoint(page,4.08,65);await page.mouse.move(from.x,from.y);await page.mouse.down();await page.mouse.move(to.x,to.y,{steps:4});await page.mouse.up();result=await readRoll(page);const drawn=result.document.composition.tracks[0].notes.find(n=>!original.document.composition.tracks[0].notes.some(o=>o.id===n.id));expect(drawn).toMatchObject({pitch:65,start:3.25,duration:.75,velocity:.8});expect(drawn?.id).not.toBe(added?.id);
});

test('keyboard move and resize preserve exact fractional offsets and Enter selects numeric editing',async({page})=>{
  await openRoll(page);const original=await readRoll(page);let note=page.locator('[data-note="fractional-low"]');await note.focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowUp');await page.keyboard.press('Shift+ArrowRight');const expected=structuredClone(original);Object.assign(expected.document.composition.tracks[0].notes[0],{start:1/3+.25,pitch:61,duration:2/3+.25});expect(await readRoll(page)).toEqual(expected);
  await page.locator('#roll-snap').selectOption('0');note=page.locator('[data-note="fractional-low"]');await note.focus();await page.keyboard.press('ArrowLeft');expected.document.composition.tracks[0].notes[0].start-=.125;expect(await readRoll(page)).toEqual(expected);await note.press('Enter');await expect(page.getByLabel('Pitch (MIDI)')).toHaveValue('61');
});

for(const reason of ['escape','pagehide','resize','scroll','pointercancel','lostcapture'])test(`provisional pointer ${reason} discards the gesture without consuming redo`,async({page})=>{
  await openRoll(page);const original=await readRoll(page);await dragNote(page,'fractional-low',.25);await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.getByRole('button',{name:'Redo',exact:true})).toBeEnabled();await dragNote(page,'fractional-low',.5,1,false,false);await expect(page.locator('.roll-preview')).toBeVisible();
  if(reason==='escape')await page.keyboard.press('Escape');else if(reason==='pagehide')await page.evaluate(()=>{dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true}));dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true}));});else if(reason==='resize')await page.setViewportSize({width:1200,height:790});else if(reason==='scroll')await page.evaluate(()=>window.scrollBy(0,50));else await page.locator('[data-note="fractional-low"]').evaluate((node,type)=>node.dispatchEvent(new PointerEvent(type==='pointercancel'?'pointercancel':'lostpointercapture',{bubbles:true,pointerId:1})),reason);await page.mouse.up();expect(await readRoll(page)).toEqual(original);await expect(page.getByRole('button',{name:'Redo',exact:true})).toBeEnabled();
});

test('focused invalid raw note inputs refuse pointer admission before blur',async({page})=>{
  await openRoll(page);await page.locator('[data-note="fractional-low"]').click();const original=await readRoll(page),field=page.getByLabel('Start beat',{exact:true});await field.fill('');await field.evaluate(n=>n.dataset.original='retained');await dragNote(page,'fractional-low',.5,1);await expect(field).toHaveValue('');await expect(field).toBeFocused();await expect(field).toHaveAttribute('data-original','retained');expect(await readRoll(page)).toEqual(original);
});

test('edited notes export exact independently decoded MIDI and scalar sine audio while retained PCM stays immutable',async({page},info)=>{
  await openRoll(page);await dragNote(page,'fractional-low',.25,2);const result=await readRoll(page),midi=await rollDownload(page,'Export MIDI'),wav=await rollDownload(page,'Export WAV');assertMidi(midi,result.document.composition);const receipt=assertWav(wav,result.document.composition);expect(result.assets).toEqual(rollBackup().assets);await writeFile(info.outputPath('roll-edited.mid'),midi);await writeFile(info.outputPath('roll-edited.wav'),wav);await writeFile(info.outputPath('roll-complete.melody.json'),JSON.stringify(result));await writeFile(info.outputPath('roll-audio-oracle.json'),JSON.stringify(receipt));
});

test('subthreshold movement selects without history and impossible negative moves do not clamp',async({page})=>{
  await openRoll(page);const original=await readRoll(page);const box=await page.locator('[data-note="fractional-low"]').boundingBox();if(!box)throw Error('note missing');await page.mouse.move(box.x+5,box.y+8);await page.mouse.down();await page.mouse.move(box.x+7,box.y+8);await page.mouse.up();expect(await readRoll(page)).toEqual(original);await dragNote(page,'fractional-low',-.5);expect(await readRoll(page)).toEqual(original);
});

test('native touch movement and 390px keyboard controls retain reference and avoid page overflow',async({browser},info)=>{
  const context=await browser.newContext({baseURL:info.project.use.baseURL,viewport:{width:390,height:844},isMobile:true,hasTouch:true});const page=await context.newPage();try{
    await openRoll(page);const original=await readRoll(page),g=await geometry(page),box=await page.locator('[data-note="fractional-low"]').boundingBox();if(!box)throw Error('note missing');await page.evaluate(()=>{const events:unknown[]=[];(window as unknown as {rollTouchEvents:unknown[]}).rollTouchEvents=events;for(const kind of ['pointerdown','pointermove','pointerup','pointercancel','lostpointercapture','gotpointercapture','scroll'])window.addEventListener(kind,event=>{const e=event as PointerEvent;const r=document.querySelector('.roll-grid')!.getBoundingClientRect();events.push({kind,id:e.pointerId,primary:e.isPrimary,button:e.button,x:e.clientX,y:e.clientY,target:(e.target as Element).outerHTML?.slice(0,180),scrollY,rect:{x:r.x,y:r.y,width:r.width,height:r.height},status:document.querySelector('#roll-status')?.textContent});},true);});const client=await context.newCDPSession(page);const x=box.x+5,y=box.y+8;await writeFile(info.outputPath('touch-geometry.json'),JSON.stringify({grid:g,note:box,x,y,hit:await page.evaluate(({x,y})=>({tag:document.elementFromPoint(x,y)?.outerHTML,viewport:{width:innerWidth,height:innerHeight},scrollY}),{x,y})},null,2));await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:1}]});await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+.25*g.width/g.beats,y:y-22,id:1}]});await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await writeFile(info.outputPath('touch-events.json'),JSON.stringify(await page.evaluate(()=>(window as unknown as {rollTouchEvents:unknown[]}).rollTouchEvents),null,2));const expected=structuredClone(original);Object.assign(expected.document.composition.tracks[0].notes[0],{start:1/3+.25,pitch:61});expect(await readRoll(page)).toEqual(expected);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('roll-390px.png'),fullPage:true});
  }finally{await context.close();}
});

test('new changed-back raw input cancels an already visible preview without replacing its native field',async({page})=>{
  await openRoll(page);await page.locator('[data-note="fractional-low"]').click();const original=await readRoll(page),field=page.getByLabel('Velocity');await dragNote(page,'fractional-low',.5,1,false,false);await expect(page.locator('.roll-preview')).toBeVisible();await field.fill('.7');await field.fill('0.5');await field.evaluate(n=>n.dataset.original='retained');await page.mouse.up();await expect(field).toHaveValue('0.5');await expect(field).toHaveAttribute('data-original','retained');expect(await readRoll(page)).toEqual(original);
});

test('a genuine late project-file read cannot overwrite a newer committed roll gesture',async({page})=>{
  await openRoll(page);await page.evaluate(()=>{
    const native=File.prototype.arrayBuffer;const state={pending:false,release:null as null|(()=>void)};(window as unknown as {rollFileGate:typeof state}).rollFileGate=state;
    File.prototype.arrayBuffer=async function(){const result=await native.call(this);if(this.name==='held-roll-replacement.json'){state.pending=true;await new Promise<void>(resolve=>{state.release=resolve;});}return result;};
  });const incoming=rollBackup();incoming.document.composition.title='Late file must not publish';await page.getByLabel('Open project file',{exact:true}).setInputFiles({name:'held-roll-replacement.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(incoming))});await expect.poll(()=>page.evaluate(()=>(window as unknown as {rollFileGate:{pending:boolean}}).rollFileGate.pending)).toBe(true);await dragNote(page,'fractional-low',.25,1);const edited=await readRoll(page);expect(edited.document.composition.tracks[0].notes[0]).toMatchObject({start:1/3+.25,pitch:61});await page.evaluate(()=>(window as unknown as {rollFileGate:{release:()=>void}}).rollFileGate.release());await expect(page.getByLabel('Project title')).toHaveValue(edited.document.composition.title);expect(await readRoll(page)).toEqual(edited);
});

test('a real aborted save preserves the complete durable reference and Retry save publishes the roll edit',async({page})=>{
  await openRoll(page);await expect(page.locator('#save-status')).toHaveText('Saved in this browser');const original=await readRoll(page),durable=await storedRoll(page);await page.evaluate(()=>{
    const native=IDBObjectStore.prototype.put;let armed=true;IDBObjectStore.prototype.put=function(value:unknown,key?:IDBValidKey){const request=key===undefined?native.call(this,value):native.call(this,value,key);if(armed&&this.transaction.db.name==='melody-studio.projects'&&this.name==='projects'){armed=false;request.addEventListener('success',()=>this.transaction.abort(),{once:true});}return request;};
  });await dragNote(page,'fractional-low',.25,1);await expect(page.locator('#save-status')).toContainText(/not saved/i);expect(await storedRoll(page)).toEqual(durable);const memory=await readRoll(page);expect(memory.assets).toEqual(original.assets);expect(memory.document.composition.tracks[0].notes[0].pitch).toBe(61);await page.locator('#retry-save').click();await expect(page.locator('#save-status')).toHaveText('Saved in this browser');await page.reload();await expect(page.getByLabel('Project title')).toHaveValue(original.document.composition.title);expect(await readRoll(page)).toEqual(memory);
});

test('successful roll publication stops actual playback and a retired native end callback cannot restart it',async({page})=>{
  await installAudioProbe(page);await openRoll(page);await page.getByRole('button',{name:'Play composition',exact:true}).click();await expect.poll(async()=>(await audioProbe(page)).starts.length).toBe(1);await dragNote(page,'fractional-low',.25,1);await expect.poll(async()=>(await audioProbe(page)).stopped).toBeGreaterThan(0);const edited=await readRoll(page);await controlProbe(page,'oldEnded');expect((await audioProbe(page)).starts).toHaveLength(1);expect(await readRoll(page)).toEqual(edited);
});

test('protected corrupt native storage remains untouched by direct editing and Undo',async({page})=>{
  await openRoll(page);await expect(page.locator('#save-status')).toHaveText('Saved in this browser');await page.evaluate(async()=>{
    const db=await new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open('melody-studio.projects',1);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});
    try{await new Promise<void>((resolve,reject)=>{const tx=db.transaction('projects','readwrite');tx.objectStore('projects').put({schemaVersion:999,literal:'Retain original unsupported record'},'current');tx.oncomplete=()=>resolve();tx.onabort=()=>reject(tx.error);});}finally{db.close();}
  });await page.reload();await expect(page.locator('#retry-load')).toBeVisible();const protectedState=await storedRoll(page);const fixture=rollBackup();page.once('dialog',dialog=>dialog.accept());await page.getByLabel('Open project file',{exact:true}).setInputFiles({name:'memory-recovery.melody.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(fixture))});await expect(page.getByLabel('Project title')).toHaveValue(fixture.document.composition.title);await dragNote(page,'fractional-low',.25,1);expect(await storedRoll(page)).toEqual(protectedState);await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await readRoll(page)).toEqual(fixture);expect(await storedRoll(page)).toEqual(protectedState);
});

test('a rejected pitch96 keyboard edit retires an older genuine project read without changing notes or references',async({page})=>{
  const fixture=rollBackup();fixture.document.composition.tracks[0].notes[0].pitch=96;await openRoll(page,fixture);const original=await readRoll(page);const unexpectedConsent:string[]=[];page.on('dialog',dialog=>{unexpectedConsent.push(dialog.message());void dialog.accept();});
  await page.evaluate(()=>{
    const native=File.prototype.arrayBuffer;const gate={pending:false,release:null as null|(()=>void)};(window as unknown as {rollRejectedRead:typeof gate}).rollRejectedRead=gate;
    File.prototype.arrayBuffer=async function(){const result=await native.call(this);if(this.name==='held-boundary-replacement.json'){gate.pending=true;await new Promise<void>(resolve=>{gate.release=resolve;});}return result;};
  });const incoming=rollBackup();incoming.document.composition.title='Older read must lose to rejected keyboard intent';await page.getByLabel('Open project file',{exact:true}).setInputFiles({name:'held-boundary-replacement.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(incoming))});await expect.poll(()=>page.evaluate(()=>(window as unknown as {rollRejectedRead:{pending:boolean}}).rollRejectedRead.pending)).toBe(true);await page.locator('[data-note="fractional-low"]').focus();await page.keyboard.press('ArrowUp');await expect(page.locator('#roll-status')).toContainText(/pitch|96|range|C7/i);await page.evaluate(()=>(window as unknown as {rollRejectedRead:{release:()=>void}}).rollRejectedRead.release());await page.waitForTimeout(100);await expect(page.getByLabel('Project title')).toHaveValue(original.document.composition.title);expect(await readRoll(page)).toEqual(original);expect(unexpectedConsent).toEqual([]);
});

test('canceling a drag does not swallow a later trusted keyboard button activation',async({page})=>{
  await openRoll(page);const original=await readRoll(page);await dragNote(page,'fractional-low',.25,1,false,false);await expect(page.locator('.roll-preview')).toBeVisible();await page.keyboard.press('Escape');await page.mouse.up();const add=page.getByRole('button',{name:'Add track',exact:true});await add.focus();await page.keyboard.press('Enter');const edited=await readRoll(page);expect(edited.document.composition.tracks).toHaveLength(3);expect(edited.document.composition.tracks.slice(0,2)).toEqual(original.document.composition.tracks);expect(edited.assets).toEqual(original.assets);await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await readRoll(page)).toEqual(original);
});

test('a minimum quarter-beat note on a128-beat grid has distinct native body and resize hits',async({page},info)=>{
  const fixture=rollBackup();fixture.document.composition.tracks[0].notes[0].duration=.25;fixture.document.composition.tracks[0].notes.push({id:'far-boundary',pitch:64,start:127.75,duration:.25,velocity:.2});await openRoll(page,fixture);const original=await readRoll(page);let note=page.locator('[data-note="fractional-low"]');await note.scrollIntoViewIfNeeded();let box=await note.boundingBox();const grid=await page.locator('.roll-grid').boundingBox();if(!box||!grid)throw Error('Visible long roll expected');const beats=Number(await page.locator('.roll-grid').getAttribute('data-beats'));expect(beats).toBe(128);const x=box.x+box.width/2,y=box.y+box.height/2;const hit=await page.evaluate(({x,y})=>{const node=document.elementFromPoint(x,y);return{note:node?.closest<HTMLElement>('[data-note]')?.dataset.note,resize:!!node?.closest('[data-roll-resize]'),literal:node?.outerHTML};},{x,y});await writeFile(info.outputPath('minimum-note-hit.json'),JSON.stringify({note:box,grid,beats,handle:await note.locator('[data-roll-resize]').boundingBox(),centerHit:hit},null,2));expect(hit.note).toBe('fractional-low');expect(hit.resize).toBe(false);
  await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+.25*grid.width/beats,y,{steps:4});await page.mouse.up();const moved=structuredClone(original);moved.document.composition.tracks[0].notes[0].start=1/3+.25;expect(await readRoll(page)).toEqual(moved);note=page.locator('[data-note="fractional-low"]');await note.scrollIntoViewIfNeeded();box=await note.locator('[data-roll-resize]').boundingBox();if(!box)throw Error('Resize handle missing');const hx=box.x+box.width/2,hy=box.y+box.height/2;expect(await page.evaluate(({x,y})=>!!document.elementFromPoint(x,y)?.closest('[data-roll-resize]'),{x:hx,y:hy})).toBe(true);await page.mouse.move(hx,hy);await page.mouse.down();await page.mouse.move(hx+.25*grid.width/beats,hy,{steps:4});await page.mouse.up();const resized=structuredClone(moved);resized.document.composition.tracks[0].notes[0].duration=.5;expect(await readRoll(page)).toEqual(resized);await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await readRoll(page)).toEqual(moved);await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await readRoll(page)).toEqual(original);
});
