import {test,expect} from '@playwright/test';
import {openRoll,readRoll,rollDownload,assertMidi,assertWav,rollBackup} from './roll-edit-fixtures.ts';
import {savedProject} from './browser/continuation-fixtures.ts';

test('reverse phrase timing matches independent project/MIDI/WAV and exact history/reload',async({page})=>{
 await openRoll(page);const before=await readRoll(page);await page.getByLabel('Section start beat',{exact:true}).fill('1');await page.getByLabel('Section end beat (exclusive)',{exact:true}).fill('4.5');await page.getByRole('button',{name:'Reverse section note timing',exact:true}).click();const expected=structuredClone(before);expected.document.composition.tracks[0].notes[0].start=2.5;expected.document.composition.tracks[0].notes[1].start=2.25;expected.document.composition.tracks[0].notes[2].start=1;expect(await readRoll(page)).toEqual(expected);assertMidi(await rollDownload(page,'Export MIDI'),expected.document.composition);assertWav(await rollDownload(page,'Export WAV'),expected.document.composition);await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await readRoll(page)).toEqual(before);await page.getByRole('button',{name:'Redo',exact:true}).click();expect(await readRoll(page)).toEqual(expected);await expect(page.locator('#save-status')).toHaveText('Saved in this browser');await page.reload();expect(await readRoll(page)).toEqual(expected);
});
test('crossing-note refusal preserves complete effects/reference and prior redo',async({page})=>{
 const fixture=rollBackup();fixture.document.composition.tracks[0].echo={beats:1,decay:.5,repeats:3};fixture.document.composition.tracks[0].filter={cutoff:500,resonance:.7};await openRoll(page,fixture);const before=await readRoll(page);await page.getByLabel('Section start beat',{exact:true}).fill('1');await page.getByLabel('Section end beat (exclusive)',{exact:true}).fill('4.5');await page.getByRole('button',{name:'Reverse section note timing',exact:true}).click();const expected=structuredClone(before);expected.document.composition.tracks[0].notes[0].start=2.5;expected.document.composition.tracks[0].notes[1].start=2.25;expected.document.composition.tracks[0].notes[2].start=1;expect(await readRoll(page)).toEqual(expected);await page.getByRole('button',{name:'Undo',exact:true}).click();for(const [first,last] of [['1.5','3.5'],['1','2']]){await page.getByLabel('Section start beat',{exact:true}).fill(first);await page.getByLabel('Section end beat (exclusive)',{exact:true}).fill(last);await page.getByRole('button',{name:'Reverse section note timing',exact:true}).click();await expect(page.locator('#notice')).toContainText('crosses');expect(await readRoll(page)).toEqual(before);await expect(page.getByRole('button',{name:'Redo',exact:true})).toBeEnabled();}await page.getByRole('button',{name:'Redo',exact:true}).click();expect(await readRoll(page)).toEqual(expected);
});
test('symmetric timing no-op and empty range preserve undo history and recording assets',async({page})=>{
 const fixture=rollBackup();fixture.document.composition.tracks[0].notes=[{id:'fractional-low',pitch:60,start:1.5,duration:.5,velocity:.5}];await openRoll(page,fixture);const before=await readRoll(page);await page.getByLabel('Section start beat',{exact:true}).fill('1');await page.getByLabel('Section end beat (exclusive)',{exact:true}).fill('4.5');await page.getByRole('button',{name:'Transpose section up a semitone',exact:true}).click();const expected=structuredClone(before);expected.document.composition.tracks[0].notes[0].pitch=61;await page.getByRole('button',{name:'Undo',exact:true}).click();await page.getByRole('button',{name:'Reverse section note timing',exact:true}).click();await expect(page.locator('#notice')).toContainText('unchanged');expect(await readRoll(page)).toEqual(before);await expect(page.getByRole('button',{name:'Redo',exact:true})).toBeEnabled();await page.getByLabel('Section start beat',{exact:true}).fill('1');await page.getByLabel('Section end beat (exclusive)',{exact:true}).fill('2');await page.getByRole('button',{name:'Reverse section note timing',exact:true}).click();await expect(page.locator('#notice')).toContainText('no note onsets');expect(await readRoll(page)).toEqual(before);await page.getByRole('button',{name:'Redo',exact:true}).click();expect(await readRoll(page)).toEqual(expected);
});
test('reverse protects preblur and keyboard note drafts with readable narrow controls',async({page})=>{
 await page.setViewportSize({width:390,height:844});await openRoll(page);const before=await readRoll(page);await page.getByLabel('Section start beat',{exact:true}).fill('1');await page.getByLabel('Section end beat (exclusive)',{exact:true}).fill('4.5');const title=page.getByLabel('Project title',{exact:true});await title.fill('Unsent reverse title');await page.getByRole('button',{name:'Reverse section note timing',exact:true}).click();await expect(title).toHaveValue('Unsent reverse title');await expect(title).toBeFocused();expect(await savedProject(page)).toEqual(before.document.composition);await title.fill(before.document.composition.title);await title.press('Tab');await page.locator('[data-note="fractional-low"]').press('Enter');await page.getByLabel('Duration (beats)',{exact:true}).fill('');await page.getByRole('button',{name:'Reverse section note timing',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.getByLabel('Duration (beats)',{exact:true})).toHaveValue('');expect(await readRoll(page)).toEqual(before);await page.getByRole('button',{name:'Discard note edits',exact:true}).click();await page.getByRole('button',{name:'Reverse section note timing',exact:true}).focus();await page.keyboard.press('Enter');expect((await readRoll(page)).document.composition.tracks[0].notes.map(n=>n.start)).toEqual([2.5,2.25,1]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole('button',{name:'Reverse section note timing',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:test.info().outputPath('section-reverse-mobile.png')});
});
