import {test,expect} from '@playwright/test';
import {openRoll,readRoll,rollDownload,assertMidi,assertWav,rollBackup} from './roll-edit-fixtures.ts';
import {savedProject} from './browser/continuation-fixtures.ts';

test('section transpose and inversion produce independent project/MIDI/WAV with history and reload',async({page})=>{
 await openRoll(page);const before=await readRoll(page);await page.getByLabel('Section start beat',{exact:true}).fill('2');await page.getByLabel('Section end beat (exclusive)',{exact:true}).fill('4.5');await page.getByRole('button',{name:'Transpose section up a semitone',exact:true}).click();const partial=structuredClone(before);partial.document.composition.tracks[0].notes[2].pitch=65;expect(await readRoll(page)).toEqual(partial);assertMidi(await rollDownload(page,'Export MIDI'),partial.document.composition);assertWav(await rollDownload(page,'Export WAV'),partial.document.composition);await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await readRoll(page)).toEqual(before);
 await page.getByLabel('Section start beat',{exact:true}).fill('1');await page.getByRole('button',{name:'Invert section pitches',exact:true}).click();const inverted=structuredClone(before);inverted.document.composition.tracks[0].notes[1].pitch=53;inverted.document.composition.tracks[0].notes[2].pitch=56;expect(await readRoll(page)).toEqual(inverted);assertMidi(await rollDownload(page,'Export MIDI'),inverted.document.composition);assertWav(await rollDownload(page,'Export WAV'),inverted.document.composition);await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await readRoll(page)).toEqual(before);await page.getByRole('button',{name:'Redo',exact:true}).click();expect(await readRoll(page)).toEqual(inverted);await expect(page.locator('#save-status')).toHaveText('Saved in this browser');await page.reload();expect(await readRoll(page)).toEqual(inverted);
});
test('all four transpose directions preserve complete reference and effects graph',async({page})=>{
 const fixture=rollBackup();fixture.document.composition.tracks[0].echo={beats:1,decay:.5,repeats:3};fixture.document.composition.tracks[0].filter={cutoff:500,resonance:.7};await openRoll(page,fixture);const before=await readRoll(page);await page.getByLabel('Section start beat',{exact:true}).fill('1');await page.getByLabel('Section end beat (exclusive)',{exact:true}).fill('4.5');for(const [step,label] of [[-12,'down an octave'],[-1,'down a semitone'],[1,'up a semitone'],[12,'up an octave']] as const){await page.getByRole('button',{name:`Transpose section ${label}`,exact:true}).click();const expected=structuredClone(before);for(const note of expected.document.composition.tracks[0].notes)note.pitch+=step;expect(await readRoll(page)).toEqual(expected);await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await readRoll(page)).toEqual(before);}
});
test('unison no-op, empty section and pitch overflow preserve redo and current graph',async({page})=>{
 const fixture=rollBackup();for(const n of fixture.document.composition.tracks[0].notes)n.pitch=36;await openRoll(page,fixture);const before=await readRoll(page);await page.getByLabel('Section start beat',{exact:true}).fill('1');await page.getByLabel('Section end beat (exclusive)',{exact:true}).fill('4.5');await page.getByRole('button',{name:'Transpose section up a semitone',exact:true}).click();const expected=structuredClone(before);for(const note of expected.document.composition.tracks[0].notes)note.pitch=37;await page.getByRole('button',{name:'Undo',exact:true}).click();await page.getByRole('button',{name:'Invert section pitches',exact:true}).click();await expect(page.locator('#notice')).toContainText('unchanged');expect(await readRoll(page)).toEqual(before);await expect(page.getByRole('button',{name:'Redo',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Transpose section down a semitone',exact:true}).click();await expect(page.locator('#notice')).toContainText('pitch');expect(await readRoll(page)).toEqual(before);await expect(page.getByRole('button',{name:'Redo',exact:true})).toBeEnabled();await page.getByLabel('Section start beat',{exact:true}).fill('2');await page.getByLabel('Section end beat (exclusive)',{exact:true}).fill('3');await page.getByRole('button',{name:'Invert section pitches',exact:true}).click();await expect(page.locator('#notice')).toContainText('no note onsets');expect(await readRoll(page)).toEqual(before);await page.getByRole('button',{name:'Redo',exact:true}).click();expect(await readRoll(page)).toEqual(expected);
});
test('pitch buttons protect pointer and keyboard drafts and fit narrow screens',async({page})=>{
 await page.setViewportSize({width:390,height:844});await openRoll(page);const before=await readRoll(page);await page.getByLabel('Section start beat',{exact:true}).fill('1');await page.getByLabel('Section end beat (exclusive)',{exact:true}).fill('4.5');const title=page.getByLabel('Project title',{exact:true});await title.fill('Unsent pitch title');await page.getByRole('button',{name:'Transpose section up a semitone',exact:true}).click();await expect(title).toHaveValue('Unsent pitch title');await expect(title).toBeFocused();expect(await savedProject(page)).toEqual(before.document.composition);await title.fill(before.document.composition.title);await title.press('Tab');await page.locator('[data-note="fractional-low"]').press('Enter');await page.getByLabel('Duration (beats)',{exact:true}).fill('');await page.getByRole('button',{name:'Invert section pitches',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.getByLabel('Duration (beats)',{exact:true})).toHaveValue('');expect(await readRoll(page)).toEqual(before);await page.getByRole('button',{name:'Discard note edits',exact:true}).click();await page.getByRole('button',{name:'Transpose section up a semitone',exact:true}).focus();await page.keyboard.press('Enter');expect((await readRoll(page)).document.composition.tracks[0].notes.map(n=>n.pitch)).toEqual([61,68,65]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole('heading',{name:'Create a phrase variation.',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:test.info().outputPath('section-pitch-mobile.png')});
});
