import {test,expect} from '@playwright/test';
import {openRoll,readRoll,rollDownload} from './roll-edit-fixtures.ts';
import {decodeWav,savedProject} from './browser/continuation-fixtures.ts';
import type {Composition} from '../src/types.ts';

// Independent direct sine/envelope/tap oracle. It uses no production mixer,
// echo helper or oscillator table. Quiet original fixture avoids peak limiting.
function assertEchoWav(bytes:Buffer,p:Composition) {
 const wav=decodeWav(bytes),rate=22050,seconds=60/p.tempo;expect(wav.sampleRate).toBe(rate);
 const end=Math.max(...p.tracks.flatMap(t=>t.notes.map(n=>(n.start+n.duration+(t.echo?t.echo.beats*t.echo.repeats:0))*seconds+.08)));expect(wav.samples.length).toBe(Math.ceil(end*rate));
 let maximum=0;
 for(let index=0;index<wav.samples.length;index+=37){let value=0;
  for(const t of p.tracks)if(!t.muted)for(const n of t.notes)for(let tap=0;tap<=(t.echo?.repeats??0);tap++){
   const offset=Math.round((n.start+tap*(t.echo?.beats??0))*seconds*rate),i=index-offset,duration=n.duration*seconds*rate;if(i<0||i>=Math.ceil(duration+.08*rate))continue;
   const level=i<.01*rate?i/(.01*rate):i<=duration?1:Math.max(0,1-(i-duration)/(.08*rate));
   value+=Math.sin(2*Math.PI*440*2**((n.pitch-69)/12)*i/rate)*level*.4*t.volume*n.velocity*(tap===0?1:t.echo!.decay**tap);
  }
  maximum=Math.max(maximum,Math.abs(wav.samples[index]-Math.round(value*(value<0?32768:32767))));
 }
 expect(maximum).toBeLessThanOrEqual(2);return wav;
}
test('echo applies as one edit with actual full/section WAV, unchanged MIDI/reference, duplication and reload',async({page})=>{
 await openRoll(page);const before=await readRoll(page),dry=await rollDownload(page,'Export WAV'),midi=await rollDownload(page,'Export MIDI');
 await page.getByLabel('Enable rhythmic echo',{exact:true}).check();await page.getByLabel('Echo spacing (beats)',{exact:true}).fill('1');await page.getByLabel('Echo decay',{exact:true}).fill('.5');await page.getByLabel('Echo repeats',{exact:true}).fill('3');expect(await readRoll(page)).toEqual(before);expect(await rollDownload(page,'Export WAV')).toEqual(dry);
 await page.getByRole('button',{name:'Apply sound echo',exact:true}).click();await expect(page.locator('#notice')).toContainText('Sound echo applied');const after=await readRoll(page);expect(after.document.composition.tracks[0].echo).toEqual({beats:1,decay:.5,repeats:3});expect(after.document.references).toEqual(before.document.references);expect(after.assets).toEqual(before.assets);expect(after.document.composition.tracks[1]).toEqual(before.document.composition.tracks[1]);expect(await rollDownload(page,'Export MIDI')).toEqual(midi);
 const wetBytes=await rollDownload(page,'Export WAV'),wet=assertEchoWav(wetBytes,after.document.composition);expect(await rollDownload(page,'Export track WAV')).toEqual(wetBytes);await page.getByLabel('Section start beat',{exact:true}).fill('1');await page.getByLabel('Section end beat (exclusive)',{exact:true}).fill('4');const section=decodeWav(await rollDownload(page,'Export section WAV'));expect(section.samples).toEqual(wet.samples.slice(0,33075));
 await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await readRoll(page)).toEqual(before);expect(await rollDownload(page,'Export WAV')).toEqual(dry);await page.getByRole('button',{name:'Redo',exact:true}).click();expect(await readRoll(page)).toEqual(after);await expect(page.locator('#save-status')).toHaveText('Saved in this browser');await page.reload();expect(await readRoll(page)).toEqual(after);await expect(page.getByLabel('Enable rhythmic echo',{exact:true})).toBeChecked();await page.getByRole('button',{name:'Duplicate track',exact:true}).click();expect((await readRoll(page)).document.composition.tracks[1].echo).toEqual({beats:1,decay:.5,repeats:3});
});
test('actual composition and solo AudioBuffers retain independently decoded echo samples and tail',async({page})=>{
 await page.addInitScript(()=>{const starts:unknown[]=[];Object.assign(window,{echoStarts:starts});const original=AudioBufferSourceNode.prototype.start;AudioBufferSourceNode.prototype.start=function(...args:Parameters<typeof original>){if(this.buffer){const pcm=this.buffer.getChannelData(0);starts.push({rate:this.buffer.sampleRate,length:pcm.length,channels:this.buffer.numberOfChannels,points:Array.from({length:Math.ceil(pcm.length/503)},(_,i)=>[i*503,pcm[i*503]])});}return original.apply(this,args);};});
 await openRoll(page);await page.getByLabel('Enable rhythmic echo',{exact:true}).check();await page.getByRole('button',{name:'Apply sound echo',exact:true}).click();const p=(await readRoll(page)).document.composition,expected=assertEchoWav(await rollDownload(page,'Export WAV'),p);
 for(const name of ['Play composition','Solo track']){await page.getByRole('button',{name,exact:true}).click();await expect(page.locator('#notice')).toContainText(name==='Solo track'?'Soloing':'Playing your composition');await page.getByRole('button',{name:'Stop playback',exact:true}).click();}
 const starts=await page.evaluate(()=>(window as unknown as {echoStarts:{rate:number;length:number;channels:number;points:[number,number][]}[]}).echoStarts);expect(starts).toHaveLength(2);for(const start of starts){expect(start.rate).toBe(22050);expect(start.channels).toBe(1);expect(start.length).toBe(expected.samples.length);for(const [index,sample]of start.points)expect(Math.abs(Math.round(sample*(sample<0?32768:32767))-expected.samples[index])).toBeLessThanOrEqual(1);}
});
test('invalid and retained echo drafts cannot alter sound; discard and bypass restore original PCM',async({page})=>{
 await openRoll(page);const before=await readRoll(page),dry=await rollDownload(page,'Export WAV');await page.getByLabel('Enable rhythmic echo',{exact:true}).check();const spacing=page.getByLabel('Echo spacing (beats)',{exact:true});await spacing.fill('');await page.getByRole('button',{name:'Apply sound echo',exact:true}).click();await expect(page.locator('#notice')).toContainText('nonempty');expect(await readRoll(page)).toEqual(before);await page.getByRole('button',{name:'Select track: Muted independent part',exact:true}).click();await page.getByRole('button',{name:'Select track: Fractional sine',exact:true}).click();await expect(spacing).toHaveValue('');await spacing.fill('1');await page.getByLabel('Echo repeats',{exact:true}).fill('1.5');await page.getByRole('button',{name:'Apply sound echo',exact:true}).click();await expect(page.locator('#notice')).toContainText('integer');expect(await readRoll(page)).toEqual(before);
 await page.getByRole('button',{name:'Discard echo edits',exact:true}).click();await expect(page.getByLabel('Enable rhythmic echo',{exact:true})).not.toBeChecked();await expect(spacing).toHaveValue('1');await page.getByLabel('Enable rhythmic echo',{exact:true}).check();await page.getByRole('button',{name:'Apply sound echo',exact:true}).click();await page.getByLabel('Enable rhythmic echo',{exact:true}).uncheck();await page.getByRole('button',{name:'Apply sound echo',exact:true}).click();expect(await readRoll(page)).toEqual(before);expect(await rollDownload(page,'Export WAV')).toEqual(dry);
});
test('echo Apply protects a focused other draft before blur and supports keyboard at 390px',async({page})=>{
 await page.setViewportSize({width:390,height:844});await openRoll(page);const before=await readRoll(page);await page.getByLabel('Enable rhythmic echo',{exact:true}).check();const title=page.getByLabel('Project title',{exact:true});await title.fill('Unsent echo title');await page.getByRole('button',{name:'Apply sound echo',exact:true}).click();await expect(title).toHaveValue('Unsent echo title');await expect(title).toBeFocused();await expect(page.locator('#notice')).toContainText('other editor drafts');expect(await savedProject(page)).toEqual(before.document.composition);await title.fill(before.document.composition.title);await title.press('Tab');await page.getByRole('button',{name:'Apply sound echo',exact:true}).focus();await page.keyboard.press('Enter');expect((await readRoll(page)).document.composition.tracks[0].echo).toEqual({beats:1,decay:.5,repeats:3});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole('button',{name:'Apply sound echo',exact:true}).scrollIntoViewIfNeeded();const panel=await page.locator('.track-settings').boundingBox(),effect=await page.getByText('Sound echo',{exact:true}).locator('..').boundingBox();expect(effect!.width).toBeGreaterThanOrEqual(panel!.width-2);await page.screenshot({path:test.info().outputPath('echo-mobile.png')});
});
