/* global Buffer, console, process, indexedDB, window */
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {performance} from 'node:perf_hooks';
import {URL} from 'node:url';
import {deflateSync} from 'node:zlib';
import {PNG} from 'pngjs';
import {parseGIF,decompressFrames} from 'gifuct-js';
import {chromium,expect} from '@playwright/test';

// Original literal graph and artwork oracles. No production modules imported.
const CAP=6*1024*1024+168;
const sha=b=>createHash('sha256').update(b).digest('hex');
const bytes=x=>Buffer.from(JSON.stringify(x));
const clone=x=>JSON.parse(JSON.stringify(x));
const arg=name=>{const i=process.argv.indexOf(name);return i<0?null:process.argv[i+1];};
const key=(frame=0,x=0,y=0,scale=1,rotation=0)=>({x,y,scale,rotation,opacity:1,frame,easing:'linear'});
const drawing=(id,name,cels,keys)=>({id,name,keys,kind:'drawing',cels});
function crc(b){let v=0xffffffff;for(const n of b){v^=n;for(let k=0;k<8;k++)v=(v>>>1)^((v&1)?0xedb88320:0);}return(v^0xffffffff)>>>0;}
function chunk(name,data){const b=Buffer.alloc(data.length+12);b.writeUInt32BE(data.length);b.write(name,4);data.copy(b,8);b.writeUInt32BE(crc(b.subarray(4,-4)),b.length-4);return b;}
function png(side,rgb,padding=0){const h=Buffer.alloc(13);h.writeUInt32BE(side);h.writeUInt32BE(side,4);h[8]=8;h[9]=6;const raw=Buffer.alloc(side*(side*4+1));for(let y=0;y<side;y++)for(let x=0;x<side;x++){const i=y*(side*4+1)+1+x*4;raw[i]=rgb[0];raw[i+1]=rgb[1];raw[i+2]=rgb[2];raw[i+3]=255;}const p=[Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',h),chunk('IDAT',deflateSync(raw))];if(padding)p.push(chunk('paDd',Buffer.alloc(padding,71)));p.push(chunk('IEND',Buffer.alloc(0)));return Buffer.concat(p);}
const stroke=(color,width,points)=>({color,width,points});
function originalGraph(){
 const target=stroke('#FF0000',8,Array.from({length:100},(_,i)=>({x:i%2?30:10,y:5})));
 const cels=Array.from({length:24},(_,i)=>({frame:i*4,strokes:[i===0?target:stroke('#0000FF',8,[{x:60,y:5},{x:80,y:5}])]}));
 const remaining=10000-100-46-1,rest=remaining-1000,base=Math.floor(rest/74),extra=rest%74;
 const budget=Array.from({length:75},(_,i)=>stroke('#000000',1,Array.from({length:i===0?1000:base+(i<=extra?1:0)},(_,j)=>({x:-900+j%2,y:-900}))));
 const images=Array.from({length:4},(_,i)=>({id:`original-image-${i}`,name:`Original image ${i}`,keys:[key(0,i===0?500:-640,i===0?40:-360)],kind:'image',image:{dataUrl:'data:image/png;base64,'+png(i===0?16:800,i===0?[0,255,255]:[255,255,255]).toString('base64'),width:i===0?16:800,height:i===0?16:800}}));
 return {schemaVersion:2,title:'Original maximum retained-stroke artwork',background:'#FFFFFF',frameCount:96,layers:[...images,drawing('editable','Editable transformed original',cels,[key(0,200,100,2,90)]),drawing('control','Independent moving green control',[{frame:0,strokes:[stroke('#00FF00',24,[{x:0,y:0}])]}],[key(0,400,300),key(95,440,300)]),drawing('budget','Offstage original point budget',[{frame:0,strokes:budget}],[key()]),drawing('blank','Untouched blank drawing',[{frame:0,strokes:[]}],[key()])]};
}
function counts(p){const ds=p.layers.filter(l=>l.kind==='drawing'),ss=ds.flatMap(l=>l.cels.flatMap(c=>c.strokes));return{layers:p.layers.length,images:p.layers.length-ds.length,cels:ds.reduce((n,l)=>n+l.cels.length,0),selectedLayerCels:ds[0].cels.length,strokes:ss.length,points:ss.reduce((n,s)=>n+s.points.length,0),longestStroke:Math.max(...ss.map(s=>s.points.length))};}
function paddedCapacity(source){const p=clone(source);let missing=CAP-bytes(p).length;p.title+='q'.repeat(missing%4);missing=CAP-bytes(p).length;assert.equal(missing%4,0);for(let i=0;i<4;i++){const l=p.layers[i],old=l.image.dataUrl.length,add=Math.min(missing,Math.floor((1.5*1024*1024-old)/4)*4);if(add){const expected=old+add,side=l.image.width,color=i===0?[0,255,255]:[255,255,255];let padding=Math.floor((expected-22)/4)*3-png(side,color,1).length+1;let b=png(side,color,padding);while(22+4*Math.ceil(b.length/3)>expected)b=png(side,color,--padding);while(22+4*Math.ceil(b.length/3)<expected)b=png(side,color,++padding);l.image.dataUrl='data:image/png;base64,'+b.toString('base64');assert.equal(l.image.dataUrl.length,expected);missing-=add;}}assert.equal(missing,0);assert.equal(bytes(p).length,CAP);return p;}
function expectedStates(original){const moved=clone(original);moved.layers[4].cels[0].strokes[0].points=moved.layers[4].cels[0].strokes[0].points.map(p=>({x:p.x,y:0}));const blue=clone(moved);blue.layers[4].cels[0].strokes[0].color='#0000ff';blue.layers[4].cels[0].strokes[0].width=12;const deleted=clone(blue);deleted.layers[4].cels[0].strokes=[];return{original,moved,blue,deleted};}
function patch(r,x,y,wanted,label){assert.equal(r.width,640);assert.equal(r.height,360);const data=r.data??r.patch;for(let yy=y-1;yy<=y+1;yy++)for(let xx=x-1;xx<=x+1;xx++)assert.deepEqual([...data.subarray((yy*640+xx)*4,(yy*640+xx)*4+4)],wanted,`${label}: ${xx},${yy}`);}
function inspectArtwork(r,frame,state){patch(r,500,40,[0,255,255,255],'original cyan PNG');patch(r,Math.floor(400+40*frame/95),300,[0,255,0,255],'independent animated green dot');patch(r,175,140,[255,255,255,255],'no exported selection overlay');if(frame<4){patch(r,state==='original'?190:200,140,state==='deleted'?[255,255,255,255]:state==='blue'?[0,0,255,255]:[255,0,0,255],`${state} selected exposure`);}else patch(r,190,240,[0,0,255,255],'untouched later cel');}
function inspectGif(b,state){const frames=decompressFrames(parseGIF(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)),true);assert.equal(frames.length,96);let total=0;for(let f=0;f<96;f++){const r=frames[f];assert.deepEqual(r.dims,{top:0,left:0,width:640,height:360});assert.equal(r.delay,10*(Math.round((f+1)*100/12)-Math.round(f*100/12)));total+=r.delay;inspectArtwork({width:640,height:360,patch:r.patch},f,state);}assert.equal(total,8000);return{frames:96,durationMs:total,frameHashes:frames.map(f=>sha(f.patch))};}
async function artifact(out,name,b){await writeFile(join(out,name),b);return{file:name,bytes:b.length,sha256:sha(b)};}
async function download(page,id,out,name){const pending=page.waitForEvent('download',{timeout:45000});await page.locator(id).click();await(await pending).saveAs(join(out,name));return readFile(join(out,name));}
async function backup(page,out,name){return download(page,'#backup',out,name);}
async function seek(page,f){await page.locator('#frame').focus();await page.keyboard.press('Home');for(let i=0;i<f;i++)await page.keyboard.press('ArrowRight');await expect(page.locator('#stage')).toHaveAttribute('data-frame',String(f));}
async function open(page,p){const previous=await nativeRow(page);await expect(page.locator('#project-file')).toBeEnabled();await page.locator('#project-file').setInputFiles({name:'original-stroke-fixture.motion.json',mimeType:'application/json',buffer:bytes(p)});await expect(page.locator('#message')).toContainText('Project file imported as a new editable project.');await expect(page.locator('#project-title')).toHaveValue(p.title);await expect(page.locator('#stage')).toHaveAttribute('aria-disabled','false');await expect.poll(async()=>{const row=await nativeRow(page);return row.id!==previous.id?row.project:null;},{timeout:20000}).toEqual(p);await expect(page.locator('#save-status')).toHaveText('Saved in this browser',{timeout:20000});}
async function nativeRow(page){return page.evaluate(()=>new Promise((resolve,reject)=>{const rq=indexedDB.open('motion-studio',2);rq.onerror=()=>reject(rq.error);rq.onsuccess=()=>{const db=rq.result,tx=db.transaction(['library','projects'],'readonly'),head=tx.objectStore('library').get('current');let id=null,project=null;head.onsuccess=()=>{if(!head.result?.activeId)return;id=head.result.activeId;const row=tx.objectStore('projects').get(id);row.onsuccess=()=>{project=row.result?.project;};};tx.oncomplete=()=>{db.close();resolve({id,project});};tx.onabort=()=>{db.close();reject(tx.error??Error('Library observation aborted'));};};}));}
async function nativeRecord(page){return(await nativeRow(page)).project;}
async function pid(context){const s=await context.browser().newBrowserCDPSession();try{return(await s.send('SystemInfo.getProcessInfo')).processInfo.filter(p=>p.type==='browser').map(p=>p.id);}finally{await s.detach();}}
async function main(){
 const output=arg('--output');assert(output,'Specify --output NEW_DIRECTORY for --prepare, existing prepared directory for --run.');const out=resolve(output);
 if(process.argv.includes('--prepare')){await mkdir(out,{recursive:false});const original=originalGraph(),capacity=paddedCapacity(original),states=expectedStates(original);assert.deepEqual(counts(original),{layers:8,images:4,cels:27,selectedLayerCels:24,strokes:100,points:10000,longestStroke:1000});for(const l of capacity.layers.filter(l=>l.kind==='image')){assert(l.image.dataUrl.length<=1.5*1024*1024);const image=PNG.sync.read(Buffer.from(l.image.dataUrl.split(',')[1],'base64'));assert.equal(image.width,l.image.width);assert.equal(image.height,l.image.height);}const fixtures={schemaVersion:1,issue:122,counts:counts(original),capacityBytes:CAP,scalarExpectation:'Pose(200,100,2,90): local(10,5)→stage(190,120). Shift+Right is stage(+10,0)→local(0,-5); all target y=0, unchanged x/order/count. Blue width12 and deletion affect only boundary0 exposure frames0..3.',files:{},limits:['Graph has four drawings/four images and27 total cels, selected layer24; not eight drawings192 cels.','Exact6MiB+168 variant uses declared private ancillary paDd capacity bytes, not complex imagery or peak-memory proof.','Artwork editing uses the identical unpadded graph so longer legal numeric spellings/color/width cannot consume a false capacity claim.','No photo normalization, inference, native device or server lifecycle claim.']};for(const[name,p]of Object.entries({...states,capacity}))fixtures.files[name]=await artifact(out,`${name}.motion.json`,bytes(p));await writeFile(join(out,'fixture-oracle.json'),JSON.stringify(fixtures,null,2)+'\n');console.log(JSON.stringify({status:'prepared',out,counts:fixtures.counts,files:fixtures.files},null,2));return;}
 assert(process.argv.includes('--run'),'Use --prepare or --run.');const origin=arg('--origin');assert(origin,'--run requires root-owned --origin.');const fixture=JSON.parse(await readFile(join(out,'fixture-oracle.json'),'utf8')),states={};for(const[name,meta]of Object.entries(fixture.files)){const b=await readFile(join(out,meta.file));assert.equal(sha(b),meta.sha256);assert.equal(b.length,meta.bytes);states[name]=JSON.parse(b);}
 const evidence={schemaVersion:1,issue:122,status:'running',scriptSha256:sha(await readFile(new URL(import.meta.url))),fixtureOracleSha256:sha(await readFile(join(out,'fixture-oracle.json'))),fixture,checks:[],artifacts:[],browserPids:[],pageErrors:[],externalRequests:[],scope:'Original independent scalar/pixel/full graph oracle; actual native UI, native IndexedDB read-only observation. Browser lifecycle owned by runner; root owns service.'};let context,page;const started=performance.now(),profile=join(out,'profile'),save=()=>writeFile(join(out,'verification.json'),JSON.stringify(evidence,null,2)+'\n');await save();
 const mount=async()=>{context=await chromium.launchPersistentContext(profile,{headless:true,acceptDownloads:true,viewport:{width:1280,height:1000},...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});evidence.browserVersion=context.browser().version();evidence.browserPids.push(await pid(context));page=context.pages()[0];page.on('dialog',d=>d.accept());page.on('pageerror',e=>evidence.pageErrors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url())&&new URL(r.url()).origin!==new URL(origin).origin)evidence.externalRequests.push(r.url());});await page.goto(origin);if(evidence.browserPids.length===1)await expect(page.locator('#save-status')).toHaveText('Original demo · saved after your first edit');await expect(page.locator('#stage')).toHaveAttribute('aria-disabled','false');await expect(page.locator('#project-file')).toBeEnabled();};
 const checkState=async(name,label)=>{const b=await backup(page,out,`${label}.motion.json`);assert.deepEqual(JSON.parse(b),states[name]);evidence.artifacts.push({file:`${label}.motion.json`,bytes:b.length,sha256:sha(b)});return b;};
 const select=async()=>{await page.locator('#layers button').filter({hasText:'Editable transformed original'}).click();await seek(page,0);await page.locator('#edit-strokes-mode').click();await page.locator('#stroke-list button[data-stroke-index="0"]').click();};
 try{
  await mount();await open(page,states.capacity);const capBefore=await checkState('capacity','capacity-before-restart');assert.equal(capBefore.length,CAP);assert.deepEqual(await nativeRecord(page),states.capacity);await context.close();context=undefined;await mount();await expect(page.locator('#project-title')).toHaveValue(states.capacity.title);const capAfter=await checkState('capacity','capacity-after-restart');assert(capBefore.equals(capAfter));assert.notDeepEqual(evidence.browserPids[0],evidence.browserPids[1]);assert.deepEqual(await nativeRecord(page),states.capacity);evidence.checks.push('Exact capacity embedded images and maximum retained graph survive complete Chromium process restart byte-identically.');await page.locator('#project-file').setInputFiles({name:'capacity-plus-one.motion.json',mimeType:'application/json',buffer:Buffer.concat([bytes(states.capacity),Buffer.from(' ')])});await expect(page.locator('#message')).toContainText(/large|limit/i);const afterOverflow=await checkState('capacity','after-capacity-plus-one');assert(capAfter.equals(afterOverflow));assert.deepEqual(await nativeRecord(page),states.capacity);evidence.checks.push('Whole native File capacity+1 refuses without replacing the exact committed or saved project.');
  await open(page,states.original);const originalPng=await download(page,'#png',out,'original-frame-0.png');inspectArtwork(PNG.sync.read(originalPng),0,'original');evidence.artifacts.push({file:'original-frame-0.png',bytes:originalPng.length,sha256:sha(originalPng)});await select();await checkState('original','selection-no-mutation');await expect(page.getByRole('button',{name:'Undo',exact:true})).toBeDisabled();const selected=page.locator('#stroke-list button[data-stroke-index="0"]');await selected.focus();await page.keyboard.press('Shift+ArrowRight');await checkState('moved','after-keyboard-move');const movedPng=await download(page,'#png',out,'moved-frame-0.png');inspectArtwork(PNG.sync.read(movedPng),0,'moved');evidence.artifacts.push({file:'moved-frame-0.png',bytes:movedPng.length,sha256:sha(movedPng)});await page.getByRole('button',{name:'Undo',exact:true}).click();await checkState('original','move-undo');await page.getByRole('button',{name:'Redo',exact:true}).click();await checkState('moved','move-redo');await select();await page.locator('#stroke-color').fill('#0000FF');await page.locator('#stroke-width').fill('12');await page.locator('#stroke-apply').click();await checkState('blue','after-appearance');await page.getByRole('button',{name:'Undo',exact:true}).click();await checkState('moved','appearance-undo');await page.getByRole('button',{name:'Redo',exact:true}).click();await checkState('blue','appearance-redo');await select();await page.locator('#stroke-delete').click();await checkState('deleted','after-delete');await page.getByRole('button',{name:'Undo',exact:true}).click();await checkState('blue','delete-undo');await select();await page.locator('#stroke-apply').click();await expect(page.getByRole('button',{name:'Redo',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Redo',exact:true}).click();await checkState('deleted','delete-redo');await page.getByRole('button',{name:'Undo',exact:true}).click();await checkState('blue','final-blue');evidence.checks.push('Trusted list/keyboard selection, stage-axis translation, appearance and deletion each preserve literal graph except intended stroke; one-step Undo/Redo and no-op Apply preserve Redo.');
  for(const f of[0,3,4,95]){await seek(page,f);const b=await download(page,'#png',out,`edited-frame-${f}.png`);inspectArtwork(PNG.sync.read(b),f,'blue');evidence.artifacts.push({file:`edited-frame-${f}.png`,bytes:b.length,sha256:sha(b)});}await seek(page,0);await select();await page.locator('#stroke-delete').click();const blank=await download(page,'#png',out,'deleted-frame-0.png');inspectArtwork(PNG.sync.read(blank),0,'deleted');evidence.artifacts.push({file:'deleted-frame-0.png',bytes:blank.length,sha256:sha(blank)});await page.getByRole('button',{name:'Undo',exact:true}).click();await checkState('blue','pre-export-blue');const t=performance.now(),gif=await download(page,'#gif',out,'edited-96-frames.gif');evidence.gif={bytes:gif.length,sha256:sha(gif),encodeAndDownloadWallMs:performance.now()-t};assert(gif.length<=32*1024*1024);const dt=performance.now();Object.assign(evidence.gif,inspectGif(gif,'blue'),{independentDecodeWallMs:performance.now()-dt});evidence.checks.push('Actual PNG/GIF original cyan image, independent moving dot, held exposure boundary and edited stroke interiors decoded against literal colors; selection overlays excluded.');
  await expect(page.locator('#save-status')).toHaveText('Saved in this browser',{timeout:20000});await expect.poll(()=>nativeRecord(page),{timeout:20000}).toEqual(states.blue);const before=await checkState('blue','artwork-before-restart');await context.close();context=undefined;await mount();await expect(page.locator('#project-title')).toHaveValue(states.blue.title);const after=await checkState('blue','artwork-after-restart');assert(before.equals(after));assert.notDeepEqual(evidence.browserPids[1],evidence.browserPids[2]);assert.deepEqual(await nativeRecord(page),states.blue);evidence.restart={capacityByteExact:true,editedArtworkByteExact:true,backupBytes:after.length,backupSha256:sha(after)};await page.screenshot({path:join(out,'desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>window.document.documentElement.scrollWidth<=window.innerWidth));await page.screenshot({path:join(out,'390px.png'),fullPage:true});assert.deepEqual(evidence.pageErrors,[]);assert.deepEqual(evidence.externalRequests,[]);evidence.status='passed';console.log(JSON.stringify({status:evidence.status,counts:fixture.counts,gifBytes:evidence.gif.bytes,restart:evidence.restart},null,2));
 }catch(e){evidence.status='failed';evidence.failure={name:e.name,message:e.message,stack:e.stack};throw e;}finally{await context?.close();evidence.browsersClosed=true;evidence.wallMs=performance.now()-started;await save();}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
