import {test,expect,type Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {PNG} from 'pngjs';
import {independentPng} from '../oracle/fixtures';
import {scalarReference} from '../oracle/scalar';
import type {Project} from '../../src/types';
async function backup(page:Page):Promise<Project>{const [file]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Download project',exact:true}).click()]);return JSON.parse((await readFile((await file.path())!)).toString());}
async function setup(page:Page){await page.goto('/');await expect(page.locator('#save-status')).not.toContainText('Checking local');const rgba=new Uint8ClampedArray(16*12*4);for(let y=0;y<12;y++)for(let x=0;x<16;x++){const color=x===6?200:x===5?20:10;rgba.set([color,color,color,255],(y*16+x)*4);}await page.getByLabel('Import photo',{exact:true}).setInputFiles({name:'disconnected-colors.png',mimeType:'image/png',buffer:independentPng({width:16,height:12,rgba})});await expect(page.locator('#render-status')).toContainText('Projection ready');await page.getByLabel('Depth tool',{exact:true}).selectOption('color');await page.getByLabel('Paint near',{exact:true}).check();}
async function seed(page:Page,release=true){await page.locator('#source-canvas').scrollIntoViewIfNeeded();const b=(await page.locator('#source-canvas').boundingBox())!;await page.mouse.move(b.x+b.width*3.5/16,b.y+b.height*5.5/12);await page.mouse.down();if(release)await page.mouse.up();}
test('connected seed threshold yields exact actual mask one edit reload and independent perspective PNG',async({page})=>{
 await setup(page);const original=await backup(page);await page.getByLabel('Color tolerance',{exact:true}).fill('10');await seed(page);const next=await backup(page);expect(next).toEqual({...original,depth:next.depth});const labels=Buffer.from(next.depth.labels,'base64');for(let y=0;y<12;y++)for(let x=0;x<16;x++)expect(labels[y*16+x]).toBe(x<6?0:1);await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await backup(page)).toEqual(original);await page.getByRole('button',{name:'Redo',exact:true}).click();expect(await backup(page)).toEqual(next);await expect(page.locator('#save-status')).toContainText('Saved locally');await page.reload();await expect(page.locator('#render-status')).toContainText('Projection ready');expect(await backup(page)).toEqual(next);await page.getByLabel('I understand this is manual geometry, not inferred depth',{exact:true}).check();await page.getByLabel('Manual perspective',{exact:true}).check();await page.locator('#settings-form [name=targetFocal]').fill('75');await page.getByRole('button',{name:'Apply settings',exact:true}).click();await expect(page.locator('#render-status')).toContainText('Projection ready');const project=await backup(page),png=PNG.sync.read(Buffer.from(project.photo.dataUrl.split(',')[1],'base64'));const expected=scalarReference({width:16,height:12,rgba:new Uint8ClampedArray(png.data)},project.settings,new Uint8Array(Buffer.from(project.depth.labels,'base64')));const [file]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Export PNG',exact:true}).click()]);const actual=PNG.sync.read(await readFile((await file.path())!));expect([actual.width,actual.height]).toEqual([16,12]);let maximum=0;for(let i=0;i<actual.data.length;i++)maximum=Math.max(maximum,Math.abs(actual.data[i]-expected.rgba[i]));expect(maximum).toBeLessThanOrEqual(1);expect(await backup(page)).toEqual(project);
});
test('invalid color drafts canceled preview and same-plane no-op keep complete study unrelated drafts and redo',async({page})=>{
 await page.setViewportSize({width:390,height:844});await setup(page);await page.getByLabel('Color tolerance',{exact:true}).fill('0');const original=await backup(page);await seed(page);const painted=await backup(page);await page.getByRole('button',{name:'Undo',exact:true}).click();await page.getByLabel('Target focal length',{exact:true}).fill('');await page.getByLabel('Brush size',{exact:true}).fill('');for(const raw of ['','256','-1','.5']){await page.getByLabel('Color tolerance',{exact:true}).fill(raw);await seed(page);expect(await backup(page)).toEqual(original);await expect(page.getByLabel('Color tolerance',{exact:true})).toHaveValue(raw);await expect(page.getByRole('button',{name:'Redo',exact:true})).toBeEnabled();}await page.getByLabel('Color tolerance',{exact:true}).fill('0');await seed(page,false);await page.keyboard.press('Escape');await page.mouse.up();expect(await backup(page)).toEqual(original);await expect(page.getByLabel('Target focal length',{exact:true})).toHaveValue('');await expect(page.getByLabel('Brush size',{exact:true})).toHaveValue('');await page.getByLabel('Paint subject',{exact:true}).check();await seed(page);expect(await backup(page)).toEqual(original);await page.getByRole('button',{name:'Redo',exact:true}).click();expect(await backup(page)).toEqual(painted);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('#paint-controls').screenshot({path:test.info().outputPath('color-regions-mobile.png')});
});
test('tolerance or tool changes discard only the captured color preview',async({page})=>{
 await setup(page);const before=await backup(page);await seed(page,false);await page.getByLabel('Color tolerance',{exact:true}).focus();await page.keyboard.press('ControlOrMeta+A');await page.keyboard.type('25');await page.mouse.up();expect(await backup(page)).toEqual(before);await seed(page,false);await page.getByLabel('Depth tool',{exact:true}).selectOption('rectangle');await page.mouse.up();expect(await backup(page)).toEqual(before);await expect(page.getByRole('button',{name:'Undo',exact:true})).toBeDisabled();
});
test('maximum original photo connected preview commits all1638400 labels with exact complete history',async({page})=>{
 await page.goto('/');await expect(page.locator('#save-status')).not.toContainText('Checking local');const rgba=new Uint8ClampedArray(1280*1280*4).fill(255);await page.getByLabel('Import photo',{exact:true}).setInputFiles({name:'maximum-source.png',mimeType:'image/png',buffer:independentPng({width:1280,height:1280,rgba})});await expect(page.locator('#source-canvas')).toBeVisible({timeout:40000});const original=await backup(page);expect([original.photo.width,original.photo.height]).toEqual([1280,1280]);await page.getByLabel('Depth tool',{exact:true}).selectOption('color');await page.getByLabel('Paint near',{exact:true}).check();await page.getByLabel('Color tolerance',{exact:true}).fill('0');await page.locator('#source-canvas').scrollIntoViewIfNeeded();const b=(await page.locator('#source-canvas').boundingBox())!;await page.mouse.move(b.x+b.width/2,b.y+b.height/2);const start=Date.now();await page.mouse.down();const pointerDownRoundTripMs=Date.now()-start;const preview=await page.locator('#source-canvas').evaluate((canvas:HTMLCanvasElement)=>[...canvas.getContext('2d')!.getImageData(640,640,1,1).data]);expect(preview[0]).toBeLessThan(255);await page.mouse.up();const next=await backup(page),labels=Buffer.from(next.depth.labels,'base64');expect(labels.length).toBe(1638400);expect(labels.every(v=>v===0)).toBe(true);expect(next).toEqual({...original,depth:next.depth});await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await backup(page)).toEqual(original);await page.getByRole('button',{name:'Redo',exact:true}).click();expect(await backup(page)).toEqual(next);test.info().annotations.push({type:'measured-pointerdown-roundtrip-ms',description:String(pointerDownRoundTripMs)});console.log(JSON.stringify({maximumColorSelection:{width:1280,height:1280,labels:labels.length,pointerDownRoundTripMs,previewRGBA:preview}}));
});
