import {test,expect,type Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {PNG} from 'pngjs';
import {scalarReference} from '../oracle/scalar';
import {texture,independentPng} from '../oracle/fixtures';
import type {Project} from '../../src/types';
async function backup(page:Page):Promise<Project>{const [file]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Download project',exact:true}).click()]);return JSON.parse((await readFile((await file.path())!)).toString());}
async function setup(page:Page){await page.goto('/');await expect(page.locator('#save-status')).not.toContainText('Checking local');await page.getByLabel('Import photo',{exact:true}).setInputFiles({name:'retained-source.png',mimeType:'image/png',buffer:independentPng(texture(32,24))});await expect(page.locator('#render-status')).toContainText('Projection ready');}
async function drag(page:Page,points:{x:number;y:number}[],end=true){const canvas=page.locator('#source-canvas');await canvas.scrollIntoViewIfNeeded();const b=(await canvas.boundingBox())!;const to=(p:{x:number;y:number})=>({x:b.x+p.x/32*b.width,y:b.y+p.y/24*b.height});const start=to(points[0]);await page.mouse.move(start.x,start.y);await page.mouse.down();for(const point of points.slice(1)){const p=to(point);await page.mouse.move(p.x,p.y);}if(end)await page.mouse.up();}
test('actual rectangle masks retain complete original photo settings and exact one-step history plus saved reload',async({page})=>{
 await setup(page);const original=await backup(page);await page.getByLabel('Depth tool',{exact:true}).selectOption('rectangle');await page.getByLabel('Paint near',{exact:true}).check();await drag(page,[{x:4,y:4},{x:20,y:16}]);const next=await backup(page),labels=Buffer.from(next.depth.labels,'base64');expect(next).toEqual({...original,depth:next.depth});for(let y=0;y<24;y++)for(let x=0;x<32;x++)expect(labels[y*32+x]).toBe(x>=4&&x<20&&y>=4&&y<16?0:1);await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await backup(page)).toEqual(original);await page.getByRole('button',{name:'Redo',exact:true}).click();expect(await backup(page)).toEqual(next);await expect(page.locator('#save-status')).toContainText('Saved locally');await page.reload();await expect(page.locator('#source-canvas')).toBeVisible();expect(await backup(page)).toEqual(next);
});
test('actual polygon fills its boundary and Escape cancels a new region while raw fields and redo survive',async({page})=>{
 await setup(page);const original=await backup(page);await page.getByLabel('Depth tool',{exact:true}).selectOption('polygon');await page.getByLabel('Paint far',{exact:true}).check();const requested=[{x:3.2,y:2.3},{x:28.4,y:3.37},{x:3.2,y:20.1}];await page.locator('#source-canvas').evaluate((canvas:HTMLCanvasElement)=>{const observed:{x:number;y:number}[]=[];Object.assign(window,{observedRegionPoints:observed});for(const kind of ['pointerdown','pointermove','pointerup'])canvas.addEventListener(kind,event=>{const e=event as PointerEvent;if(kind==='pointermove'&&!e.buttons)return;if(kind==='pointerdown')observed.length=0;const b=canvas.getBoundingClientRect();observed.push({x:Math.max(0,Math.min(32,(e.clientX-b.left)*32/b.width)),y:Math.max(0,Math.min(24,(e.clientY-b.top)*24/b.height))});});});await drag(page,requested);const points=await page.evaluate(()=>(window as unknown as {observedRegionPoints:{x:number;y:number}[]}).observedRegionPoints);const next=await backup(page),labels=Buffer.from(next.depth.labels,'base64');for(let y=0;y<24;y++)for(let x=0;x<32;x++){let inside=false;for(let i=0,j=points.length-1;i<points.length;j=i++){const a=points[i],b=points[j];if((a.y>y+.5)!==(b.y>y+.5)&&x+.5<(b.x-a.x)*(y+.5-a.y)/(b.y-a.y)+a.x)inside=!inside;}expect(labels[y*32+x],JSON.stringify({x,y,points,requested})).toBe(inside?2:1);}await page.getByRole('button',{name:'Undo',exact:true}).click();await page.getByLabel('Target focal length',{exact:true}).fill('');await drag(page,[{x:2,y:2},{x:15,y:10}],false);await page.keyboard.press('Escape');await page.mouse.up();expect(await backup(page)).toEqual(original);await expect(page.getByLabel('Target focal length',{exact:true})).toHaveValue('');await expect(page.getByRole('button',{name:'Redo',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Redo',exact:true}).click();expect(await backup(page)).toEqual(next);
});
test('390px depth tools and explicit cancellation keep the mask intact',async({page})=>{
 await page.setViewportSize({width:390,height:844});await setup(page);const original=await backup(page);await page.getByLabel('Depth tool',{exact:true}).selectOption('rectangle');await page.getByLabel('Paint near',{exact:true}).check();await drag(page,[{x:1,y:1},{x:18,y:17}],false);await page.getByRole('button',{name:'Cancel depth gesture',exact:true}).focus();await page.keyboard.press('Enter');await page.mouse.up();expect(await backup(page)).toEqual(original);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('#paint-controls').screenshot({path:test.info().outputPath('depth-region-mobile.png')});
});

test('rectangle and polygon assignments feed exact manual perspective PNG export',async({page})=>{
 await setup(page);await page.getByLabel('Depth tool',{exact:true}).selectOption('rectangle');await page.getByLabel('Paint near',{exact:true}).check();await drag(page,[{x:2,y:4},{x:15,y:20}]);await page.getByLabel('Depth tool',{exact:true}).selectOption('polygon');await page.getByLabel('Paint far',{exact:true}).check();await drag(page,[{x:17,y:2},{x:29,y:7},{x:22,y:22}]);await page.getByLabel('I understand this is manual geometry, not inferred depth',{exact:true}).check();await page.getByLabel('Manual perspective',{exact:true}).check();await page.locator('#settings-form [name=targetFocal]').fill('75');await page.getByRole('button',{name:'Apply settings',exact:true}).click();await expect(page.locator('#render-status')).toContainText('Projection ready');const project=await backup(page);expect(new Set(Buffer.from(project.depth.labels,'base64'))).toEqual(new Set([0,1,2]));const png=PNG.sync.read(Buffer.from(project.photo.dataUrl.split(',')[1],'base64')),expected=scalarReference({width:png.width,height:png.height,rgba:new Uint8ClampedArray(png.data)},project.settings,new Uint8Array(Buffer.from(project.depth.labels,'base64')));const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Export PNG',exact:true}).click()]);const actual=PNG.sync.read(await readFile((await download.path())!));expect([actual.width,actual.height]).toEqual([32,24]);let error=0;for(let i=0;i<actual.data.length;i++)error=Math.max(error,Math.abs(actual.data[i]-expected.rgba[i]));expect(error).toBeLessThanOrEqual(1);expect(await backup(page)).toEqual(project);
});
