import { test, expect, type Page } from '@playwright/test';
import { writeFile } from 'node:fs/promises';
import { originalStudy, winnerStudy, originalPixels, sha256, backup, rendered, saved, rawRow, projectOf, openOriginal, restoreOriginal, rename, winner, protection, conflict, checkPng, transactionGate, waitGate, releaseGate, cleanupGate, abortNextPut, holdDecode, waitDecode, releaseDecode, holdFile, waitFile, releaseFile } from './saved-copy-fixtures.ts';

async function rawTitle(page:Page,text:string,caret=3){const title=page.locator('#project-title');await title.fill(text);await title.evaluate((node,caret)=>{const input=node as HTMLInputElement;input.dataset.independent117='same-title';input.setSelectionRange(caret,caret);},caret);return title;}
async function consent(page:Page,selector:string,accept:boolean){const event=page.waitForEvent('dialog'),click=page.locator(selector).click(),dialog=await event;const message=dialog.message();await(accept?dialog.accept():dialog.dismiss());await click;return message;}

// Literal complete values and numerical pixels were fixed before reading the
// new storage/UI producers. Gate helpers delay genuine browser work only.
test('two actual pages retain the complete winner while stale raw fields history and PNG remain local',async({page,context},info)=>{
 await openOriginal(page);const stale=await context.newPage();await restoreOriginal(stale);await winner(page);const state={row:await rawRow(page),winner:winnerStudy(),memory:{...originalStudy(),title:'Protected local study117'}};await holdDecode(stale);await rename(stale,state.memory.title);await waitDecode(stale);
 const numeric=stale.getByLabel('Target focal length',{exact:true});await numeric.fill('50.000');await numeric.evaluate(node=>node.setAttribute('data-independent117','numeric-node'));
 const title=await rawTitle(stale,'Unsubmitted title Ω',5);await releaseDecode(stale);await protection(stale);await expect(title).toBeFocused();expect(await rawRow(stale)).toEqual(state.row);expect(await title.evaluate(node=>(node as HTMLInputElement).selectionStart)).toBe(5);await expect(numeric).toHaveValue('50.000');await expect(numeric).toHaveAttribute('data-independent117','numeric-node');
 expect(await backup(stale,info.outputPath('local-complete-study.json'))).toEqual(state.memory);expect(await backup(page,info.outputPath('winner-complete-study.json'))).toEqual(state.winner);
 const localPng=await checkPng(stale,state.memory,info.outputPath('local-projection.png')),winnerPng=await checkPng(page,state.winner,info.outputPath('winner-projection.png'));
 await stale.getByRole('button',{name:'Undo',exact:true}).click();expect(await backup(stale)).toEqual(originalStudy());expect(await rawRow(stale)).toEqual(state.row);await stale.getByRole('button',{name:'Redo',exact:true}).click();expect(await backup(stale)).toEqual(state.memory);expect(await rawRow(stale)).toEqual(state.row);
 await stale.setViewportSize({width:390,height:844});expect(await stale.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await stale.screenshot({path:info.outputPath('protected-study-390.png'),fullPage:true});await writeFile(info.outputPath('original-image-and-projection-receipt.json'),JSON.stringify({originalRgbaSha256:sha256(originalPixels()),originalPhotoSha256:sha256(Buffer.from(originalStudy().photo.dataUrl.split(',')[1]!,'base64')),winnerMaskSha256:sha256(Buffer.from(winnerStudy().depth.labels,'base64')),localPng,winnerPng},null,2));await stale.close();
});

test('a conflict during a genuine unfinished brush gesture does not cancel its one local history edit',async({page,context})=>{
 await openOriginal(page);const stale=await context.newPage();await restoreOriginal(stale);await winner(page);const row=await rawRow(page);await holdDecode(stale);await rename(stale,'Pending local title117');await waitDecode(stale);
 await stale.getByLabel('Paint near',{exact:true}).check();await stale.getByLabel('Brush size',{exact:true}).fill('2');const canvas=stale.locator('#source-canvas');await canvas.scrollIntoViewIfNeeded();const box=(await canvas.boundingBox())!;await stale.mouse.move(box.x+box.width/2,box.y+box.height/2);await stale.mouse.down();
 try{await expect.poll(()=>canvas.evaluate((node:HTMLCanvasElement)=>node.hasPointerCapture(1))).toBe(true);await releaseDecode(stale);await expect(stale.locator('#save-status')).toContainText(/protected|changed|conflict|another tab/i);expect(await canvas.evaluate((node:HTMLCanvasElement)=>node.hasPointerCapture(1))).toBe(true);}finally{await stale.mouse.up();}
 await rendered(stale);const expected={...originalStudy(),title:'Pending local title117',depth:winnerStudy().depth};expect(await backup(stale)).toEqual(expected);expect(await rawRow(stale)).toEqual(row);await stale.getByRole('button',{name:'Undo',exact:true}).click();expect(await backup(stale)).toEqual({...originalStudy(),title:'Pending local title117'});await stale.getByRole('button',{name:'Redo',exact:true}).click();expect(await backup(stale)).toEqual(expected);expect(await rawRow(stale)).toEqual(row);await stale.close();
});

test('Reload requires discard consent and restores exact saved photo mask settings with a fresh history',async({page,context})=>{
 const stale=await context.newPage(),state=await conflict(page,stale);await rawTitle(stale,'Keep until consent');await stale.getByLabel('Target focal length',{exact:true}).fill('');await consent(stale,'#retry-load',false);expect(await backup(stale)).toEqual(state.memory);await expect(stale.locator('#project-title')).toHaveValue('Keep until consent');await expect(stale.getByLabel('Target focal length',{exact:true})).toHaveValue('');expect(await rawRow(stale)).toEqual(state.row);
 await consent(stale,'#retry-load',true);await expect(stale.locator('#project-title')).toHaveValue(state.winner.title);await expect(stale.locator('#save-status')).toContainText(/^Saved locally/);expect(await backup(stale)).toEqual(state.winner);await expect(stale.getByRole('button',{name:'Undo',exact:true})).toBeDisabled();await expect(stale.getByRole('button',{name:'Redo',exact:true})).toBeDisabled();expect(await rawRow(stale)).toEqual(state.row);await stale.close();
});

test('reviewed replacement names the saved winner and writes committed memory only without clearing raw fields',async({page,context})=>{
 const stale=await context.newPage(),state=await conflict(page,stale);const target=stale.getByLabel('Target focal length',{exact:true});await target.fill('50.000');await target.evaluate(node=>node.setAttribute('data-independent117','kept-number'));await rawTitle(stale,'Retain raw title  Ω',4);
 const rejected=await consent(stale,'#replace-saved-copy',false);expect(rejected).toContain(state.winner.title);expect(rejected).toMatch(/committed|unsubmitted|unapplied/i);expect(await rawRow(stale)).toEqual(state.row);await expect(stale.locator('#save-status')).toContainText('Saved-copy replacement was retired or canceled. Current work was kept.');await expect(stale.locator('#save-status')).toContainText('Current work stays in memory.');await expect(stale.locator('#retry-save')).toBeHidden();await expect(stale.locator('#replace-saved-copy')).toBeEnabled();
 expect(await consent(stale,'#replace-saved-copy',true)).toContain(state.winner.title);await saved(stale);expect(projectOf(await rawRow(stale))).toEqual(state.memory);expect(await backup(stale)).toEqual(state.memory);await expect(stale.locator('#project-title')).toHaveValue('Retain raw title  Ω');await expect(stale.locator('#project-title')).toHaveAttribute('data-independent117','same-title');await expect(target).toHaveValue('50.000');await expect(target).toHaveAttribute('data-independent117','kept-number');await stale.close();
});

test('a third actual writer during native confirmation defeats the reviewed copy without changing local memory',async({page,context})=>{
 const stale=await context.newPage(),state=await conflict(page,stale),third=await context.newPage();await third.goto('/');await expect(third.locator('#project-title')).toHaveValue(state.winner.title);const event=stale.waitForEvent('dialog'),click=stale.locator('#replace-saved-copy').click(),dialog=await event;expect(dialog.message()).toContain(state.winner.title);
 await rename(third,'Third writer117');await saved(third);const row=await rawRow(third);expect(projectOf(row)).toEqual({...state.winner,title:'Third writer117'});await dialog.accept();await click;await protection(stale);expect(await rawRow(stale)).toEqual(row);expect(await backup(stale)).toEqual(state.memory);await third.close();await stale.close();
});

test('actual put success followed by transaction abort preserves both studies until a fresh reviewed retry',async({page,context})=>{
 const stale=await context.newPage(),state=await conflict(page,stale);await abortNextPut(stale);await consent(stale,'#replace-saved-copy',true);await expect(stale.locator('#save-status')).toContainText(/failed|not saved|protected|could not/i);await expect(stale.locator('#replace-saved-copy')).toBeEnabled();expect(await rawRow(stale)).toEqual(state.row);expect(await backup(stale)).toEqual(state.memory);await consent(stale,'#replace-saved-copy',true);await saved(stale);expect(projectOf(await rawRow(stale))).toEqual(state.memory);await stale.close();
});

test('cancelled actual startup PNG decode cannot grant overwrite or open recovery before native drain',async({page,context})=>{
 await openOriginal(page);const row=await rawRow(page),late=await context.newPage();await holdDecode(late,true);await late.goto('/');await waitDecode(late);await late.getByRole('button',{name:'Cancel operation',exact:true}).click();await expect(late.locator('#save-status')).toContainText(/protected|cancel|not saved|memory/i);await expect(late.locator('#retry-load')).toBeDisabled();expect(await rawRow(page)).toEqual(row);await releaseDecode(late);await expect(late.locator('#retry-load')).toBeEnabled();await expect(late.locator('#source-canvas')).toBeHidden();
 const incoming={...originalStudy(),title:'Memory after cancelled restore117'};const importDialog=late.waitForEvent('dialog'),importAction=late.locator('#project-import').setInputFiles({name:'memory-only117.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(incoming))});const prompt=await importDialog;expect(prompt.message()).toContain('A protected saved copy is not replaced by this action.');await prompt.accept();await importAction;await expect(late.locator('#project-title')).toHaveValue(incoming.title);await expect(late.locator('#retry-save')).toBeHidden();expect(await backup(late)).toEqual(incoming);expect(await rawRow(page)).toEqual(row);await consent(late,'#retry-load',true);await expect(late.locator('#project-title')).toHaveValue(originalStudy().title);expect(await backup(late)).toEqual(originalStudy());expect(await rawRow(late)).toEqual(row);await late.close();
});

test('a held genuine File read cannot replace protected memory after changed-back numeric input',async({page,context})=>{
 const stale=await context.newPage(),state=await conflict(page,stale);await holdFile(stale);const incoming={...winnerStudy(),title:'Old delayed file117'};stale.once('dialog',dialog=>dialog.accept());await stale.locator('#project-import').setInputFiles({name:'held-original117.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(incoming))});await waitFile(stale);const number=stale.getByLabel('Target focal length',{exact:true});await number.fill('75');await number.fill('50');await number.evaluate(node=>node.setAttribute('data-independent117','pending-file-number'));await releaseFile(stale);await expect(stale.getByRole('button',{name:'Cancel operation',exact:true})).toBeHidden();await expect(number).toBeFocused();await expect(number).toHaveValue('50');await expect(number).toHaveAttribute('data-independent117','pending-file-number');expect(await backup(stale)).toEqual(state.memory);expect(await rawRow(stale)).toEqual(state.row);await protection(stale);await stale.close();
});

test('newer committed and raw input during held native replacement stays unsaved until manual Retry',async({page,context})=>{
 const stale=await context.newPage(),state=await conflict(page,stale);await transactionGate(stale,'readwrite');try{await consent(stale,'#replace-saved-copy',true);await waitGate(stale,true);await rename(stale,'Newer committed study117');await rawTitle(stale,'Newer unsent title117',6);const number=stale.getByLabel('Target focal length',{exact:true});await number.fill('50.000');await releaseGate(stale);await expect(stale.locator('#retry-save')).toBeVisible();await expect(stale.locator('#save-status')).not.toContainText(/^Saved locally/);expect(projectOf(await rawRow(stale))).toEqual(state.memory);const latest={...state.memory,title:'Newer committed study117'};expect(await backup(stale)).toEqual(latest);await expect(number).toHaveValue('50.000');await expect(stale.locator('#project-title')).toHaveValue('Newer unsent title117');await stale.locator('#retry-save').click();await saved(stale);expect(projectOf(await rawRow(stale))).toEqual(latest);await expect(number).toHaveValue('50.000');await expect(stale.locator('#project-title')).toHaveValue('Newer unsent title117');}finally{await cleanupGate(stale);await stale.close();}
});

test('controlled persisted return prevents an older save callback claiming newer raw input is Saved',async({page})=>{
 await openOriginal(page);await transactionGate(page,'readwrite');try{await rename(page,'Captured pending study117');await waitGate(page,true);await page.evaluate(()=>{dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true}));dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true}));});const title=await rawTitle(page,'Raw title after return117',4);await releaseGate(page);await expect(page.locator('#save-status')).not.toContainText(/^Saved locally/);await expect(page.locator('#retry-load')).toBeVisible();expect(projectOf(await rawRow(page))).toEqual({...originalStudy(),title:'Captured pending study117'});await expect(title).toBeFocused();await expect(title).toHaveValue('Raw title after return117');await expect(title).toHaveAttribute('data-independent117','same-title');expect(await title.evaluate(node=>(node as HTMLInputElement).selectionStart)).toBe(4);expect(await backup(page)).toEqual({...originalStudy(),title:'Captured pending study117'});}finally{await cleanupGate(page);}
});

test('changed-back input during actual replacement review suppresses obsolete consent and preserves caret',async({page,context})=>{
 const stale=await context.newPage(),state=await conflict(page,stale);let confirmations=0;stale.on('dialog',dialog=>{confirmations++;void dialog.dismiss();});await transactionGate(stale,'readonly');try{await stale.locator('#replace-saved-copy').click();await waitGate(stale);await rawTitle(stale,'Changed temporarily');const title=await rawTitle(stale,state.memory.title,7);await releaseGate(stale);await expect(stale.locator('#replace-saved-copy')).toBeEnabled();expect(confirmations).toBe(0);await expect(title).toBeFocused();await expect(title).toHaveValue(state.memory.title);expect(await title.evaluate(node=>(node as HTMLInputElement).selectionStart)).toBe(7);expect(await rawRow(stale)).toEqual(state.row);expect(await backup(stale)).toEqual(state.memory);}finally{await cleanupGate(stale);await stale.close();}
});

test('corrupt saved data with no photo exposes recovery and imported memory cannot silently overwrite it',async({page})=>{
 await page.goto('/');await expect(page.locator('#save-status')).toHaveText('Local storage ready · import a photo or study');const corrupt={schemaVersion:2,revision:'e759fe5e-5599-4aaf-a293-3a8b6f0e8117',project:{broken:'original malformed saved fixture117'}};
 await page.evaluate(value=>new Promise<void>((resolve,reject)=>{const request=indexedDB.open('lens-studio.v1',2);request.onsuccess=()=>{const db=request.result,tx=db.transaction('projects','readwrite');tx.objectStore('projects').put(value,'current');tx.oncomplete=()=>{db.close();resolve();};tx.onabort=()=>{db.close();reject(Error('Fixture write aborted'));};};request.onerror=()=>reject(Error('Fixture database failed'));}),corrupt);await page.reload();await expect(page.locator('#save-status')).toBeVisible();await expect(page.locator('#save-status')).toContainText(/protected|could not|not saved|invalid|unavailable/i);await expect(page.locator('#retry-load')).toBeEnabled();await expect(page.locator('#source-canvas')).toBeHidden();await expect(page.locator('#replace-saved-copy')).toBeDisabled();expect(await rawRow(page)).toEqual(corrupt);
 const importDialog=page.waitForEvent('dialog'),importAction=page.locator('#project-import').setInputFiles({name:'complete-memory117.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(originalStudy()))});const prompt=await importDialog;expect(prompt.message()).toContain('A protected saved copy is not replaced by this action.');await prompt.accept();await importAction;await expect(page.locator('#project-title')).toHaveValue(originalStudy().title);await expect(page.locator('#retry-save')).toBeHidden();expect(await backup(page)).toEqual(originalStudy());expect(await rawRow(page)).toEqual(corrupt);expect(await consent(page,'#replace-saved-copy',true)).toMatch(/unreadable|invalid|corrupt/i);await saved(page);expect(projectOf(await rawRow(page))).toEqual(originalStudy());
});


test('changed-back raw input during an actual reload bitmap keeps the prior study and cannot accept saved authority',async({page,context})=>{
 const stale=await context.newPage(),state=await conflict(page,stale);await holdDecode(stale);await consent(stale,'#retry-load',true);await waitDecode(stale);
 const number=stale.getByLabel('Target focal length',{exact:true});await number.fill('75');await number.fill('50.000');const title=await rawTitle(stale,state.memory.title,5);await releaseDecode(stale);
 await expect(stale.locator('#retry-load')).toBeEnabled();await expect(stale.locator('#retry-save')).toBeHidden();await expect(stale.locator('#save-status')).not.toContainText(/^Saved locally/);await expect(number).toHaveValue('50.000');await expect(title).toBeFocused();expect(await title.evaluate(node=>(node as HTMLInputElement).selectionStart)).toBe(5);expect(await backup(stale)).toEqual(state.memory);expect(await rawRow(stale)).toEqual(state.row);
 await rename(stale,'Still protected after rejected reload117');expect(await backup(stale)).toEqual({...state.memory,title:'Still protected after rejected reload117'});expect(await rawRow(stale)).toEqual(state.row);await stale.close();
});
