import {test,expect,type Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {PNG} from 'pngjs';
import {texture,independentPng} from '../oracle/fixtures';
import type {Project} from '../../src/types';
async function backup(page:Page):Promise<Project>{const [file]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Download project',exact:true}).click()]);return JSON.parse((await readFile((await file.path())!)).toString());}
async function png(page:Page){const [file]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Export PNG',exact:true}).click()]);const actual=PNG.sync.read(await readFile((await file.path())!));return [...actual.data];}
async function setup(page:Page){await page.goto('/');await expect(page.locator('#save-status')).not.toContainText('Checking local');await page.getByLabel('Import photo',{exact:true}).setInputFiles({name:'detailed-source.png',mimeType:'image/png',buffer:independentPng(texture(160,120))});await expect(page.locator('#render-status')).toContainText('Projection ready');}
async function point(page:Page,x:number,y:number){const b=(await page.locator('#source-canvas').boundingBox())!;await page.mouse.move(b.x+x*b.width/160,b.y+y*b.height/120);}
async function center(page:Page){return page.locator('#source-viewport').evaluate((surface:HTMLDivElement)=>{const canvas=surface.querySelector('canvas')!,b=canvas.getBoundingClientRect(),v=surface.getBoundingClientRect();return {x:Math.floor((v.left+surface.clientWidth/2-b.left)*160/b.width),y:Math.floor((v.top+surface.clientHeight/2-b.top)*120/b.height)};});}
test('zoom and pan preserve complete study result pixels drafts and redo without saved view state',async({page})=>{
 await setup(page);const original=await backup(page),pixels=await png(page),resultBounds=await page.locator('#result-canvas').boundingBox();await page.getByLabel('Target focal length',{exact:true}).fill('');for(const zoom of ['2','4','1']){await page.getByLabel('Source zoom',{exact:true}).selectOption(zoom);expect(await backup(page)).toEqual(original);await expect(page.getByLabel('Target focal length',{exact:true})).toHaveValue('');expect(await page.locator('#result-canvas').boundingBox()).toMatchObject({width:resultBounds!.width,height:resultBounds!.height});}expect(await png(page)).toEqual(pixels);await page.getByLabel('Source zoom',{exact:true}).selectOption('4');await page.getByRole('button',{name:'Pan source right',exact:true}).click();await page.getByRole('button',{name:'Pan source down',exact:true}).click();const scroll=await page.locator('#source-viewport').evaluate(el=>({x:el.scrollLeft,y:el.scrollTop}));expect(scroll.x).toBeGreaterThan(0);expect(scroll.y).toBeGreaterThan(0);expect(await backup(page)).toEqual(original);await expect(page.locator('#save-status')).toContainText('Saved locally');await page.reload();await expect(page.locator('#render-status')).toContainText('Projection ready');await expect(page.getByLabel('Source zoom',{exact:true})).toHaveValue('1');expect(await backup(page)).toEqual(original);
});
test('scaled scrolled native rectangle maps exact source pixels and zoom cancellation retains redo',async({page})=>{
 await setup(page);const original=await backup(page);await page.getByLabel('Source zoom',{exact:true}).selectOption('4');await page.getByRole('button',{name:'Pan source right',exact:true}).click();await page.getByRole('button',{name:'Pan source down',exact:true}).click();await page.locator('#source-viewport').scrollIntoViewIfNeeded();const c=await center(page);await page.getByLabel('Depth tool',{exact:true}).selectOption('rectangle');await page.getByLabel('Paint near',{exact:true}).check();await page.locator('#source-viewport').scrollIntoViewIfNeeded();await point(page,c.x-4,c.y-4);await page.mouse.down();await point(page,c.x+4,c.y+4);await page.mouse.up();const painted=await backup(page),labels=Buffer.from(painted.depth.labels,'base64');for(let y=0;y<120;y++)for(let x=0;x<160;x++)expect(labels[y*160+x]).toBe(x>=c.x-4&&x<c.x+4&&y>=c.y-4&&y<c.y+4?0:1);await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await backup(page)).toEqual(original);await page.getByLabel('Target focal length',{exact:true}).fill('');await page.locator('#source-viewport').scrollIntoViewIfNeeded();await point(page,c.x,c.y);await page.mouse.down();await page.getByLabel('Source zoom',{exact:true}).selectOption('2');await page.mouse.up();expect(await backup(page)).toEqual(original);await expect(page.getByLabel('Target focal length',{exact:true})).toHaveValue('');await page.getByRole('button',{name:'Redo',exact:true}).click();expect(await backup(page)).toEqual(painted);
});
test('390px source view stays contained and accessible panning preserves exact connected-color source identity',async({page})=>{
 await page.setViewportSize({width:390,height:844});await setup(page);const original=await backup(page);await page.getByLabel('Source zoom',{exact:true}).selectOption('4');await page.getByRole('button',{name:'Pan source right',exact:true}).focus();await page.keyboard.press('Enter');await page.getByRole('button',{name:'Pan source down',exact:true}).focus();await page.keyboard.press('Enter');await page.locator('#source-viewport').scrollIntoViewIfNeeded();const c=await center(page);await page.getByLabel('Depth tool',{exact:true}).selectOption('color');await page.getByLabel('Paint far',{exact:true}).check();await page.getByLabel('Color tolerance',{exact:true}).fill('255');await page.locator('#source-viewport').scrollIntoViewIfNeeded();await point(page,c.x+.5,c.y+.5);await page.mouse.down();await page.mouse.up();const next=await backup(page);expect(next).toEqual({...original,depth:next.depth});expect(Buffer.from(next.depth.labels,'base64').every(v=>v===2)).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('#source-view-controls').screenshot({path:test.info().outputPath('source-view-mobile.png')});
});

test('native wheel panning retires only the unfinished gesture and retains redo',async({page})=>{
 await setup(page);const original=await backup(page);await page.getByLabel('Depth tool',{exact:true}).selectOption('rectangle');await page.getByLabel('Paint near',{exact:true}).check();await page.locator('#source-viewport').scrollIntoViewIfNeeded();await point(page,75,55);await page.mouse.down();await point(page,85,65);await page.mouse.up();const painted=await backup(page);expect(painted.depth).not.toEqual(original.depth);await page.getByRole('button',{name:'Undo',exact:true}).click();await page.getByLabel('Source zoom',{exact:true}).selectOption('4');await page.locator('#source-viewport').scrollIntoViewIfNeeded();const c=await center(page);await point(page,c.x,c.y);await page.mouse.down();await expect(page.getByRole('button',{name:'Cancel depth gesture',exact:true})).toBeEnabled();const scroll=await page.locator('#source-viewport').evaluate(el=>el.scrollLeft);await page.mouse.wheel(90,120);await expect.poll(()=>page.locator('#source-viewport').evaluate(el=>el.scrollLeft)).toBeGreaterThan(scroll);await expect(page.getByRole('button',{name:'Cancel depth gesture',exact:true})).toBeDisabled();await page.mouse.up();expect(await backup(page)).toEqual(original);await page.getByRole('button',{name:'Redo',exact:true}).click();expect(await backup(page)).toEqual(painted);
});
